// Code generated by ent, DO NOT EDIT.

package upstreamaccount

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the upstreamaccount type in the database.
	Label = "upstream_account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldChannelID holds the string denoting the channel_id field in the database.
	FieldChannelID = "channel_id"
	// FieldPoolID holds the string denoting the pool_id field in the database.
	FieldPoolID = "pool_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCredentialType holds the string denoting the credential_type field in the database.
	FieldCredentialType = "credential_type"
	// FieldCredentials holds the string denoting the credentials field in the database.
	FieldCredentials = "credentials"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSchedulable holds the string denoting the schedulable field in the database.
	FieldSchedulable = "schedulable"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldWeight holds the string denoting the weight field in the database.
	FieldWeight = "weight"
	// FieldConcurrencyLimit holds the string denoting the concurrency_limit field in the database.
	FieldConcurrencyLimit = "concurrency_limit"
	// FieldProxyConfig holds the string denoting the proxy_config field in the database.
	FieldProxyConfig = "proxy_config"
	// FieldRateMultiplier holds the string denoting the rate_multiplier field in the database.
	FieldRateMultiplier = "rate_multiplier"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldLastUsedAt holds the string denoting the last_used_at field in the database.
	FieldLastUsedAt = "last_used_at"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldRateLimitResetAt holds the string denoting the rate_limit_reset_at field in the database.
	FieldRateLimitResetAt = "rate_limit_reset_at"
	// FieldOverloadUntil holds the string denoting the overload_until field in the database.
	FieldOverloadUntil = "overload_until"
	// FieldCooldownUntil holds the string denoting the cooldown_until field in the database.
	FieldCooldownUntil = "cooldown_until"
	// FieldCooldownReason holds the string denoting the cooldown_reason field in the database.
	FieldCooldownReason = "cooldown_reason"
	// FieldQuotaLimitMicros holds the string denoting the quota_limit_micros field in the database.
	FieldQuotaLimitMicros = "quota_limit_micros"
	// FieldQuotaUsedMicros holds the string denoting the quota_used_micros field in the database.
	FieldQuotaUsedMicros = "quota_used_micros"
	// EdgeChannel holds the string denoting the channel edge name in mutations.
	EdgeChannel = "channel"
	// EdgePool holds the string denoting the pool edge name in mutations.
	EdgePool = "pool"
	// EdgeExecutions holds the string denoting the executions edge name in mutations.
	EdgeExecutions = "executions"
	// Table holds the table name of the upstreamaccount in the database.
	Table = "upstream_accounts"
	// ChannelTable is the table that holds the channel relation/edge.
	ChannelTable = "upstream_accounts"
	// ChannelInverseTable is the table name for the Channel entity.
	// It exists in this package in order to avoid circular dependency with the "channel" package.
	ChannelInverseTable = "channels"
	// ChannelColumn is the table column denoting the channel relation/edge.
	ChannelColumn = "channel_id"
	// PoolTable is the table that holds the pool relation/edge.
	PoolTable = "upstream_accounts"
	// PoolInverseTable is the table name for the UpstreamAccountPool entity.
	// It exists in this package in order to avoid circular dependency with the "upstreamaccountpool" package.
	PoolInverseTable = "upstream_account_pools"
	// PoolColumn is the table column denoting the pool relation/edge.
	PoolColumn = "pool_id"
	// ExecutionsTable is the table that holds the executions relation/edge.
	ExecutionsTable = "request_executions"
	// ExecutionsInverseTable is the table name for the RequestExecution entity.
	// It exists in this package in order to avoid circular dependency with the "requestexecution" package.
	ExecutionsInverseTable = "request_executions"
	// ExecutionsColumn is the table column denoting the executions relation/edge.
	ExecutionsColumn = "upstream_account_id"
)

// Columns holds all SQL columns for upstreamaccount fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldChannelID,
	FieldPoolID,
	FieldName,
	FieldCredentialType,
	FieldCredentials,
	FieldStatus,
	FieldSchedulable,
	FieldPriority,
	FieldWeight,
	FieldConcurrencyLimit,
	FieldProxyConfig,
	FieldRateMultiplier,
	FieldExpiresAt,
	FieldLastUsedAt,
	FieldErrorMessage,
	FieldRateLimitResetAt,
	FieldOverloadUntil,
	FieldCooldownUntil,
	FieldCooldownReason,
	FieldQuotaLimitMicros,
	FieldQuotaUsedMicros,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/looplj/axonhub/internal/ent/runtime"
var (
	Hooks        [2]ent.Hook
	Interceptors [1]ent.Interceptor
	Policy       ent.Policy
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultDeletedAt holds the default value on creation for the "deleted_at" field.
	DefaultDeletedAt int
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultSchedulable holds the default value on creation for the "schedulable" field.
	DefaultSchedulable bool
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority int
	// DefaultWeight holds the default value on creation for the "weight" field.
	DefaultWeight int
	// DefaultConcurrencyLimit holds the default value on creation for the "concurrency_limit" field.
	DefaultConcurrencyLimit int
	// DefaultRateMultiplier holds the default value on creation for the "rate_multiplier" field.
	DefaultRateMultiplier float64
	// DefaultQuotaLimitMicros holds the default value on creation for the "quota_limit_micros" field.
	DefaultQuotaLimitMicros int64
	// DefaultQuotaUsedMicros holds the default value on creation for the "quota_used_micros" field.
	DefaultQuotaUsedMicros int64
)

// CredentialType defines the type for the "credential_type" enum field.
type CredentialType string

// CredentialTypeAPIKey is the default value of the CredentialType enum.
const DefaultCredentialType = CredentialTypeAPIKey

// CredentialType values.
const (
	CredentialTypeAPIKey CredentialType = "api_key"
	CredentialTypeOauth  CredentialType = "oauth"
	CredentialTypeCustom CredentialType = "custom"
)

func (ct CredentialType) String() string {
	return string(ct)
}

// CredentialTypeValidator is a validator for the "credential_type" field enum values. It is called by the builders before save.
func CredentialTypeValidator(ct CredentialType) error {
	switch ct {
	case CredentialTypeAPIKey, CredentialTypeOauth, CredentialTypeCustom:
		return nil
	default:
		return fmt.Errorf("upstreamaccount: invalid enum value for credential_type field: %q", ct)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive   Status = "active"
	StatusDisabled Status = "disabled"
	StatusArchived Status = "archived"
	StatusError    Status = "error"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusDisabled, StatusArchived, StatusError:
		return nil
	default:
		return fmt.Errorf("upstreamaccount: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the UpstreamAccount queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByChannelID orders the results by the channel_id field.
func ByChannelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelID, opts...).ToFunc()
}

// ByPoolID orders the results by the pool_id field.
func ByPoolID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPoolID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCredentialType orders the results by the credential_type field.
func ByCredentialType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCredentialType, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySchedulable orders the results by the schedulable field.
func BySchedulable(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSchedulable, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByWeight orders the results by the weight field.
func ByWeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeight, opts...).ToFunc()
}

// ByConcurrencyLimit orders the results by the concurrency_limit field.
func ByConcurrencyLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConcurrencyLimit, opts...).ToFunc()
}

// ByRateMultiplier orders the results by the rate_multiplier field.
func ByRateMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRateMultiplier, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByLastUsedAt orders the results by the last_used_at field.
func ByLastUsedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastUsedAt, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByRateLimitResetAt orders the results by the rate_limit_reset_at field.
func ByRateLimitResetAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRateLimitResetAt, opts...).ToFunc()
}

// ByOverloadUntil orders the results by the overload_until field.
func ByOverloadUntil(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOverloadUntil, opts...).ToFunc()
}

// ByCooldownUntil orders the results by the cooldown_until field.
func ByCooldownUntil(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCooldownUntil, opts...).ToFunc()
}

// ByCooldownReason orders the results by the cooldown_reason field.
func ByCooldownReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCooldownReason, opts...).ToFunc()
}

// ByQuotaLimitMicros orders the results by the quota_limit_micros field.
func ByQuotaLimitMicros(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuotaLimitMicros, opts...).ToFunc()
}

// ByQuotaUsedMicros orders the results by the quota_used_micros field.
func ByQuotaUsedMicros(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuotaUsedMicros, opts...).ToFunc()
}

// ByChannelField orders the results by channel field.
func ByChannelField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChannelStep(), sql.OrderByField(field, opts...))
	}
}

// ByPoolField orders the results by pool field.
func ByPoolField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPoolStep(), sql.OrderByField(field, opts...))
	}
}

// ByExecutionsCount orders the results by executions count.
func ByExecutionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newExecutionsStep(), opts...)
	}
}

// ByExecutions orders the results by executions terms.
func ByExecutions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newExecutionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newChannelStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChannelInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ChannelTable, ChannelColumn),
	)
}
func newPoolStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PoolInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PoolTable, PoolColumn),
	)
}
func newExecutionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ExecutionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ExecutionsTable, ExecutionsColumn),
	)
}

// MarshalGQL implements graphql.Marshaler interface.
func (e CredentialType) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *CredentialType) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = CredentialType(str)
	if err := CredentialTypeValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid CredentialType", str)
	}
	return nil
}

// MarshalGQL implements graphql.Marshaler interface.
func (e Status) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *Status) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = Status(str)
	if err := StatusValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid Status", str)
	}
	return nil
}
