// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/affiliateinvitation"
	"github.com/looplj/axonhub/internal/ent/affiliaterebate"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// AffiliateInvitationUpdate is the builder for updating AffiliateInvitation entities.
type AffiliateInvitationUpdate struct {
	config
	hooks     []Hook
	mutation  *AffiliateInvitationMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the AffiliateInvitationUpdate builder.
func (_u *AffiliateInvitationUpdate) Where(ps ...predicate.AffiliateInvitation) *AffiliateInvitationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AffiliateInvitationUpdate) SetUpdatedAt(v time.Time) *AffiliateInvitationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *AffiliateInvitationUpdate) SetStatus(v affiliateinvitation.Status) *AffiliateInvitationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AffiliateInvitationUpdate) SetNillableStatus(v *affiliateinvitation.Status) *AffiliateInvitationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *AffiliateInvitationUpdate) SetNotes(v string) *AffiliateInvitationUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *AffiliateInvitationUpdate) SetNillableNotes(v *string) *AffiliateInvitationUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// AddRebateIDs adds the "rebates" edge to the AffiliateRebate entity by IDs.
func (_u *AffiliateInvitationUpdate) AddRebateIDs(ids ...int) *AffiliateInvitationUpdate {
	_u.mutation.AddRebateIDs(ids...)
	return _u
}

// AddRebates adds the "rebates" edges to the AffiliateRebate entity.
func (_u *AffiliateInvitationUpdate) AddRebates(v ...*AffiliateRebate) *AffiliateInvitationUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRebateIDs(ids...)
}

// Mutation returns the AffiliateInvitationMutation object of the builder.
func (_u *AffiliateInvitationUpdate) Mutation() *AffiliateInvitationMutation {
	return _u.mutation
}

// ClearRebates clears all "rebates" edges to the AffiliateRebate entity.
func (_u *AffiliateInvitationUpdate) ClearRebates() *AffiliateInvitationUpdate {
	_u.mutation.ClearRebates()
	return _u
}

// RemoveRebateIDs removes the "rebates" edge to AffiliateRebate entities by IDs.
func (_u *AffiliateInvitationUpdate) RemoveRebateIDs(ids ...int) *AffiliateInvitationUpdate {
	_u.mutation.RemoveRebateIDs(ids...)
	return _u
}

// RemoveRebates removes "rebates" edges to AffiliateRebate entities.
func (_u *AffiliateInvitationUpdate) RemoveRebates(v ...*AffiliateRebate) *AffiliateInvitationUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRebateIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AffiliateInvitationUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AffiliateInvitationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AffiliateInvitationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AffiliateInvitationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AffiliateInvitationUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if affiliateinvitation.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized affiliateinvitation.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := affiliateinvitation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *AffiliateInvitationUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := affiliateinvitation.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AffiliateInvitation.status": %w`, err)}
		}
	}
	if _u.mutation.InviterCleared() && len(_u.mutation.InviterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AffiliateInvitation.inviter"`)
	}
	if _u.mutation.InviteeCleared() && len(_u.mutation.InviteeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AffiliateInvitation.invitee"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *AffiliateInvitationUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AffiliateInvitationUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *AffiliateInvitationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(affiliateinvitation.Table, affiliateinvitation.Columns, sqlgraph.NewFieldSpec(affiliateinvitation.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(affiliateinvitation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(affiliateinvitation.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(affiliateinvitation.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.RebatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   affiliateinvitation.RebatesTable,
			Columns: []string{affiliateinvitation.RebatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(affiliaterebate.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRebatesIDs(); len(nodes) > 0 && !_u.mutation.RebatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   affiliateinvitation.RebatesTable,
			Columns: []string{affiliateinvitation.RebatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(affiliaterebate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RebatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   affiliateinvitation.RebatesTable,
			Columns: []string{affiliateinvitation.RebatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(affiliaterebate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{affiliateinvitation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AffiliateInvitationUpdateOne is the builder for updating a single AffiliateInvitation entity.
type AffiliateInvitationUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *AffiliateInvitationMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AffiliateInvitationUpdateOne) SetUpdatedAt(v time.Time) *AffiliateInvitationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *AffiliateInvitationUpdateOne) SetStatus(v affiliateinvitation.Status) *AffiliateInvitationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AffiliateInvitationUpdateOne) SetNillableStatus(v *affiliateinvitation.Status) *AffiliateInvitationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *AffiliateInvitationUpdateOne) SetNotes(v string) *AffiliateInvitationUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *AffiliateInvitationUpdateOne) SetNillableNotes(v *string) *AffiliateInvitationUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// AddRebateIDs adds the "rebates" edge to the AffiliateRebate entity by IDs.
func (_u *AffiliateInvitationUpdateOne) AddRebateIDs(ids ...int) *AffiliateInvitationUpdateOne {
	_u.mutation.AddRebateIDs(ids...)
	return _u
}

// AddRebates adds the "rebates" edges to the AffiliateRebate entity.
func (_u *AffiliateInvitationUpdateOne) AddRebates(v ...*AffiliateRebate) *AffiliateInvitationUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRebateIDs(ids...)
}

// Mutation returns the AffiliateInvitationMutation object of the builder.
func (_u *AffiliateInvitationUpdateOne) Mutation() *AffiliateInvitationMutation {
	return _u.mutation
}

// ClearRebates clears all "rebates" edges to the AffiliateRebate entity.
func (_u *AffiliateInvitationUpdateOne) ClearRebates() *AffiliateInvitationUpdateOne {
	_u.mutation.ClearRebates()
	return _u
}

// RemoveRebateIDs removes the "rebates" edge to AffiliateRebate entities by IDs.
func (_u *AffiliateInvitationUpdateOne) RemoveRebateIDs(ids ...int) *AffiliateInvitationUpdateOne {
	_u.mutation.RemoveRebateIDs(ids...)
	return _u
}

// RemoveRebates removes "rebates" edges to AffiliateRebate entities.
func (_u *AffiliateInvitationUpdateOne) RemoveRebates(v ...*AffiliateRebate) *AffiliateInvitationUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRebateIDs(ids...)
}

// Where appends a list predicates to the AffiliateInvitationUpdate builder.
func (_u *AffiliateInvitationUpdateOne) Where(ps ...predicate.AffiliateInvitation) *AffiliateInvitationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AffiliateInvitationUpdateOne) Select(field string, fields ...string) *AffiliateInvitationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AffiliateInvitation entity.
func (_u *AffiliateInvitationUpdateOne) Save(ctx context.Context) (*AffiliateInvitation, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AffiliateInvitationUpdateOne) SaveX(ctx context.Context) *AffiliateInvitation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AffiliateInvitationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AffiliateInvitationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AffiliateInvitationUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if affiliateinvitation.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized affiliateinvitation.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := affiliateinvitation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *AffiliateInvitationUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := affiliateinvitation.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AffiliateInvitation.status": %w`, err)}
		}
	}
	if _u.mutation.InviterCleared() && len(_u.mutation.InviterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AffiliateInvitation.inviter"`)
	}
	if _u.mutation.InviteeCleared() && len(_u.mutation.InviteeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AffiliateInvitation.invitee"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *AffiliateInvitationUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AffiliateInvitationUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *AffiliateInvitationUpdateOne) sqlSave(ctx context.Context) (_node *AffiliateInvitation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(affiliateinvitation.Table, affiliateinvitation.Columns, sqlgraph.NewFieldSpec(affiliateinvitation.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AffiliateInvitation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, affiliateinvitation.FieldID)
		for _, f := range fields {
			if !affiliateinvitation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != affiliateinvitation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(affiliateinvitation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(affiliateinvitation.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(affiliateinvitation.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.RebatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   affiliateinvitation.RebatesTable,
			Columns: []string{affiliateinvitation.RebatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(affiliaterebate.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRebatesIDs(); len(nodes) > 0 && !_u.mutation.RebatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   affiliateinvitation.RebatesTable,
			Columns: []string{affiliateinvitation.RebatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(affiliaterebate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RebatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   affiliateinvitation.RebatesTable,
			Columns: []string{affiliateinvitation.RebatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(affiliaterebate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &AffiliateInvitation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{affiliateinvitation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
