// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/billingnotificationpreference"
	"github.com/looplj/axonhub/internal/ent/user"
)

// BillingNotificationPreferenceCreate is the builder for creating a BillingNotificationPreference entity.
type BillingNotificationPreferenceCreate struct {
	config
	mutation *BillingNotificationPreferenceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *BillingNotificationPreferenceCreate) SetCreatedAt(v time.Time) *BillingNotificationPreferenceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BillingNotificationPreferenceCreate) SetNillableCreatedAt(v *time.Time) *BillingNotificationPreferenceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BillingNotificationPreferenceCreate) SetUpdatedAt(v time.Time) *BillingNotificationPreferenceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BillingNotificationPreferenceCreate) SetNillableUpdatedAt(v *time.Time) *BillingNotificationPreferenceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *BillingNotificationPreferenceCreate) SetUserID(v int) *BillingNotificationPreferenceCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *BillingNotificationPreferenceCreate) SetEnabled(v bool) *BillingNotificationPreferenceCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *BillingNotificationPreferenceCreate) SetNillableEnabled(v *bool) *BillingNotificationPreferenceCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetLowBalanceEnabled sets the "low_balance_enabled" field.
func (_c *BillingNotificationPreferenceCreate) SetLowBalanceEnabled(v bool) *BillingNotificationPreferenceCreate {
	_c.mutation.SetLowBalanceEnabled(v)
	return _c
}

// SetNillableLowBalanceEnabled sets the "low_balance_enabled" field if the given value is not nil.
func (_c *BillingNotificationPreferenceCreate) SetNillableLowBalanceEnabled(v *bool) *BillingNotificationPreferenceCreate {
	if v != nil {
		_c.SetLowBalanceEnabled(*v)
	}
	return _c
}

// SetPaymentEnabled sets the "payment_enabled" field.
func (_c *BillingNotificationPreferenceCreate) SetPaymentEnabled(v bool) *BillingNotificationPreferenceCreate {
	_c.mutation.SetPaymentEnabled(v)
	return _c
}

// SetNillablePaymentEnabled sets the "payment_enabled" field if the given value is not nil.
func (_c *BillingNotificationPreferenceCreate) SetNillablePaymentEnabled(v *bool) *BillingNotificationPreferenceCreate {
	if v != nil {
		_c.SetPaymentEnabled(*v)
	}
	return _c
}

// SetSubscriptionEnabled sets the "subscription_enabled" field.
func (_c *BillingNotificationPreferenceCreate) SetSubscriptionEnabled(v bool) *BillingNotificationPreferenceCreate {
	_c.mutation.SetSubscriptionEnabled(v)
	return _c
}

// SetNillableSubscriptionEnabled sets the "subscription_enabled" field if the given value is not nil.
func (_c *BillingNotificationPreferenceCreate) SetNillableSubscriptionEnabled(v *bool) *BillingNotificationPreferenceCreate {
	if v != nil {
		_c.SetSubscriptionEnabled(*v)
	}
	return _c
}

// SetLargeConsumptionEnabled sets the "large_consumption_enabled" field.
func (_c *BillingNotificationPreferenceCreate) SetLargeConsumptionEnabled(v bool) *BillingNotificationPreferenceCreate {
	_c.mutation.SetLargeConsumptionEnabled(v)
	return _c
}

// SetNillableLargeConsumptionEnabled sets the "large_consumption_enabled" field if the given value is not nil.
func (_c *BillingNotificationPreferenceCreate) SetNillableLargeConsumptionEnabled(v *bool) *BillingNotificationPreferenceCreate {
	if v != nil {
		_c.SetLargeConsumptionEnabled(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *BillingNotificationPreferenceCreate) SetUser(v *User) *BillingNotificationPreferenceCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the BillingNotificationPreferenceMutation object of the builder.
func (_c *BillingNotificationPreferenceCreate) Mutation() *BillingNotificationPreferenceMutation {
	return _c.mutation
}

// Save creates the BillingNotificationPreference in the database.
func (_c *BillingNotificationPreferenceCreate) Save(ctx context.Context) (*BillingNotificationPreference, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BillingNotificationPreferenceCreate) SaveX(ctx context.Context) *BillingNotificationPreference {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BillingNotificationPreferenceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BillingNotificationPreferenceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BillingNotificationPreferenceCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if billingnotificationpreference.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized billingnotificationpreference.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := billingnotificationpreference.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if billingnotificationpreference.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized billingnotificationpreference.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := billingnotificationpreference.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := billingnotificationpreference.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.LowBalanceEnabled(); !ok {
		v := billingnotificationpreference.DefaultLowBalanceEnabled
		_c.mutation.SetLowBalanceEnabled(v)
	}
	if _, ok := _c.mutation.PaymentEnabled(); !ok {
		v := billingnotificationpreference.DefaultPaymentEnabled
		_c.mutation.SetPaymentEnabled(v)
	}
	if _, ok := _c.mutation.SubscriptionEnabled(); !ok {
		v := billingnotificationpreference.DefaultSubscriptionEnabled
		_c.mutation.SetSubscriptionEnabled(v)
	}
	if _, ok := _c.mutation.LargeConsumptionEnabled(); !ok {
		v := billingnotificationpreference.DefaultLargeConsumptionEnabled
		_c.mutation.SetLargeConsumptionEnabled(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *BillingNotificationPreferenceCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "BillingNotificationPreference.user_id"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "BillingNotificationPreference.enabled"`)}
	}
	if _, ok := _c.mutation.LowBalanceEnabled(); !ok {
		return &ValidationError{Name: "low_balance_enabled", err: errors.New(`ent: missing required field "BillingNotificationPreference.low_balance_enabled"`)}
	}
	if _, ok := _c.mutation.PaymentEnabled(); !ok {
		return &ValidationError{Name: "payment_enabled", err: errors.New(`ent: missing required field "BillingNotificationPreference.payment_enabled"`)}
	}
	if _, ok := _c.mutation.SubscriptionEnabled(); !ok {
		return &ValidationError{Name: "subscription_enabled", err: errors.New(`ent: missing required field "BillingNotificationPreference.subscription_enabled"`)}
	}
	if _, ok := _c.mutation.LargeConsumptionEnabled(); !ok {
		return &ValidationError{Name: "large_consumption_enabled", err: errors.New(`ent: missing required field "BillingNotificationPreference.large_consumption_enabled"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "BillingNotificationPreference.user"`)}
	}
	return nil
}

func (_c *BillingNotificationPreferenceCreate) sqlSave(ctx context.Context) (*BillingNotificationPreference, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BillingNotificationPreferenceCreate) createSpec() (*BillingNotificationPreference, *sqlgraph.CreateSpec) {
	var (
		_node = &BillingNotificationPreference{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(billingnotificationpreference.Table, sqlgraph.NewFieldSpec(billingnotificationpreference.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(billingnotificationpreference.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(billingnotificationpreference.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(billingnotificationpreference.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.LowBalanceEnabled(); ok {
		_spec.SetField(billingnotificationpreference.FieldLowBalanceEnabled, field.TypeBool, value)
		_node.LowBalanceEnabled = value
	}
	if value, ok := _c.mutation.PaymentEnabled(); ok {
		_spec.SetField(billingnotificationpreference.FieldPaymentEnabled, field.TypeBool, value)
		_node.PaymentEnabled = value
	}
	if value, ok := _c.mutation.SubscriptionEnabled(); ok {
		_spec.SetField(billingnotificationpreference.FieldSubscriptionEnabled, field.TypeBool, value)
		_node.SubscriptionEnabled = value
	}
	if value, ok := _c.mutation.LargeConsumptionEnabled(); ok {
		_spec.SetField(billingnotificationpreference.FieldLargeConsumptionEnabled, field.TypeBool, value)
		_node.LargeConsumptionEnabled = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   billingnotificationpreference.UserTable,
			Columns: []string{billingnotificationpreference.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BillingNotificationPreference.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BillingNotificationPreferenceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *BillingNotificationPreferenceCreate) OnConflict(opts ...sql.ConflictOption) *BillingNotificationPreferenceUpsertOne {
	_c.conflict = opts
	return &BillingNotificationPreferenceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BillingNotificationPreference.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BillingNotificationPreferenceCreate) OnConflictColumns(columns ...string) *BillingNotificationPreferenceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BillingNotificationPreferenceUpsertOne{
		create: _c,
	}
}

type (
	// BillingNotificationPreferenceUpsertOne is the builder for "upsert"-ing
	//  one BillingNotificationPreference node.
	BillingNotificationPreferenceUpsertOne struct {
		create *BillingNotificationPreferenceCreate
	}

	// BillingNotificationPreferenceUpsert is the "OnConflict" setter.
	BillingNotificationPreferenceUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *BillingNotificationPreferenceUpsert) SetUpdatedAt(v time.Time) *BillingNotificationPreferenceUpsert {
	u.Set(billingnotificationpreference.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BillingNotificationPreferenceUpsert) UpdateUpdatedAt() *BillingNotificationPreferenceUpsert {
	u.SetExcluded(billingnotificationpreference.FieldUpdatedAt)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *BillingNotificationPreferenceUpsert) SetEnabled(v bool) *BillingNotificationPreferenceUpsert {
	u.Set(billingnotificationpreference.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *BillingNotificationPreferenceUpsert) UpdateEnabled() *BillingNotificationPreferenceUpsert {
	u.SetExcluded(billingnotificationpreference.FieldEnabled)
	return u
}

// SetLowBalanceEnabled sets the "low_balance_enabled" field.
func (u *BillingNotificationPreferenceUpsert) SetLowBalanceEnabled(v bool) *BillingNotificationPreferenceUpsert {
	u.Set(billingnotificationpreference.FieldLowBalanceEnabled, v)
	return u
}

// UpdateLowBalanceEnabled sets the "low_balance_enabled" field to the value that was provided on create.
func (u *BillingNotificationPreferenceUpsert) UpdateLowBalanceEnabled() *BillingNotificationPreferenceUpsert {
	u.SetExcluded(billingnotificationpreference.FieldLowBalanceEnabled)
	return u
}

// SetPaymentEnabled sets the "payment_enabled" field.
func (u *BillingNotificationPreferenceUpsert) SetPaymentEnabled(v bool) *BillingNotificationPreferenceUpsert {
	u.Set(billingnotificationpreference.FieldPaymentEnabled, v)
	return u
}

// UpdatePaymentEnabled sets the "payment_enabled" field to the value that was provided on create.
func (u *BillingNotificationPreferenceUpsert) UpdatePaymentEnabled() *BillingNotificationPreferenceUpsert {
	u.SetExcluded(billingnotificationpreference.FieldPaymentEnabled)
	return u
}

// SetSubscriptionEnabled sets the "subscription_enabled" field.
func (u *BillingNotificationPreferenceUpsert) SetSubscriptionEnabled(v bool) *BillingNotificationPreferenceUpsert {
	u.Set(billingnotificationpreference.FieldSubscriptionEnabled, v)
	return u
}

// UpdateSubscriptionEnabled sets the "subscription_enabled" field to the value that was provided on create.
func (u *BillingNotificationPreferenceUpsert) UpdateSubscriptionEnabled() *BillingNotificationPreferenceUpsert {
	u.SetExcluded(billingnotificationpreference.FieldSubscriptionEnabled)
	return u
}

// SetLargeConsumptionEnabled sets the "large_consumption_enabled" field.
func (u *BillingNotificationPreferenceUpsert) SetLargeConsumptionEnabled(v bool) *BillingNotificationPreferenceUpsert {
	u.Set(billingnotificationpreference.FieldLargeConsumptionEnabled, v)
	return u
}

// UpdateLargeConsumptionEnabled sets the "large_consumption_enabled" field to the value that was provided on create.
func (u *BillingNotificationPreferenceUpsert) UpdateLargeConsumptionEnabled() *BillingNotificationPreferenceUpsert {
	u.SetExcluded(billingnotificationpreference.FieldLargeConsumptionEnabled)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.BillingNotificationPreference.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BillingNotificationPreferenceUpsertOne) UpdateNewValues() *BillingNotificationPreferenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(billingnotificationpreference.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(billingnotificationpreference.FieldUserID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BillingNotificationPreference.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BillingNotificationPreferenceUpsertOne) Ignore() *BillingNotificationPreferenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BillingNotificationPreferenceUpsertOne) DoNothing() *BillingNotificationPreferenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BillingNotificationPreferenceCreate.OnConflict
// documentation for more info.
func (u *BillingNotificationPreferenceUpsertOne) Update(set func(*BillingNotificationPreferenceUpsert)) *BillingNotificationPreferenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BillingNotificationPreferenceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BillingNotificationPreferenceUpsertOne) SetUpdatedAt(v time.Time) *BillingNotificationPreferenceUpsertOne {
	return u.Update(func(s *BillingNotificationPreferenceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BillingNotificationPreferenceUpsertOne) UpdateUpdatedAt() *BillingNotificationPreferenceUpsertOne {
	return u.Update(func(s *BillingNotificationPreferenceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetEnabled sets the "enabled" field.
func (u *BillingNotificationPreferenceUpsertOne) SetEnabled(v bool) *BillingNotificationPreferenceUpsertOne {
	return u.Update(func(s *BillingNotificationPreferenceUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *BillingNotificationPreferenceUpsertOne) UpdateEnabled() *BillingNotificationPreferenceUpsertOne {
	return u.Update(func(s *BillingNotificationPreferenceUpsert) {
		s.UpdateEnabled()
	})
}

// SetLowBalanceEnabled sets the "low_balance_enabled" field.
func (u *BillingNotificationPreferenceUpsertOne) SetLowBalanceEnabled(v bool) *BillingNotificationPreferenceUpsertOne {
	return u.Update(func(s *BillingNotificationPreferenceUpsert) {
		s.SetLowBalanceEnabled(v)
	})
}

// UpdateLowBalanceEnabled sets the "low_balance_enabled" field to the value that was provided on create.
func (u *BillingNotificationPreferenceUpsertOne) UpdateLowBalanceEnabled() *BillingNotificationPreferenceUpsertOne {
	return u.Update(func(s *BillingNotificationPreferenceUpsert) {
		s.UpdateLowBalanceEnabled()
	})
}

// SetPaymentEnabled sets the "payment_enabled" field.
func (u *BillingNotificationPreferenceUpsertOne) SetPaymentEnabled(v bool) *BillingNotificationPreferenceUpsertOne {
	return u.Update(func(s *BillingNotificationPreferenceUpsert) {
		s.SetPaymentEnabled(v)
	})
}

// UpdatePaymentEnabled sets the "payment_enabled" field to the value that was provided on create.
func (u *BillingNotificationPreferenceUpsertOne) UpdatePaymentEnabled() *BillingNotificationPreferenceUpsertOne {
	return u.Update(func(s *BillingNotificationPreferenceUpsert) {
		s.UpdatePaymentEnabled()
	})
}

// SetSubscriptionEnabled sets the "subscription_enabled" field.
func (u *BillingNotificationPreferenceUpsertOne) SetSubscriptionEnabled(v bool) *BillingNotificationPreferenceUpsertOne {
	return u.Update(func(s *BillingNotificationPreferenceUpsert) {
		s.SetSubscriptionEnabled(v)
	})
}

// UpdateSubscriptionEnabled sets the "subscription_enabled" field to the value that was provided on create.
func (u *BillingNotificationPreferenceUpsertOne) UpdateSubscriptionEnabled() *BillingNotificationPreferenceUpsertOne {
	return u.Update(func(s *BillingNotificationPreferenceUpsert) {
		s.UpdateSubscriptionEnabled()
	})
}

// SetLargeConsumptionEnabled sets the "large_consumption_enabled" field.
func (u *BillingNotificationPreferenceUpsertOne) SetLargeConsumptionEnabled(v bool) *BillingNotificationPreferenceUpsertOne {
	return u.Update(func(s *BillingNotificationPreferenceUpsert) {
		s.SetLargeConsumptionEnabled(v)
	})
}

// UpdateLargeConsumptionEnabled sets the "large_consumption_enabled" field to the value that was provided on create.
func (u *BillingNotificationPreferenceUpsertOne) UpdateLargeConsumptionEnabled() *BillingNotificationPreferenceUpsertOne {
	return u.Update(func(s *BillingNotificationPreferenceUpsert) {
		s.UpdateLargeConsumptionEnabled()
	})
}

// Exec executes the query.
func (u *BillingNotificationPreferenceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BillingNotificationPreferenceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BillingNotificationPreferenceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BillingNotificationPreferenceUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BillingNotificationPreferenceUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BillingNotificationPreferenceCreateBulk is the builder for creating many BillingNotificationPreference entities in bulk.
type BillingNotificationPreferenceCreateBulk struct {
	config
	err      error
	builders []*BillingNotificationPreferenceCreate
	conflict []sql.ConflictOption
}

// Save creates the BillingNotificationPreference entities in the database.
func (_c *BillingNotificationPreferenceCreateBulk) Save(ctx context.Context) ([]*BillingNotificationPreference, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BillingNotificationPreference, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BillingNotificationPreferenceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BillingNotificationPreferenceCreateBulk) SaveX(ctx context.Context) []*BillingNotificationPreference {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BillingNotificationPreferenceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BillingNotificationPreferenceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BillingNotificationPreference.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BillingNotificationPreferenceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *BillingNotificationPreferenceCreateBulk) OnConflict(opts ...sql.ConflictOption) *BillingNotificationPreferenceUpsertBulk {
	_c.conflict = opts
	return &BillingNotificationPreferenceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BillingNotificationPreference.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BillingNotificationPreferenceCreateBulk) OnConflictColumns(columns ...string) *BillingNotificationPreferenceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BillingNotificationPreferenceUpsertBulk{
		create: _c,
	}
}

// BillingNotificationPreferenceUpsertBulk is the builder for "upsert"-ing
// a bulk of BillingNotificationPreference nodes.
type BillingNotificationPreferenceUpsertBulk struct {
	create *BillingNotificationPreferenceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BillingNotificationPreference.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BillingNotificationPreferenceUpsertBulk) UpdateNewValues() *BillingNotificationPreferenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(billingnotificationpreference.FieldCreatedAt)
			}
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(billingnotificationpreference.FieldUserID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BillingNotificationPreference.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BillingNotificationPreferenceUpsertBulk) Ignore() *BillingNotificationPreferenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BillingNotificationPreferenceUpsertBulk) DoNothing() *BillingNotificationPreferenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BillingNotificationPreferenceCreateBulk.OnConflict
// documentation for more info.
func (u *BillingNotificationPreferenceUpsertBulk) Update(set func(*BillingNotificationPreferenceUpsert)) *BillingNotificationPreferenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BillingNotificationPreferenceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BillingNotificationPreferenceUpsertBulk) SetUpdatedAt(v time.Time) *BillingNotificationPreferenceUpsertBulk {
	return u.Update(func(s *BillingNotificationPreferenceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BillingNotificationPreferenceUpsertBulk) UpdateUpdatedAt() *BillingNotificationPreferenceUpsertBulk {
	return u.Update(func(s *BillingNotificationPreferenceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetEnabled sets the "enabled" field.
func (u *BillingNotificationPreferenceUpsertBulk) SetEnabled(v bool) *BillingNotificationPreferenceUpsertBulk {
	return u.Update(func(s *BillingNotificationPreferenceUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *BillingNotificationPreferenceUpsertBulk) UpdateEnabled() *BillingNotificationPreferenceUpsertBulk {
	return u.Update(func(s *BillingNotificationPreferenceUpsert) {
		s.UpdateEnabled()
	})
}

// SetLowBalanceEnabled sets the "low_balance_enabled" field.
func (u *BillingNotificationPreferenceUpsertBulk) SetLowBalanceEnabled(v bool) *BillingNotificationPreferenceUpsertBulk {
	return u.Update(func(s *BillingNotificationPreferenceUpsert) {
		s.SetLowBalanceEnabled(v)
	})
}

// UpdateLowBalanceEnabled sets the "low_balance_enabled" field to the value that was provided on create.
func (u *BillingNotificationPreferenceUpsertBulk) UpdateLowBalanceEnabled() *BillingNotificationPreferenceUpsertBulk {
	return u.Update(func(s *BillingNotificationPreferenceUpsert) {
		s.UpdateLowBalanceEnabled()
	})
}

// SetPaymentEnabled sets the "payment_enabled" field.
func (u *BillingNotificationPreferenceUpsertBulk) SetPaymentEnabled(v bool) *BillingNotificationPreferenceUpsertBulk {
	return u.Update(func(s *BillingNotificationPreferenceUpsert) {
		s.SetPaymentEnabled(v)
	})
}

// UpdatePaymentEnabled sets the "payment_enabled" field to the value that was provided on create.
func (u *BillingNotificationPreferenceUpsertBulk) UpdatePaymentEnabled() *BillingNotificationPreferenceUpsertBulk {
	return u.Update(func(s *BillingNotificationPreferenceUpsert) {
		s.UpdatePaymentEnabled()
	})
}

// SetSubscriptionEnabled sets the "subscription_enabled" field.
func (u *BillingNotificationPreferenceUpsertBulk) SetSubscriptionEnabled(v bool) *BillingNotificationPreferenceUpsertBulk {
	return u.Update(func(s *BillingNotificationPreferenceUpsert) {
		s.SetSubscriptionEnabled(v)
	})
}

// UpdateSubscriptionEnabled sets the "subscription_enabled" field to the value that was provided on create.
func (u *BillingNotificationPreferenceUpsertBulk) UpdateSubscriptionEnabled() *BillingNotificationPreferenceUpsertBulk {
	return u.Update(func(s *BillingNotificationPreferenceUpsert) {
		s.UpdateSubscriptionEnabled()
	})
}

// SetLargeConsumptionEnabled sets the "large_consumption_enabled" field.
func (u *BillingNotificationPreferenceUpsertBulk) SetLargeConsumptionEnabled(v bool) *BillingNotificationPreferenceUpsertBulk {
	return u.Update(func(s *BillingNotificationPreferenceUpsert) {
		s.SetLargeConsumptionEnabled(v)
	})
}

// UpdateLargeConsumptionEnabled sets the "large_consumption_enabled" field to the value that was provided on create.
func (u *BillingNotificationPreferenceUpsertBulk) UpdateLargeConsumptionEnabled() *BillingNotificationPreferenceUpsertBulk {
	return u.Update(func(s *BillingNotificationPreferenceUpsert) {
		s.UpdateLargeConsumptionEnabled()
	})
}

// Exec executes the query.
func (u *BillingNotificationPreferenceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BillingNotificationPreferenceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BillingNotificationPreferenceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BillingNotificationPreferenceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
