// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/billingaccount"
	"github.com/looplj/axonhub/internal/ent/billinghold"
	"github.com/looplj/axonhub/internal/ent/ledgertransaction"
	"github.com/looplj/axonhub/internal/ent/request"
	"github.com/looplj/axonhub/internal/ent/usagelog"
)

// BillingHold is the model entity for the BillingHold schema.
type BillingHold struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// BillingAccountID holds the value of the "billing_account_id" field.
	BillingAccountID int `json:"billing_account_id,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID int `json:"request_id,omitempty"`
	// UsageLogID holds the value of the "usage_log_id" field.
	UsageLogID int `json:"usage_log_id,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID int `json:"project_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int `json:"api_key_id,omitempty"`
	// ModelID holds the value of the "model_id" field.
	ModelID string `json:"model_id,omitempty"`
	// AmountMicros holds the value of the "amount_micros" field.
	AmountMicros int64 `json:"amount_micros,omitempty"`
	// CapturedAmountMicros holds the value of the "captured_amount_micros" field.
	CapturedAmountMicros int64 `json:"captured_amount_micros,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// Status holds the value of the "status" field.
	Status billinghold.Status `json:"status,omitempty"`
	// IdempotencyKey holds the value of the "idempotency_key" field.
	IdempotencyKey string `json:"idempotency_key,omitempty"`
	// ReferenceType holds the value of the "reference_type" field.
	ReferenceType string `json:"reference_type,omitempty"`
	// ReferenceID holds the value of the "reference_id" field.
	ReferenceID string `json:"reference_id,omitempty"`
	// CapturedLedgerTransactionID holds the value of the "captured_ledger_transaction_id" field.
	CapturedLedgerTransactionID int `json:"captured_ledger_transaction_id,omitempty"`
	// ReleaseReason holds the value of the "release_reason" field.
	ReleaseReason string `json:"release_reason,omitempty"`
	// ReleasedByType holds the value of the "released_by_type" field.
	ReleasedByType billinghold.ReleasedByType `json:"released_by_type,omitempty"`
	// ReleasedByID holds the value of the "released_by_id" field.
	ReleasedByID string `json:"released_by_id,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// CapturedAt holds the value of the "captured_at" field.
	CapturedAt *time.Time `json:"captured_at,omitempty"`
	// ReleasedAt holds the value of the "released_at" field.
	ReleasedAt *time.Time `json:"released_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BillingHoldQuery when eager-loading is set.
	Edges        BillingHoldEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BillingHoldEdges holds the relations/edges for other nodes in the graph.
type BillingHoldEdges struct {
	// BillingAccount holds the value of the billing_account edge.
	BillingAccount *BillingAccount `json:"billing_account,omitempty"`
	// Request holds the value of the request edge.
	Request *Request `json:"request,omitempty"`
	// UsageLog holds the value of the usage_log edge.
	UsageLog *UsageLog `json:"usage_log,omitempty"`
	// CapturedLedgerTransaction holds the value of the captured_ledger_transaction edge.
	CapturedLedgerTransaction *LedgerTransaction `json:"captured_ledger_transaction,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
	// totalCount holds the count of the edges above.
	totalCount [4]map[string]int
}

// BillingAccountOrErr returns the BillingAccount value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BillingHoldEdges) BillingAccountOrErr() (*BillingAccount, error) {
	if e.BillingAccount != nil {
		return e.BillingAccount, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: billingaccount.Label}
	}
	return nil, &NotLoadedError{edge: "billing_account"}
}

// RequestOrErr returns the Request value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BillingHoldEdges) RequestOrErr() (*Request, error) {
	if e.Request != nil {
		return e.Request, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: request.Label}
	}
	return nil, &NotLoadedError{edge: "request"}
}

// UsageLogOrErr returns the UsageLog value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BillingHoldEdges) UsageLogOrErr() (*UsageLog, error) {
	if e.UsageLog != nil {
		return e.UsageLog, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: usagelog.Label}
	}
	return nil, &NotLoadedError{edge: "usage_log"}
}

// CapturedLedgerTransactionOrErr returns the CapturedLedgerTransaction value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BillingHoldEdges) CapturedLedgerTransactionOrErr() (*LedgerTransaction, error) {
	if e.CapturedLedgerTransaction != nil {
		return e.CapturedLedgerTransaction, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: ledgertransaction.Label}
	}
	return nil, &NotLoadedError{edge: "captured_ledger_transaction"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BillingHold) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case billinghold.FieldID, billinghold.FieldBillingAccountID, billinghold.FieldRequestID, billinghold.FieldUsageLogID, billinghold.FieldProjectID, billinghold.FieldUserID, billinghold.FieldAPIKeyID, billinghold.FieldAmountMicros, billinghold.FieldCapturedAmountMicros, billinghold.FieldCapturedLedgerTransactionID:
			values[i] = new(sql.NullInt64)
		case billinghold.FieldModelID, billinghold.FieldCurrency, billinghold.FieldStatus, billinghold.FieldIdempotencyKey, billinghold.FieldReferenceType, billinghold.FieldReferenceID, billinghold.FieldReleaseReason, billinghold.FieldReleasedByType, billinghold.FieldReleasedByID:
			values[i] = new(sql.NullString)
		case billinghold.FieldCreatedAt, billinghold.FieldUpdatedAt, billinghold.FieldExpiresAt, billinghold.FieldCapturedAt, billinghold.FieldReleasedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BillingHold fields.
func (_m *BillingHold) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case billinghold.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case billinghold.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case billinghold.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case billinghold.FieldBillingAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field billing_account_id", values[i])
			} else if value.Valid {
				_m.BillingAccountID = int(value.Int64)
			}
		case billinghold.FieldRequestID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = int(value.Int64)
			}
		case billinghold.FieldUsageLogID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field usage_log_id", values[i])
			} else if value.Valid {
				_m.UsageLogID = int(value.Int64)
			}
		case billinghold.FieldProjectID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value.Valid {
				_m.ProjectID = int(value.Int64)
			}
		case billinghold.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case billinghold.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = int(value.Int64)
			}
		case billinghold.FieldModelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_id", values[i])
			} else if value.Valid {
				_m.ModelID = value.String
			}
		case billinghold.FieldAmountMicros:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount_micros", values[i])
			} else if value.Valid {
				_m.AmountMicros = value.Int64
			}
		case billinghold.FieldCapturedAmountMicros:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field captured_amount_micros", values[i])
			} else if value.Valid {
				_m.CapturedAmountMicros = value.Int64
			}
		case billinghold.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case billinghold.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = billinghold.Status(value.String)
			}
		case billinghold.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				_m.IdempotencyKey = value.String
			}
		case billinghold.FieldReferenceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reference_type", values[i])
			} else if value.Valid {
				_m.ReferenceType = value.String
			}
		case billinghold.FieldReferenceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reference_id", values[i])
			} else if value.Valid {
				_m.ReferenceID = value.String
			}
		case billinghold.FieldCapturedLedgerTransactionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field captured_ledger_transaction_id", values[i])
			} else if value.Valid {
				_m.CapturedLedgerTransactionID = int(value.Int64)
			}
		case billinghold.FieldReleaseReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field release_reason", values[i])
			} else if value.Valid {
				_m.ReleaseReason = value.String
			}
		case billinghold.FieldReleasedByType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field released_by_type", values[i])
			} else if value.Valid {
				_m.ReleasedByType = billinghold.ReleasedByType(value.String)
			}
		case billinghold.FieldReleasedByID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field released_by_id", values[i])
			} else if value.Valid {
				_m.ReleasedByID = value.String
			}
		case billinghold.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case billinghold.FieldCapturedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field captured_at", values[i])
			} else if value.Valid {
				_m.CapturedAt = new(time.Time)
				*_m.CapturedAt = value.Time
			}
		case billinghold.FieldReleasedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field released_at", values[i])
			} else if value.Valid {
				_m.ReleasedAt = new(time.Time)
				*_m.ReleasedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BillingHold.
// This includes values selected through modifiers, order, etc.
func (_m *BillingHold) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryBillingAccount queries the "billing_account" edge of the BillingHold entity.
func (_m *BillingHold) QueryBillingAccount() *BillingAccountQuery {
	return NewBillingHoldClient(_m.config).QueryBillingAccount(_m)
}

// QueryRequest queries the "request" edge of the BillingHold entity.
func (_m *BillingHold) QueryRequest() *RequestQuery {
	return NewBillingHoldClient(_m.config).QueryRequest(_m)
}

// QueryUsageLog queries the "usage_log" edge of the BillingHold entity.
func (_m *BillingHold) QueryUsageLog() *UsageLogQuery {
	return NewBillingHoldClient(_m.config).QueryUsageLog(_m)
}

// QueryCapturedLedgerTransaction queries the "captured_ledger_transaction" edge of the BillingHold entity.
func (_m *BillingHold) QueryCapturedLedgerTransaction() *LedgerTransactionQuery {
	return NewBillingHoldClient(_m.config).QueryCapturedLedgerTransaction(_m)
}

// Update returns a builder for updating this BillingHold.
// Note that you need to call BillingHold.Unwrap() before calling this method if this BillingHold
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BillingHold) Update() *BillingHoldUpdateOne {
	return NewBillingHoldClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BillingHold entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BillingHold) Unwrap() *BillingHold {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BillingHold is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BillingHold) String() string {
	var builder strings.Builder
	builder.WriteString("BillingHold(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("billing_account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.BillingAccountID))
	builder.WriteString(", ")
	builder.WriteString("request_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestID))
	builder.WriteString(", ")
	builder.WriteString("usage_log_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UsageLogID))
	builder.WriteString(", ")
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("model_id=")
	builder.WriteString(_m.ModelID)
	builder.WriteString(", ")
	builder.WriteString("amount_micros=")
	builder.WriteString(fmt.Sprintf("%v", _m.AmountMicros))
	builder.WriteString(", ")
	builder.WriteString("captured_amount_micros=")
	builder.WriteString(fmt.Sprintf("%v", _m.CapturedAmountMicros))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("idempotency_key=")
	builder.WriteString(_m.IdempotencyKey)
	builder.WriteString(", ")
	builder.WriteString("reference_type=")
	builder.WriteString(_m.ReferenceType)
	builder.WriteString(", ")
	builder.WriteString("reference_id=")
	builder.WriteString(_m.ReferenceID)
	builder.WriteString(", ")
	builder.WriteString("captured_ledger_transaction_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CapturedLedgerTransactionID))
	builder.WriteString(", ")
	builder.WriteString("release_reason=")
	builder.WriteString(_m.ReleaseReason)
	builder.WriteString(", ")
	builder.WriteString("released_by_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReleasedByType))
	builder.WriteString(", ")
	builder.WriteString("released_by_id=")
	builder.WriteString(_m.ReleasedByID)
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.CapturedAt; v != nil {
		builder.WriteString("captured_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ReleasedAt; v != nil {
		builder.WriteString("released_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// BillingHolds is a parsable slice of BillingHold.
type BillingHolds []*BillingHold
