// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (_m *APIKey) User(ctx context.Context) (*User, error) {
	result, err := _m.Edges.UserOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryUser().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *APIKey) Project(ctx context.Context) (*Project, error) {
	result, err := _m.Edges.ProjectOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryProject().Only(ctx)
	}
	return result, err
}

func (_m *APIKey) Requests(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *RequestOrder, where *RequestWhereInput,
) (*RequestConnection, error) {
	opts := []RequestPaginateOption{
		WithRequestOrder(orderBy),
		WithRequestFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[2][alias]
	if nodes, err := _m.NamedRequests(alias); err == nil || hasTotalCount {
		pager, err := newRequestPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &RequestConnection{Edges: []*RequestEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryRequests().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *APIKeyProfileTemplate) Project(ctx context.Context) (*Project, error) {
	result, err := _m.Edges.ProjectOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryProject().Only(ctx)
	}
	return result, err
}

func (_m *AffiliateInvitation) Inviter(ctx context.Context) (*User, error) {
	result, err := _m.Edges.InviterOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryInviter().Only(ctx)
	}
	return result, err
}

func (_m *AffiliateInvitation) Invitee(ctx context.Context) (*User, error) {
	result, err := _m.Edges.InviteeOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryInvitee().Only(ctx)
	}
	return result, err
}

func (_m *AffiliateInvitation) Rebates(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *AffiliateRebateOrder, where *AffiliateRebateWhereInput,
) (*AffiliateRebateConnection, error) {
	opts := []AffiliateRebatePaginateOption{
		WithAffiliateRebateOrder(orderBy),
		WithAffiliateRebateFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[2][alias]
	if nodes, err := _m.NamedRebates(alias); err == nil || hasTotalCount {
		pager, err := newAffiliateRebatePager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &AffiliateRebateConnection{Edges: []*AffiliateRebateEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryRebates().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *AffiliateProfile) User(ctx context.Context) (*User, error) {
	result, err := _m.Edges.UserOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryUser().Only(ctx)
	}
	return result, err
}

func (_m *AffiliateRebate) Invitation(ctx context.Context) (*AffiliateInvitation, error) {
	result, err := _m.Edges.InvitationOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryInvitation().Only(ctx)
	}
	return result, err
}

func (_m *AffiliateRebate) Inviter(ctx context.Context) (*User, error) {
	result, err := _m.Edges.InviterOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryInviter().Only(ctx)
	}
	return result, err
}

func (_m *AffiliateRebate) Invitee(ctx context.Context) (*User, error) {
	result, err := _m.Edges.InviteeOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryInvitee().Only(ctx)
	}
	return result, err
}

func (_m *AffiliateRebate) PaymentOrder(ctx context.Context) (*PaymentOrder, error) {
	result, err := _m.Edges.PaymentOrderOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryPaymentOrder().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *AffiliateRebate) UserSubscription(ctx context.Context) (*UserSubscription, error) {
	result, err := _m.Edges.UserSubscriptionOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryUserSubscription().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *AffiliateRebate) LedgerTransaction(ctx context.Context) (*LedgerTransaction, error) {
	result, err := _m.Edges.LedgerTransactionOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryLedgerTransaction().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *BillingAccount) Bindings(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *BillingAccountBindingOrder, where *BillingAccountBindingWhereInput,
) (*BillingAccountBindingConnection, error) {
	opts := []BillingAccountBindingPaginateOption{
		WithBillingAccountBindingOrder(orderBy),
		WithBillingAccountBindingFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[0][alias]
	if nodes, err := _m.NamedBindings(alias); err == nil || hasTotalCount {
		pager, err := newBillingAccountBindingPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &BillingAccountBindingConnection{Edges: []*BillingAccountBindingEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryBindings().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *BillingAccount) LedgerTransactions(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *LedgerTransactionOrder, where *LedgerTransactionWhereInput,
) (*LedgerTransactionConnection, error) {
	opts := []LedgerTransactionPaginateOption{
		WithLedgerTransactionOrder(orderBy),
		WithLedgerTransactionFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[1][alias]
	if nodes, err := _m.NamedLedgerTransactions(alias); err == nil || hasTotalCount {
		pager, err := newLedgerTransactionPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &LedgerTransactionConnection{Edges: []*LedgerTransactionEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryLedgerTransactions().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *BillingAccount) BillingHolds(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *BillingHoldOrder, where *BillingHoldWhereInput,
) (*BillingHoldConnection, error) {
	opts := []BillingHoldPaginateOption{
		WithBillingHoldOrder(orderBy),
		WithBillingHoldFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[2][alias]
	if nodes, err := _m.NamedBillingHolds(alias); err == nil || hasTotalCount {
		pager, err := newBillingHoldPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &BillingHoldConnection{Edges: []*BillingHoldEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryBillingHolds().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *BillingAccount) UsageBillingRecords(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *UsageBillingRecordOrder, where *UsageBillingRecordWhereInput,
) (*UsageBillingRecordConnection, error) {
	opts := []UsageBillingRecordPaginateOption{
		WithUsageBillingRecordOrder(orderBy),
		WithUsageBillingRecordFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[3][alias]
	if nodes, err := _m.NamedUsageBillingRecords(alias); err == nil || hasTotalCount {
		pager, err := newUsageBillingRecordPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &UsageBillingRecordConnection{Edges: []*UsageBillingRecordEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryUsageBillingRecords().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *BillingAccount) PaymentOrders(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *PaymentOrderOrder, where *PaymentOrderWhereInput,
) (*PaymentOrderConnection, error) {
	opts := []PaymentOrderPaginateOption{
		WithPaymentOrderOrder(orderBy),
		WithPaymentOrderFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[4][alias]
	if nodes, err := _m.NamedPaymentOrders(alias); err == nil || hasTotalCount {
		pager, err := newPaymentOrderPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &PaymentOrderConnection{Edges: []*PaymentOrderEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryPaymentOrders().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *BillingAccount) PromoUsages(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *PromoUsageOrder, where *PromoUsageWhereInput,
) (*PromoUsageConnection, error) {
	opts := []PromoUsagePaginateOption{
		WithPromoUsageOrder(orderBy),
		WithPromoUsageFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[5][alias]
	if nodes, err := _m.NamedPromoUsages(alias); err == nil || hasTotalCount {
		pager, err := newPromoUsagePager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &PromoUsageConnection{Edges: []*PromoUsageEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryPromoUsages().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *BillingAccount) BillingNotifications(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *BillingNotificationOrder, where *BillingNotificationWhereInput,
) (*BillingNotificationConnection, error) {
	opts := []BillingNotificationPaginateOption{
		WithBillingNotificationOrder(orderBy),
		WithBillingNotificationFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[6][alias]
	if nodes, err := _m.NamedBillingNotifications(alias); err == nil || hasTotalCount {
		pager, err := newBillingNotificationPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &BillingNotificationConnection{Edges: []*BillingNotificationEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryBillingNotifications().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *BillingAccountBinding) BillingAccount(ctx context.Context) (*BillingAccount, error) {
	result, err := _m.Edges.BillingAccountOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryBillingAccount().Only(ctx)
	}
	return result, err
}

func (_m *BillingHold) BillingAccount(ctx context.Context) (*BillingAccount, error) {
	result, err := _m.Edges.BillingAccountOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryBillingAccount().Only(ctx)
	}
	return result, err
}

func (_m *BillingHold) Request(ctx context.Context) (*Request, error) {
	result, err := _m.Edges.RequestOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryRequest().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *BillingHold) UsageLog(ctx context.Context) (*UsageLog, error) {
	result, err := _m.Edges.UsageLogOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryUsageLog().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *BillingHold) CapturedLedgerTransaction(ctx context.Context) (*LedgerTransaction, error) {
	result, err := _m.Edges.CapturedLedgerTransactionOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryCapturedLedgerTransaction().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *BillingNotification) User(ctx context.Context) (*User, error) {
	result, err := _m.Edges.UserOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryUser().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *BillingNotification) BillingAccount(ctx context.Context) (*BillingAccount, error) {
	result, err := _m.Edges.BillingAccountOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryBillingAccount().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *BillingNotification) PaymentOrder(ctx context.Context) (*PaymentOrder, error) {
	result, err := _m.Edges.PaymentOrderOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryPaymentOrder().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *BillingNotification) UserSubscription(ctx context.Context) (*UserSubscription, error) {
	result, err := _m.Edges.UserSubscriptionOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryUserSubscription().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *BillingNotification) UsageBillingRecord(ctx context.Context) (*UsageBillingRecord, error) {
	result, err := _m.Edges.UsageBillingRecordOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryUsageBillingRecord().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *BillingNotificationPreference) User(ctx context.Context) (*User, error) {
	result, err := _m.Edges.UserOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryUser().Only(ctx)
	}
	return result, err
}

func (_m *Channel) Requests(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *RequestOrder, where *RequestWhereInput,
) (*RequestConnection, error) {
	opts := []RequestPaginateOption{
		WithRequestOrder(orderBy),
		WithRequestFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[0][alias]
	if nodes, err := _m.NamedRequests(alias); err == nil || hasTotalCount {
		pager, err := newRequestPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &RequestConnection{Edges: []*RequestEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryRequests().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *Channel) Executions(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *RequestExecutionOrder, where *RequestExecutionWhereInput,
) (*RequestExecutionConnection, error) {
	opts := []RequestExecutionPaginateOption{
		WithRequestExecutionOrder(orderBy),
		WithRequestExecutionFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[1][alias]
	if nodes, err := _m.NamedExecutions(alias); err == nil || hasTotalCount {
		pager, err := newRequestExecutionPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &RequestExecutionConnection{Edges: []*RequestExecutionEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryExecutions().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *Channel) UsageLogs(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *UsageLogOrder, where *UsageLogWhereInput,
) (*UsageLogConnection, error) {
	opts := []UsageLogPaginateOption{
		WithUsageLogOrder(orderBy),
		WithUsageLogFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[2][alias]
	if nodes, err := _m.NamedUsageLogs(alias); err == nil || hasTotalCount {
		pager, err := newUsageLogPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &UsageLogConnection{Edges: []*UsageLogEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryUsageLogs().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *Channel) ChannelProbes(ctx context.Context) (result []*ChannelProbe, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedChannelProbes(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.ChannelProbesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryChannelProbes().All(ctx)
	}
	return result, err
}

func (_m *Channel) ChannelModelPrices(ctx context.Context) (result []*ChannelModelPrice, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedChannelModelPrices(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.ChannelModelPricesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryChannelModelPrices().All(ctx)
	}
	return result, err
}

func (_m *Channel) UpstreamAccountPools(ctx context.Context) (result []*UpstreamAccountPool, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedUpstreamAccountPools(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.UpstreamAccountPoolsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryUpstreamAccountPools().All(ctx)
	}
	return result, err
}

func (_m *Channel) UpstreamAccounts(ctx context.Context) (result []*UpstreamAccount, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedUpstreamAccounts(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.UpstreamAccountsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryUpstreamAccounts().All(ctx)
	}
	return result, err
}

func (_m *Channel) ProviderQuotaStatus(ctx context.Context) (*ProviderQuotaStatus, error) {
	result, err := _m.Edges.ProviderQuotaStatusOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryProviderQuotaStatus().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *ChannelModelPrice) Channel(ctx context.Context) (*Channel, error) {
	result, err := _m.Edges.ChannelOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryChannel().Only(ctx)
	}
	return result, err
}

func (_m *ChannelModelPrice) Versions(ctx context.Context) (result []*ChannelModelPriceVersion, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedVersions(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.VersionsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryVersions().All(ctx)
	}
	return result, err
}

func (_m *ChannelModelPriceVersion) ChannelModelPrice(ctx context.Context) (*ChannelModelPrice, error) {
	result, err := _m.Edges.ChannelModelPriceOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryChannelModelPrice().Only(ctx)
	}
	return result, err
}

func (_m *ChannelOverrideTemplate) User(ctx context.Context) (*User, error) {
	result, err := _m.Edges.UserOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryUser().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *ChannelProbe) Channel(ctx context.Context) (*Channel, error) {
	result, err := _m.Edges.ChannelOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryChannel().Only(ctx)
	}
	return result, err
}

func (_m *DataStorage) Requests(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *RequestOrder, where *RequestWhereInput,
) (*RequestConnection, error) {
	opts := []RequestPaginateOption{
		WithRequestOrder(orderBy),
		WithRequestFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[0][alias]
	if nodes, err := _m.NamedRequests(alias); err == nil || hasTotalCount {
		pager, err := newRequestPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &RequestConnection{Edges: []*RequestEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryRequests().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *DataStorage) Executions(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *RequestExecutionOrder, where *RequestExecutionWhereInput,
) (*RequestExecutionConnection, error) {
	opts := []RequestExecutionPaginateOption{
		WithRequestExecutionOrder(orderBy),
		WithRequestExecutionFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[1][alias]
	if nodes, err := _m.NamedExecutions(alias); err == nil || hasTotalCount {
		pager, err := newRequestExecutionPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &RequestExecutionConnection{Edges: []*RequestExecutionEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryExecutions().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *LedgerEntry) LedgerTransaction(ctx context.Context) (*LedgerTransaction, error) {
	result, err := _m.Edges.LedgerTransactionOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryLedgerTransaction().Only(ctx)
	}
	return result, err
}

func (_m *LedgerTransaction) BillingAccount(ctx context.Context) (*BillingAccount, error) {
	result, err := _m.Edges.BillingAccountOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryBillingAccount().Only(ctx)
	}
	return result, err
}

func (_m *LedgerTransaction) Entries(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *LedgerEntryOrder, where *LedgerEntryWhereInput,
) (*LedgerEntryConnection, error) {
	opts := []LedgerEntryPaginateOption{
		WithLedgerEntryOrder(orderBy),
		WithLedgerEntryFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[1][alias]
	if nodes, err := _m.NamedEntries(alias); err == nil || hasTotalCount {
		pager, err := newLedgerEntryPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &LedgerEntryConnection{Edges: []*LedgerEntryEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryEntries().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *LedgerTransaction) UsageBillingRecords(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *UsageBillingRecordOrder, where *UsageBillingRecordWhereInput,
) (*UsageBillingRecordConnection, error) {
	opts := []UsageBillingRecordPaginateOption{
		WithUsageBillingRecordOrder(orderBy),
		WithUsageBillingRecordFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[2][alias]
	if nodes, err := _m.NamedUsageBillingRecords(alias); err == nil || hasTotalCount {
		pager, err := newUsageBillingRecordPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &UsageBillingRecordConnection{Edges: []*UsageBillingRecordEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryUsageBillingRecords().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *LedgerTransaction) BillingHolds(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *BillingHoldOrder, where *BillingHoldWhereInput,
) (*BillingHoldConnection, error) {
	opts := []BillingHoldPaginateOption{
		WithBillingHoldOrder(orderBy),
		WithBillingHoldFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[3][alias]
	if nodes, err := _m.NamedBillingHolds(alias); err == nil || hasTotalCount {
		pager, err := newBillingHoldPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &BillingHoldConnection{Edges: []*BillingHoldEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryBillingHolds().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *LedgerTransaction) PaymentOrders(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *PaymentOrderOrder, where *PaymentOrderWhereInput,
) (*PaymentOrderConnection, error) {
	opts := []PaymentOrderPaginateOption{
		WithPaymentOrderOrder(orderBy),
		WithPaymentOrderFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[4][alias]
	if nodes, err := _m.NamedPaymentOrders(alias); err == nil || hasTotalCount {
		pager, err := newPaymentOrderPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &PaymentOrderConnection{Edges: []*PaymentOrderEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryPaymentOrders().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *LedgerTransaction) RedeemCodes(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *RedeemCodeOrder, where *RedeemCodeWhereInput,
) (*RedeemCodeConnection, error) {
	opts := []RedeemCodePaginateOption{
		WithRedeemCodeOrder(orderBy),
		WithRedeemCodeFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[5][alias]
	if nodes, err := _m.NamedRedeemCodes(alias); err == nil || hasTotalCount {
		pager, err := newRedeemCodePager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &RedeemCodeConnection{Edges: []*RedeemCodeEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryRedeemCodes().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *LedgerTransaction) PurchasedUserSubscriptions(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *UserSubscriptionOrder, where *UserSubscriptionWhereInput,
) (*UserSubscriptionConnection, error) {
	opts := []UserSubscriptionPaginateOption{
		WithUserSubscriptionOrder(orderBy),
		WithUserSubscriptionFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[6][alias]
	if nodes, err := _m.NamedPurchasedUserSubscriptions(alias); err == nil || hasTotalCount {
		pager, err := newUserSubscriptionPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &UserSubscriptionConnection{Edges: []*UserSubscriptionEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryPurchasedUserSubscriptions().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *LedgerTransaction) PromoUsages(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *PromoUsageOrder, where *PromoUsageWhereInput,
) (*PromoUsageConnection, error) {
	opts := []PromoUsagePaginateOption{
		WithPromoUsageOrder(orderBy),
		WithPromoUsageFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[7][alias]
	if nodes, err := _m.NamedPromoUsages(alias); err == nil || hasTotalCount {
		pager, err := newPromoUsagePager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &PromoUsageConnection{Edges: []*PromoUsageEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryPromoUsages().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *LedgerTransaction) AffiliateRebates(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *AffiliateRebateOrder, where *AffiliateRebateWhereInput,
) (*AffiliateRebateConnection, error) {
	opts := []AffiliateRebatePaginateOption{
		WithAffiliateRebateOrder(orderBy),
		WithAffiliateRebateFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[8][alias]
	if nodes, err := _m.NamedAffiliateRebates(alias); err == nil || hasTotalCount {
		pager, err := newAffiliateRebatePager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &AffiliateRebateConnection{Edges: []*AffiliateRebateEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryAffiliateRebates().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *OIDCIdentity) User(ctx context.Context) (*User, error) {
	result, err := _m.Edges.UserOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryUser().Only(ctx)
	}
	return result, err
}

func (_m *PaymentEvent) PaymentOrder(ctx context.Context) (*PaymentOrder, error) {
	result, err := _m.Edges.PaymentOrderOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryPaymentOrder().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *PaymentEvent) ProviderInstance(ctx context.Context) (*PaymentProviderInstance, error) {
	result, err := _m.Edges.ProviderInstanceOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryProviderInstance().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *PaymentOrder) BillingAccount(ctx context.Context) (*BillingAccount, error) {
	result, err := _m.Edges.BillingAccountOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryBillingAccount().Only(ctx)
	}
	return result, err
}

func (_m *PaymentOrder) ProviderInstance(ctx context.Context) (*PaymentProviderInstance, error) {
	result, err := _m.Edges.ProviderInstanceOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryProviderInstance().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *PaymentOrder) LedgerTransaction(ctx context.Context) (*LedgerTransaction, error) {
	result, err := _m.Edges.LedgerTransactionOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryLedgerTransaction().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *PaymentOrder) PromoCode(ctx context.Context) (*PromoCode, error) {
	result, err := _m.Edges.PromoCodeOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryPromoCode().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *PaymentOrder) PromoUsages(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *PromoUsageOrder, where *PromoUsageWhereInput,
) (*PromoUsageConnection, error) {
	opts := []PromoUsagePaginateOption{
		WithPromoUsageOrder(orderBy),
		WithPromoUsageFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[4][alias]
	if nodes, err := _m.NamedPromoUsages(alias); err == nil || hasTotalCount {
		pager, err := newPromoUsagePager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &PromoUsageConnection{Edges: []*PromoUsageEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryPromoUsages().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *PaymentOrder) PaymentEvents(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *PaymentEventOrder, where *PaymentEventWhereInput,
) (*PaymentEventConnection, error) {
	opts := []PaymentEventPaginateOption{
		WithPaymentEventOrder(orderBy),
		WithPaymentEventFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[5][alias]
	if nodes, err := _m.NamedPaymentEvents(alias); err == nil || hasTotalCount {
		pager, err := newPaymentEventPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &PaymentEventConnection{Edges: []*PaymentEventEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryPaymentEvents().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *PaymentOrder) AffiliateRebates(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *AffiliateRebateOrder, where *AffiliateRebateWhereInput,
) (*AffiliateRebateConnection, error) {
	opts := []AffiliateRebatePaginateOption{
		WithAffiliateRebateOrder(orderBy),
		WithAffiliateRebateFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[6][alias]
	if nodes, err := _m.NamedAffiliateRebates(alias); err == nil || hasTotalCount {
		pager, err := newAffiliateRebatePager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &AffiliateRebateConnection{Edges: []*AffiliateRebateEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryAffiliateRebates().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *PaymentOrder) BillingNotifications(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *BillingNotificationOrder, where *BillingNotificationWhereInput,
) (*BillingNotificationConnection, error) {
	opts := []BillingNotificationPaginateOption{
		WithBillingNotificationOrder(orderBy),
		WithBillingNotificationFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[7][alias]
	if nodes, err := _m.NamedBillingNotifications(alias); err == nil || hasTotalCount {
		pager, err := newBillingNotificationPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &BillingNotificationConnection{Edges: []*BillingNotificationEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryBillingNotifications().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *PaymentProviderInstance) PaymentOrders(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *PaymentOrderOrder, where *PaymentOrderWhereInput,
) (*PaymentOrderConnection, error) {
	opts := []PaymentOrderPaginateOption{
		WithPaymentOrderOrder(orderBy),
		WithPaymentOrderFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[0][alias]
	if nodes, err := _m.NamedPaymentOrders(alias); err == nil || hasTotalCount {
		pager, err := newPaymentOrderPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &PaymentOrderConnection{Edges: []*PaymentOrderEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryPaymentOrders().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *PaymentProviderInstance) PaymentEvents(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *PaymentEventOrder, where *PaymentEventWhereInput,
) (*PaymentEventConnection, error) {
	opts := []PaymentEventPaginateOption{
		WithPaymentEventOrder(orderBy),
		WithPaymentEventFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[1][alias]
	if nodes, err := _m.NamedPaymentEvents(alias); err == nil || hasTotalCount {
		pager, err := newPaymentEventPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &PaymentEventConnection{Edges: []*PaymentEventEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryPaymentEvents().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *Project) Users(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *UserOrder, where *UserWhereInput,
) (*UserConnection, error) {
	opts := []UserPaginateOption{
		WithUserOrder(orderBy),
		WithUserFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[0][alias]
	if nodes, err := _m.NamedUsers(alias); err == nil || hasTotalCount {
		pager, err := newUserPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &UserConnection{Edges: []*UserEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryUsers().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *Project) Roles(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *RoleOrder, where *RoleWhereInput,
) (*RoleConnection, error) {
	opts := []RolePaginateOption{
		WithRoleOrder(orderBy),
		WithRoleFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[1][alias]
	if nodes, err := _m.NamedRoles(alias); err == nil || hasTotalCount {
		pager, err := newRolePager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &RoleConnection{Edges: []*RoleEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryRoles().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *Project) APIKeys(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *APIKeyOrder, where *APIKeyWhereInput,
) (*APIKeyConnection, error) {
	opts := []APIKeyPaginateOption{
		WithAPIKeyOrder(orderBy),
		WithAPIKeyFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[2][alias]
	if nodes, err := _m.NamedAPIKeys(alias); err == nil || hasTotalCount {
		pager, err := newAPIKeyPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &APIKeyConnection{Edges: []*APIKeyEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryAPIKeys().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *Project) Requests(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *RequestOrder, where *RequestWhereInput,
) (*RequestConnection, error) {
	opts := []RequestPaginateOption{
		WithRequestOrder(orderBy),
		WithRequestFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[3][alias]
	if nodes, err := _m.NamedRequests(alias); err == nil || hasTotalCount {
		pager, err := newRequestPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &RequestConnection{Edges: []*RequestEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryRequests().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *Project) UsageLogs(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *UsageLogOrder, where *UsageLogWhereInput,
) (*UsageLogConnection, error) {
	opts := []UsageLogPaginateOption{
		WithUsageLogOrder(orderBy),
		WithUsageLogFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[4][alias]
	if nodes, err := _m.NamedUsageLogs(alias); err == nil || hasTotalCount {
		pager, err := newUsageLogPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &UsageLogConnection{Edges: []*UsageLogEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryUsageLogs().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *Project) Threads(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *ThreadOrder, where *ThreadWhereInput,
) (*ThreadConnection, error) {
	opts := []ThreadPaginateOption{
		WithThreadOrder(orderBy),
		WithThreadFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[5][alias]
	if nodes, err := _m.NamedThreads(alias); err == nil || hasTotalCount {
		pager, err := newThreadPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &ThreadConnection{Edges: []*ThreadEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryThreads().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *Project) Traces(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *TraceOrder, where *TraceWhereInput,
) (*TraceConnection, error) {
	opts := []TracePaginateOption{
		WithTraceOrder(orderBy),
		WithTraceFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[6][alias]
	if nodes, err := _m.NamedTraces(alias); err == nil || hasTotalCount {
		pager, err := newTracePager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &TraceConnection{Edges: []*TraceEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryTraces().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *Project) Prompts(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *PromptOrder, where *PromptWhereInput,
) (*PromptConnection, error) {
	opts := []PromptPaginateOption{
		WithPromptOrder(orderBy),
		WithPromptFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[7][alias]
	if nodes, err := _m.NamedPrompts(alias); err == nil || hasTotalCount {
		pager, err := newPromptPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &PromptConnection{Edges: []*PromptEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryPrompts().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *Project) APIKeyProfileTemplates(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *APIKeyProfileTemplateOrder, where *APIKeyProfileTemplateWhereInput,
) (*APIKeyProfileTemplateConnection, error) {
	opts := []APIKeyProfileTemplatePaginateOption{
		WithAPIKeyProfileTemplateOrder(orderBy),
		WithAPIKeyProfileTemplateFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[8][alias]
	if nodes, err := _m.NamedAPIKeyProfileTemplates(alias); err == nil || hasTotalCount {
		pager, err := newAPIKeyProfileTemplatePager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &APIKeyProfileTemplateConnection{Edges: []*APIKeyProfileTemplateEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryAPIKeyProfileTemplates().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *Project) ProjectUsers(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *UserProjectOrder, where *UserProjectWhereInput,
) (*UserProjectConnection, error) {
	opts := []UserProjectPaginateOption{
		WithUserProjectOrder(orderBy),
		WithUserProjectFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[9][alias]
	if nodes, err := _m.NamedProjectUsers(alias); err == nil || hasTotalCount {
		pager, err := newUserProjectPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &UserProjectConnection{Edges: []*UserProjectEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryProjectUsers().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *PromoCode) Usages(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *PromoUsageOrder, where *PromoUsageWhereInput,
) (*PromoUsageConnection, error) {
	opts := []PromoUsagePaginateOption{
		WithPromoUsageOrder(orderBy),
		WithPromoUsageFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[0][alias]
	if nodes, err := _m.NamedUsages(alias); err == nil || hasTotalCount {
		pager, err := newPromoUsagePager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &PromoUsageConnection{Edges: []*PromoUsageEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryUsages().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *PromoCode) PaymentOrders(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *PaymentOrderOrder, where *PaymentOrderWhereInput,
) (*PaymentOrderConnection, error) {
	opts := []PaymentOrderPaginateOption{
		WithPaymentOrderOrder(orderBy),
		WithPaymentOrderFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[1][alias]
	if nodes, err := _m.NamedPaymentOrders(alias); err == nil || hasTotalCount {
		pager, err := newPaymentOrderPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &PaymentOrderConnection{Edges: []*PaymentOrderEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryPaymentOrders().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *PromoCode) UserSubscriptions(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *UserSubscriptionOrder, where *UserSubscriptionWhereInput,
) (*UserSubscriptionConnection, error) {
	opts := []UserSubscriptionPaginateOption{
		WithUserSubscriptionOrder(orderBy),
		WithUserSubscriptionFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[2][alias]
	if nodes, err := _m.NamedUserSubscriptions(alias); err == nil || hasTotalCount {
		pager, err := newUserSubscriptionPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &UserSubscriptionConnection{Edges: []*UserSubscriptionEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryUserSubscriptions().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *PromoUsage) PromoCode(ctx context.Context) (*PromoCode, error) {
	result, err := _m.Edges.PromoCodeOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryPromoCode().Only(ctx)
	}
	return result, err
}

func (_m *PromoUsage) User(ctx context.Context) (*User, error) {
	result, err := _m.Edges.UserOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryUser().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *PromoUsage) BillingAccount(ctx context.Context) (*BillingAccount, error) {
	result, err := _m.Edges.BillingAccountOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryBillingAccount().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *PromoUsage) PaymentOrder(ctx context.Context) (*PaymentOrder, error) {
	result, err := _m.Edges.PaymentOrderOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryPaymentOrder().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *PromoUsage) UserSubscription(ctx context.Context) (*UserSubscription, error) {
	result, err := _m.Edges.UserSubscriptionOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryUserSubscription().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *PromoUsage) LedgerTransaction(ctx context.Context) (*LedgerTransaction, error) {
	result, err := _m.Edges.LedgerTransactionOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryLedgerTransaction().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *Prompt) Projects(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *ProjectOrder, where *ProjectWhereInput,
) (*ProjectConnection, error) {
	opts := []ProjectPaginateOption{
		WithProjectOrder(orderBy),
		WithProjectFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[0][alias]
	if nodes, err := _m.NamedProjects(alias); err == nil || hasTotalCount {
		pager, err := newProjectPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &ProjectConnection{Edges: []*ProjectEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryProjects().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *ProviderQuotaStatus) Channel(ctx context.Context) (*Channel, error) {
	result, err := _m.Edges.ChannelOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryChannel().Only(ctx)
	}
	return result, err
}

func (_m *RedeemCode) CreatedBy(ctx context.Context) (*User, error) {
	result, err := _m.Edges.CreatedByOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryCreatedBy().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *RedeemCode) UsedBy(ctx context.Context) (*User, error) {
	result, err := _m.Edges.UsedByOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryUsedBy().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *RedeemCode) LedgerTransaction(ctx context.Context) (*LedgerTransaction, error) {
	result, err := _m.Edges.LedgerTransactionOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryLedgerTransaction().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *Request) APIKey(ctx context.Context) (*APIKey, error) {
	result, err := _m.Edges.APIKeyOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryAPIKey().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *Request) Project(ctx context.Context) (*Project, error) {
	result, err := _m.Edges.ProjectOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryProject().Only(ctx)
	}
	return result, err
}

func (_m *Request) Trace(ctx context.Context) (*Trace, error) {
	result, err := _m.Edges.TraceOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryTrace().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *Request) DataStorage(ctx context.Context) (*DataStorage, error) {
	result, err := _m.Edges.DataStorageOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryDataStorage().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *Request) Executions(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *RequestExecutionOrder, where *RequestExecutionWhereInput,
) (*RequestExecutionConnection, error) {
	opts := []RequestExecutionPaginateOption{
		WithRequestExecutionOrder(orderBy),
		WithRequestExecutionFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[4][alias]
	if nodes, err := _m.NamedExecutions(alias); err == nil || hasTotalCount {
		pager, err := newRequestExecutionPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &RequestExecutionConnection{Edges: []*RequestExecutionEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryExecutions().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *Request) Channel(ctx context.Context) (*Channel, error) {
	result, err := _m.Edges.ChannelOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryChannel().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *Request) UsageLogs(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *UsageLogOrder, where *UsageLogWhereInput,
) (*UsageLogConnection, error) {
	opts := []UsageLogPaginateOption{
		WithUsageLogOrder(orderBy),
		WithUsageLogFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[6][alias]
	if nodes, err := _m.NamedUsageLogs(alias); err == nil || hasTotalCount {
		pager, err := newUsageLogPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &UsageLogConnection{Edges: []*UsageLogEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryUsageLogs().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *Request) BillingHolds(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *BillingHoldOrder, where *BillingHoldWhereInput,
) (*BillingHoldConnection, error) {
	opts := []BillingHoldPaginateOption{
		WithBillingHoldOrder(orderBy),
		WithBillingHoldFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[7][alias]
	if nodes, err := _m.NamedBillingHolds(alias); err == nil || hasTotalCount {
		pager, err := newBillingHoldPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &BillingHoldConnection{Edges: []*BillingHoldEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryBillingHolds().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *RequestExecution) Request(ctx context.Context) (*Request, error) {
	result, err := _m.Edges.RequestOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryRequest().Only(ctx)
	}
	return result, err
}

func (_m *RequestExecution) Channel(ctx context.Context) (*Channel, error) {
	result, err := _m.Edges.ChannelOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryChannel().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *RequestExecution) DataStorage(ctx context.Context) (*DataStorage, error) {
	result, err := _m.Edges.DataStorageOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryDataStorage().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *Role) Users(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *UserOrder, where *UserWhereInput,
) (*UserConnection, error) {
	opts := []UserPaginateOption{
		WithUserOrder(orderBy),
		WithUserFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[0][alias]
	if nodes, err := _m.NamedUsers(alias); err == nil || hasTotalCount {
		pager, err := newUserPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &UserConnection{Edges: []*UserEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryUsers().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *Role) Project(ctx context.Context) (*Project, error) {
	result, err := _m.Edges.ProjectOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryProject().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *Role) UserRoles(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *UserRoleOrder, where *UserRoleWhereInput,
) (*UserRoleConnection, error) {
	opts := []UserRolePaginateOption{
		WithUserRoleOrder(orderBy),
		WithUserRoleFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[2][alias]
	if nodes, err := _m.NamedUserRoles(alias); err == nil || hasTotalCount {
		pager, err := newUserRolePager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &UserRoleConnection{Edges: []*UserRoleEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryUserRoles().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *SubscriptionPlan) UserSubscriptions(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *UserSubscriptionOrder, where *UserSubscriptionWhereInput,
) (*UserSubscriptionConnection, error) {
	opts := []UserSubscriptionPaginateOption{
		WithUserSubscriptionOrder(orderBy),
		WithUserSubscriptionFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[0][alias]
	if nodes, err := _m.NamedUserSubscriptions(alias); err == nil || hasTotalCount {
		pager, err := newUserSubscriptionPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &UserSubscriptionConnection{Edges: []*UserSubscriptionEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryUserSubscriptions().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *Thread) Project(ctx context.Context) (*Project, error) {
	result, err := _m.Edges.ProjectOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryProject().Only(ctx)
	}
	return result, err
}

func (_m *Thread) Traces(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *TraceOrder, where *TraceWhereInput,
) (*TraceConnection, error) {
	opts := []TracePaginateOption{
		WithTraceOrder(orderBy),
		WithTraceFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[1][alias]
	if nodes, err := _m.NamedTraces(alias); err == nil || hasTotalCount {
		pager, err := newTracePager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &TraceConnection{Edges: []*TraceEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryTraces().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *Trace) Project(ctx context.Context) (*Project, error) {
	result, err := _m.Edges.ProjectOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryProject().Only(ctx)
	}
	return result, err
}

func (_m *Trace) Thread(ctx context.Context) (*Thread, error) {
	result, err := _m.Edges.ThreadOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryThread().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *Trace) Requests(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *RequestOrder, where *RequestWhereInput,
) (*RequestConnection, error) {
	opts := []RequestPaginateOption{
		WithRequestOrder(orderBy),
		WithRequestFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[2][alias]
	if nodes, err := _m.NamedRequests(alias); err == nil || hasTotalCount {
		pager, err := newRequestPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &RequestConnection{Edges: []*RequestEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryRequests().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *UpstreamAccount) Channel(ctx context.Context) (*Channel, error) {
	result, err := _m.Edges.ChannelOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryChannel().Only(ctx)
	}
	return result, err
}

func (_m *UpstreamAccount) Pool(ctx context.Context) (*UpstreamAccountPool, error) {
	result, err := _m.Edges.PoolOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryPool().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *UpstreamAccountPool) Channel(ctx context.Context) (*Channel, error) {
	result, err := _m.Edges.ChannelOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryChannel().Only(ctx)
	}
	return result, err
}

func (_m *UpstreamAccountPool) Accounts(ctx context.Context) (result []*UpstreamAccount, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedAccounts(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.AccountsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryAccounts().All(ctx)
	}
	return result, err
}

func (_m *UsageBillingRecord) UsageLog(ctx context.Context) (*UsageLog, error) {
	result, err := _m.Edges.UsageLogOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryUsageLog().Only(ctx)
	}
	return result, err
}

func (_m *UsageBillingRecord) BillingAccount(ctx context.Context) (*BillingAccount, error) {
	result, err := _m.Edges.BillingAccountOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryBillingAccount().Only(ctx)
	}
	return result, err
}

func (_m *UsageBillingRecord) LedgerTransaction(ctx context.Context) (*LedgerTransaction, error) {
	result, err := _m.Edges.LedgerTransactionOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryLedgerTransaction().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *UsageBillingRecord) UserSubscription(ctx context.Context) (*UserSubscription, error) {
	result, err := _m.Edges.UserSubscriptionOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryUserSubscription().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *UsageBillingRecord) BillingNotifications(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *BillingNotificationOrder, where *BillingNotificationWhereInput,
) (*BillingNotificationConnection, error) {
	opts := []BillingNotificationPaginateOption{
		WithBillingNotificationOrder(orderBy),
		WithBillingNotificationFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[4][alias]
	if nodes, err := _m.NamedBillingNotifications(alias); err == nil || hasTotalCount {
		pager, err := newBillingNotificationPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &BillingNotificationConnection{Edges: []*BillingNotificationEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryBillingNotifications().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *UsageLog) Request(ctx context.Context) (*Request, error) {
	result, err := _m.Edges.RequestOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryRequest().Only(ctx)
	}
	return result, err
}

func (_m *UsageLog) Project(ctx context.Context) (*Project, error) {
	result, err := _m.Edges.ProjectOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryProject().Only(ctx)
	}
	return result, err
}

func (_m *UsageLog) Channel(ctx context.Context) (*Channel, error) {
	result, err := _m.Edges.ChannelOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryChannel().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *UsageLog) UsageBillingRecords(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *UsageBillingRecordOrder, where *UsageBillingRecordWhereInput,
) (*UsageBillingRecordConnection, error) {
	opts := []UsageBillingRecordPaginateOption{
		WithUsageBillingRecordOrder(orderBy),
		WithUsageBillingRecordFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[3][alias]
	if nodes, err := _m.NamedUsageBillingRecords(alias); err == nil || hasTotalCount {
		pager, err := newUsageBillingRecordPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &UsageBillingRecordConnection{Edges: []*UsageBillingRecordEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryUsageBillingRecords().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *UsageLog) BillingHolds(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *BillingHoldOrder, where *BillingHoldWhereInput,
) (*BillingHoldConnection, error) {
	opts := []BillingHoldPaginateOption{
		WithBillingHoldOrder(orderBy),
		WithBillingHoldFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[4][alias]
	if nodes, err := _m.NamedBillingHolds(alias); err == nil || hasTotalCount {
		pager, err := newBillingHoldPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &BillingHoldConnection{Edges: []*BillingHoldEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryBillingHolds().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *User) Projects(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *ProjectOrder, where *ProjectWhereInput,
) (*ProjectConnection, error) {
	opts := []ProjectPaginateOption{
		WithProjectOrder(orderBy),
		WithProjectFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[0][alias]
	if nodes, err := _m.NamedProjects(alias); err == nil || hasTotalCount {
		pager, err := newProjectPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &ProjectConnection{Edges: []*ProjectEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryProjects().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *User) APIKeys(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *APIKeyOrder, where *APIKeyWhereInput,
) (*APIKeyConnection, error) {
	opts := []APIKeyPaginateOption{
		WithAPIKeyOrder(orderBy),
		WithAPIKeyFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[1][alias]
	if nodes, err := _m.NamedAPIKeys(alias); err == nil || hasTotalCount {
		pager, err := newAPIKeyPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &APIKeyConnection{Edges: []*APIKeyEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryAPIKeys().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *User) Roles(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *RoleOrder, where *RoleWhereInput,
) (*RoleConnection, error) {
	opts := []RolePaginateOption{
		WithRoleOrder(orderBy),
		WithRoleFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[2][alias]
	if nodes, err := _m.NamedRoles(alias); err == nil || hasTotalCount {
		pager, err := newRolePager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &RoleConnection{Edges: []*RoleEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryRoles().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *User) ChannelOverrideTemplates(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *ChannelOverrideTemplateOrder, where *ChannelOverrideTemplateWhereInput,
) (*ChannelOverrideTemplateConnection, error) {
	opts := []ChannelOverrideTemplatePaginateOption{
		WithChannelOverrideTemplateOrder(orderBy),
		WithChannelOverrideTemplateFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[3][alias]
	if nodes, err := _m.NamedChannelOverrideTemplates(alias); err == nil || hasTotalCount {
		pager, err := newChannelOverrideTemplatePager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &ChannelOverrideTemplateConnection{Edges: []*ChannelOverrideTemplateEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryChannelOverrideTemplates().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *User) OidcIdentities(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *OIDCIdentityOrder, where *OIDCIdentityWhereInput,
) (*OIDCIdentityConnection, error) {
	opts := []OIDCIdentityPaginateOption{
		WithOIDCIdentityOrder(orderBy),
		WithOIDCIdentityFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[4][alias]
	if nodes, err := _m.NamedOidcIdentities(alias); err == nil || hasTotalCount {
		pager, err := newOIDCIdentityPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &OIDCIdentityConnection{Edges: []*OIDCIdentityEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryOidcIdentities().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *User) CreatedRedeemCodes(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *RedeemCodeOrder, where *RedeemCodeWhereInput,
) (*RedeemCodeConnection, error) {
	opts := []RedeemCodePaginateOption{
		WithRedeemCodeOrder(orderBy),
		WithRedeemCodeFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[5][alias]
	if nodes, err := _m.NamedCreatedRedeemCodes(alias); err == nil || hasTotalCount {
		pager, err := newRedeemCodePager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &RedeemCodeConnection{Edges: []*RedeemCodeEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryCreatedRedeemCodes().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *User) UsedRedeemCodes(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *RedeemCodeOrder, where *RedeemCodeWhereInput,
) (*RedeemCodeConnection, error) {
	opts := []RedeemCodePaginateOption{
		WithRedeemCodeOrder(orderBy),
		WithRedeemCodeFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[6][alias]
	if nodes, err := _m.NamedUsedRedeemCodes(alias); err == nil || hasTotalCount {
		pager, err := newRedeemCodePager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &RedeemCodeConnection{Edges: []*RedeemCodeEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryUsedRedeemCodes().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *User) UserSubscriptions(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *UserSubscriptionOrder, where *UserSubscriptionWhereInput,
) (*UserSubscriptionConnection, error) {
	opts := []UserSubscriptionPaginateOption{
		WithUserSubscriptionOrder(orderBy),
		WithUserSubscriptionFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[7][alias]
	if nodes, err := _m.NamedUserSubscriptions(alias); err == nil || hasTotalCount {
		pager, err := newUserSubscriptionPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &UserSubscriptionConnection{Edges: []*UserSubscriptionEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryUserSubscriptions().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *User) AssignedUserSubscriptions(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *UserSubscriptionOrder, where *UserSubscriptionWhereInput,
) (*UserSubscriptionConnection, error) {
	opts := []UserSubscriptionPaginateOption{
		WithUserSubscriptionOrder(orderBy),
		WithUserSubscriptionFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[8][alias]
	if nodes, err := _m.NamedAssignedUserSubscriptions(alias); err == nil || hasTotalCount {
		pager, err := newUserSubscriptionPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &UserSubscriptionConnection{Edges: []*UserSubscriptionEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryAssignedUserSubscriptions().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *User) PromoUsages(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *PromoUsageOrder, where *PromoUsageWhereInput,
) (*PromoUsageConnection, error) {
	opts := []PromoUsagePaginateOption{
		WithPromoUsageOrder(orderBy),
		WithPromoUsageFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[9][alias]
	if nodes, err := _m.NamedPromoUsages(alias); err == nil || hasTotalCount {
		pager, err := newPromoUsagePager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &PromoUsageConnection{Edges: []*PromoUsageEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryPromoUsages().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *User) AffiliateProfiles(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *AffiliateProfileOrder, where *AffiliateProfileWhereInput,
) (*AffiliateProfileConnection, error) {
	opts := []AffiliateProfilePaginateOption{
		WithAffiliateProfileOrder(orderBy),
		WithAffiliateProfileFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[10][alias]
	if nodes, err := _m.NamedAffiliateProfiles(alias); err == nil || hasTotalCount {
		pager, err := newAffiliateProfilePager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &AffiliateProfileConnection{Edges: []*AffiliateProfileEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryAffiliateProfiles().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *User) AffiliateInviters(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *AffiliateInvitationOrder, where *AffiliateInvitationWhereInput,
) (*AffiliateInvitationConnection, error) {
	opts := []AffiliateInvitationPaginateOption{
		WithAffiliateInvitationOrder(orderBy),
		WithAffiliateInvitationFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[11][alias]
	if nodes, err := _m.NamedAffiliateInviters(alias); err == nil || hasTotalCount {
		pager, err := newAffiliateInvitationPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &AffiliateInvitationConnection{Edges: []*AffiliateInvitationEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryAffiliateInviters().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *User) AffiliateInvitees(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *AffiliateInvitationOrder, where *AffiliateInvitationWhereInput,
) (*AffiliateInvitationConnection, error) {
	opts := []AffiliateInvitationPaginateOption{
		WithAffiliateInvitationOrder(orderBy),
		WithAffiliateInvitationFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[12][alias]
	if nodes, err := _m.NamedAffiliateInvitees(alias); err == nil || hasTotalCount {
		pager, err := newAffiliateInvitationPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &AffiliateInvitationConnection{Edges: []*AffiliateInvitationEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryAffiliateInvitees().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *User) AffiliateRebatesEarned(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *AffiliateRebateOrder, where *AffiliateRebateWhereInput,
) (*AffiliateRebateConnection, error) {
	opts := []AffiliateRebatePaginateOption{
		WithAffiliateRebateOrder(orderBy),
		WithAffiliateRebateFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[13][alias]
	if nodes, err := _m.NamedAffiliateRebatesEarned(alias); err == nil || hasTotalCount {
		pager, err := newAffiliateRebatePager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &AffiliateRebateConnection{Edges: []*AffiliateRebateEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryAffiliateRebatesEarned().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *User) AffiliateRebatesGenerated(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *AffiliateRebateOrder, where *AffiliateRebateWhereInput,
) (*AffiliateRebateConnection, error) {
	opts := []AffiliateRebatePaginateOption{
		WithAffiliateRebateOrder(orderBy),
		WithAffiliateRebateFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[14][alias]
	if nodes, err := _m.NamedAffiliateRebatesGenerated(alias); err == nil || hasTotalCount {
		pager, err := newAffiliateRebatePager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &AffiliateRebateConnection{Edges: []*AffiliateRebateEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryAffiliateRebatesGenerated().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *User) BillingNotificationPreferences(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *BillingNotificationPreferenceOrder, where *BillingNotificationPreferenceWhereInput,
) (*BillingNotificationPreferenceConnection, error) {
	opts := []BillingNotificationPreferencePaginateOption{
		WithBillingNotificationPreferenceOrder(orderBy),
		WithBillingNotificationPreferenceFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[15][alias]
	if nodes, err := _m.NamedBillingNotificationPreferences(alias); err == nil || hasTotalCount {
		pager, err := newBillingNotificationPreferencePager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &BillingNotificationPreferenceConnection{Edges: []*BillingNotificationPreferenceEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryBillingNotificationPreferences().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *User) BillingNotifications(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *BillingNotificationOrder, where *BillingNotificationWhereInput,
) (*BillingNotificationConnection, error) {
	opts := []BillingNotificationPaginateOption{
		WithBillingNotificationOrder(orderBy),
		WithBillingNotificationFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[16][alias]
	if nodes, err := _m.NamedBillingNotifications(alias); err == nil || hasTotalCount {
		pager, err := newBillingNotificationPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &BillingNotificationConnection{Edges: []*BillingNotificationEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryBillingNotifications().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *User) ProjectUsers(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *UserProjectOrder, where *UserProjectWhereInput,
) (*UserProjectConnection, error) {
	opts := []UserProjectPaginateOption{
		WithUserProjectOrder(orderBy),
		WithUserProjectFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[17][alias]
	if nodes, err := _m.NamedProjectUsers(alias); err == nil || hasTotalCount {
		pager, err := newUserProjectPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &UserProjectConnection{Edges: []*UserProjectEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryProjectUsers().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *User) UserRoles(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *UserRoleOrder, where *UserRoleWhereInput,
) (*UserRoleConnection, error) {
	opts := []UserRolePaginateOption{
		WithUserRoleOrder(orderBy),
		WithUserRoleFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[18][alias]
	if nodes, err := _m.NamedUserRoles(alias); err == nil || hasTotalCount {
		pager, err := newUserRolePager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &UserRoleConnection{Edges: []*UserRoleEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryUserRoles().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *UserProject) User(ctx context.Context) (*User, error) {
	result, err := _m.Edges.UserOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryUser().Only(ctx)
	}
	return result, err
}

func (_m *UserProject) Project(ctx context.Context) (*Project, error) {
	result, err := _m.Edges.ProjectOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryProject().Only(ctx)
	}
	return result, err
}

func (_m *UserRole) User(ctx context.Context) (*User, error) {
	result, err := _m.Edges.UserOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryUser().Only(ctx)
	}
	return result, err
}

func (_m *UserRole) Role(ctx context.Context) (*Role, error) {
	result, err := _m.Edges.RoleOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryRole().Only(ctx)
	}
	return result, err
}

func (_m *UserSubscription) User(ctx context.Context) (*User, error) {
	result, err := _m.Edges.UserOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryUser().Only(ctx)
	}
	return result, err
}

func (_m *UserSubscription) Plan(ctx context.Context) (*SubscriptionPlan, error) {
	result, err := _m.Edges.PlanOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryPlan().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *UserSubscription) AssignedBy(ctx context.Context) (*User, error) {
	result, err := _m.Edges.AssignedByOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryAssignedBy().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *UserSubscription) PurchaseLedgerTransaction(ctx context.Context) (*LedgerTransaction, error) {
	result, err := _m.Edges.PurchaseLedgerTransactionOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryPurchaseLedgerTransaction().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *UserSubscription) PromoCode(ctx context.Context) (*PromoCode, error) {
	result, err := _m.Edges.PromoCodeOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryPromoCode().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *UserSubscription) PromoUsages(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *PromoUsageOrder, where *PromoUsageWhereInput,
) (*PromoUsageConnection, error) {
	opts := []PromoUsagePaginateOption{
		WithPromoUsageOrder(orderBy),
		WithPromoUsageFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[5][alias]
	if nodes, err := _m.NamedPromoUsages(alias); err == nil || hasTotalCount {
		pager, err := newPromoUsagePager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &PromoUsageConnection{Edges: []*PromoUsageEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryPromoUsages().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *UserSubscription) UsageBillingRecords(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *UsageBillingRecordOrder, where *UsageBillingRecordWhereInput,
) (*UsageBillingRecordConnection, error) {
	opts := []UsageBillingRecordPaginateOption{
		WithUsageBillingRecordOrder(orderBy),
		WithUsageBillingRecordFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[6][alias]
	if nodes, err := _m.NamedUsageBillingRecords(alias); err == nil || hasTotalCount {
		pager, err := newUsageBillingRecordPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &UsageBillingRecordConnection{Edges: []*UsageBillingRecordEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryUsageBillingRecords().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *UserSubscription) AffiliateRebates(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *AffiliateRebateOrder, where *AffiliateRebateWhereInput,
) (*AffiliateRebateConnection, error) {
	opts := []AffiliateRebatePaginateOption{
		WithAffiliateRebateOrder(orderBy),
		WithAffiliateRebateFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[7][alias]
	if nodes, err := _m.NamedAffiliateRebates(alias); err == nil || hasTotalCount {
		pager, err := newAffiliateRebatePager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &AffiliateRebateConnection{Edges: []*AffiliateRebateEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryAffiliateRebates().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *UserSubscription) BillingNotifications(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *BillingNotificationOrder, where *BillingNotificationWhereInput,
) (*BillingNotificationConnection, error) {
	opts := []BillingNotificationPaginateOption{
		WithBillingNotificationOrder(orderBy),
		WithBillingNotificationFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[8][alias]
	if nodes, err := _m.NamedBillingNotifications(alias); err == nil || hasTotalCount {
		pager, err := newBillingNotificationPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &BillingNotificationConnection{Edges: []*BillingNotificationEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryBillingNotifications().Paginate(ctx, after, first, before, last, opts...)
}
