// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/paymentevent"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/objects"
)

// PaymentEventUpdate is the builder for updating PaymentEvent entities.
type PaymentEventUpdate struct {
	config
	hooks     []Hook
	mutation  *PaymentEventMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the PaymentEventUpdate builder.
func (_u *PaymentEventUpdate) Where(ps ...predicate.PaymentEvent) *PaymentEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentEventUpdate) SetUpdatedAt(v time.Time) *PaymentEventUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPayload sets the "payload" field.
func (_u *PaymentEventUpdate) SetPayload(v objects.JSONRawMessage) *PaymentEventUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// AppendPayload appends value to the "payload" field.
func (_u *PaymentEventUpdate) AppendPayload(v objects.JSONRawMessage) *PaymentEventUpdate {
	_u.mutation.AppendPayload(v)
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *PaymentEventUpdate) ClearPayload() *PaymentEventUpdate {
	_u.mutation.ClearPayload()
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentEventUpdate) SetStatus(v paymentevent.Status) *PaymentEventUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentEventUpdate) SetNillableStatus(v *paymentevent.Status) *PaymentEventUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *PaymentEventUpdate) SetError(v string) *PaymentEventUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *PaymentEventUpdate) SetNillableError(v *string) *PaymentEventUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// Mutation returns the PaymentEventMutation object of the builder.
func (_u *PaymentEventUpdate) Mutation() *PaymentEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentEventUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentEventUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if paymentevent.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized paymentevent.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := paymentevent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentEventUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := paymentevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentEvent.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *PaymentEventUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PaymentEventUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *PaymentEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentevent.Table, paymentevent.Columns, sqlgraph.NewFieldSpec(paymentevent.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(paymentevent.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPayload(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, paymentevent.FieldPayload, value)
		})
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(paymentevent.FieldPayload, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentevent.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(paymentevent.FieldError, field.TypeString, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentEventUpdateOne is the builder for updating a single PaymentEvent entity.
type PaymentEventUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *PaymentEventMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentEventUpdateOne) SetUpdatedAt(v time.Time) *PaymentEventUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPayload sets the "payload" field.
func (_u *PaymentEventUpdateOne) SetPayload(v objects.JSONRawMessage) *PaymentEventUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// AppendPayload appends value to the "payload" field.
func (_u *PaymentEventUpdateOne) AppendPayload(v objects.JSONRawMessage) *PaymentEventUpdateOne {
	_u.mutation.AppendPayload(v)
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *PaymentEventUpdateOne) ClearPayload() *PaymentEventUpdateOne {
	_u.mutation.ClearPayload()
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentEventUpdateOne) SetStatus(v paymentevent.Status) *PaymentEventUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentEventUpdateOne) SetNillableStatus(v *paymentevent.Status) *PaymentEventUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *PaymentEventUpdateOne) SetError(v string) *PaymentEventUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *PaymentEventUpdateOne) SetNillableError(v *string) *PaymentEventUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// Mutation returns the PaymentEventMutation object of the builder.
func (_u *PaymentEventUpdateOne) Mutation() *PaymentEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the PaymentEventUpdate builder.
func (_u *PaymentEventUpdateOne) Where(ps ...predicate.PaymentEvent) *PaymentEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentEventUpdateOne) Select(field string, fields ...string) *PaymentEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PaymentEvent entity.
func (_u *PaymentEventUpdateOne) Save(ctx context.Context) (*PaymentEvent, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentEventUpdateOne) SaveX(ctx context.Context) *PaymentEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentEventUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if paymentevent.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized paymentevent.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := paymentevent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentEventUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := paymentevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentEvent.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *PaymentEventUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PaymentEventUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *PaymentEventUpdateOne) sqlSave(ctx context.Context) (_node *PaymentEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentevent.Table, paymentevent.Columns, sqlgraph.NewFieldSpec(paymentevent.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaymentEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentevent.FieldID)
		for _, f := range fields {
			if !paymentevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paymentevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(paymentevent.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPayload(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, paymentevent.FieldPayload, value)
		})
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(paymentevent.FieldPayload, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentevent.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(paymentevent.FieldError, field.TypeString, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &PaymentEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
