// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/paymentevent"
	"github.com/looplj/axonhub/internal/ent/paymentorder"
	"github.com/looplj/axonhub/internal/ent/paymentproviderinstance"
	"github.com/looplj/axonhub/internal/objects"
)

// PaymentEvent is the model entity for the PaymentEvent schema.
type PaymentEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Idempotency key for provider callback or internal payment event.
	EventKey string `json:"event_key,omitempty"`
	// PaymentOrderID holds the value of the "payment_order_id" field.
	PaymentOrderID *int `json:"payment_order_id,omitempty"`
	// ProviderInstanceID holds the value of the "provider_instance_id" field.
	ProviderInstanceID *int `json:"provider_instance_id,omitempty"`
	// ProviderType holds the value of the "provider_type" field.
	ProviderType paymentevent.ProviderType `json:"provider_type,omitempty"`
	// Provider event type, for example paid/refund/notify.
	EventType string `json:"event_type,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload objects.JSONRawMessage `json:"payload,omitempty"`
	// Status holds the value of the "status" field.
	Status paymentevent.Status `json:"status,omitempty"`
	// Error holds the value of the "error" field.
	Error string `json:"error,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PaymentEventQuery when eager-loading is set.
	Edges        PaymentEventEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PaymentEventEdges holds the relations/edges for other nodes in the graph.
type PaymentEventEdges struct {
	// PaymentOrder holds the value of the payment_order edge.
	PaymentOrder *PaymentOrder `json:"payment_order,omitempty"`
	// ProviderInstance holds the value of the provider_instance edge.
	ProviderInstance *PaymentProviderInstance `json:"provider_instance,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
	// totalCount holds the count of the edges above.
	totalCount [2]map[string]int
}

// PaymentOrderOrErr returns the PaymentOrder value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PaymentEventEdges) PaymentOrderOrErr() (*PaymentOrder, error) {
	if e.PaymentOrder != nil {
		return e.PaymentOrder, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: paymentorder.Label}
	}
	return nil, &NotLoadedError{edge: "payment_order"}
}

// ProviderInstanceOrErr returns the ProviderInstance value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PaymentEventEdges) ProviderInstanceOrErr() (*PaymentProviderInstance, error) {
	if e.ProviderInstance != nil {
		return e.ProviderInstance, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: paymentproviderinstance.Label}
	}
	return nil, &NotLoadedError{edge: "provider_instance"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PaymentEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case paymentevent.FieldPayload:
			values[i] = new([]byte)
		case paymentevent.FieldID, paymentevent.FieldPaymentOrderID, paymentevent.FieldProviderInstanceID:
			values[i] = new(sql.NullInt64)
		case paymentevent.FieldEventKey, paymentevent.FieldProviderType, paymentevent.FieldEventType, paymentevent.FieldStatus, paymentevent.FieldError:
			values[i] = new(sql.NullString)
		case paymentevent.FieldCreatedAt, paymentevent.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PaymentEvent fields.
func (_m *PaymentEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case paymentevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case paymentevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case paymentevent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case paymentevent.FieldEventKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_key", values[i])
			} else if value.Valid {
				_m.EventKey = value.String
			}
		case paymentevent.FieldPaymentOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field payment_order_id", values[i])
			} else if value.Valid {
				_m.PaymentOrderID = new(int)
				*_m.PaymentOrderID = int(value.Int64)
			}
		case paymentevent.FieldProviderInstanceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field provider_instance_id", values[i])
			} else if value.Valid {
				_m.ProviderInstanceID = new(int)
				*_m.ProviderInstanceID = int(value.Int64)
			}
		case paymentevent.FieldProviderType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_type", values[i])
			} else if value.Valid {
				_m.ProviderType = paymentevent.ProviderType(value.String)
			}
		case paymentevent.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				_m.EventType = value.String
			}
		case paymentevent.FieldPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Payload); err != nil {
					return fmt.Errorf("unmarshal field payload: %w", err)
				}
			}
		case paymentevent.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = paymentevent.Status(value.String)
			}
		case paymentevent.FieldError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error", values[i])
			} else if value.Valid {
				_m.Error = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PaymentEvent.
// This includes values selected through modifiers, order, etc.
func (_m *PaymentEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPaymentOrder queries the "payment_order" edge of the PaymentEvent entity.
func (_m *PaymentEvent) QueryPaymentOrder() *PaymentOrderQuery {
	return NewPaymentEventClient(_m.config).QueryPaymentOrder(_m)
}

// QueryProviderInstance queries the "provider_instance" edge of the PaymentEvent entity.
func (_m *PaymentEvent) QueryProviderInstance() *PaymentProviderInstanceQuery {
	return NewPaymentEventClient(_m.config).QueryProviderInstance(_m)
}

// Update returns a builder for updating this PaymentEvent.
// Note that you need to call PaymentEvent.Unwrap() before calling this method if this PaymentEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PaymentEvent) Update() *PaymentEventUpdateOne {
	return NewPaymentEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PaymentEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PaymentEvent) Unwrap() *PaymentEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PaymentEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PaymentEvent) String() string {
	var builder strings.Builder
	builder.WriteString("PaymentEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("event_key=")
	builder.WriteString(_m.EventKey)
	builder.WriteString(", ")
	if v := _m.PaymentOrderID; v != nil {
		builder.WriteString("payment_order_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ProviderInstanceID; v != nil {
		builder.WriteString("provider_instance_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("provider_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProviderType))
	builder.WriteString(", ")
	builder.WriteString("event_type=")
	builder.WriteString(_m.EventType)
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.Payload))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("error=")
	builder.WriteString(_m.Error)
	builder.WriteByte(')')
	return builder.String()
}

// PaymentEvents is a parsable slice of PaymentEvent.
type PaymentEvents []*PaymentEvent
