// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/upstreamaccountswitchhistory"
)

// UpstreamAccountSwitchHistoryDelete is the builder for deleting a UpstreamAccountSwitchHistory entity.
type UpstreamAccountSwitchHistoryDelete struct {
	config
	hooks    []Hook
	mutation *UpstreamAccountSwitchHistoryMutation
}

// Where appends a list predicates to the UpstreamAccountSwitchHistoryDelete builder.
func (_d *UpstreamAccountSwitchHistoryDelete) Where(ps ...predicate.UpstreamAccountSwitchHistory) *UpstreamAccountSwitchHistoryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UpstreamAccountSwitchHistoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UpstreamAccountSwitchHistoryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UpstreamAccountSwitchHistoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(upstreamaccountswitchhistory.Table, sqlgraph.NewFieldSpec(upstreamaccountswitchhistory.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UpstreamAccountSwitchHistoryDeleteOne is the builder for deleting a single UpstreamAccountSwitchHistory entity.
type UpstreamAccountSwitchHistoryDeleteOne struct {
	_d *UpstreamAccountSwitchHistoryDelete
}

// Where appends a list predicates to the UpstreamAccountSwitchHistoryDelete builder.
func (_d *UpstreamAccountSwitchHistoryDeleteOne) Where(ps ...predicate.UpstreamAccountSwitchHistory) *UpstreamAccountSwitchHistoryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UpstreamAccountSwitchHistoryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{upstreamaccountswitchhistory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UpstreamAccountSwitchHistoryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
