// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/billingaccount"
	"github.com/looplj/axonhub/internal/ent/ledgertransaction"
	"github.com/looplj/axonhub/internal/ent/usagebillingrecord"
	"github.com/looplj/axonhub/internal/ent/usagelog"
	"github.com/looplj/axonhub/internal/objects"
)

// UsageBillingRecord is the model entity for the UsageBillingRecord schema.
type UsageBillingRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UsageLogID holds the value of the "usage_log_id" field.
	UsageLogID int `json:"usage_log_id,omitempty"`
	// BillingAccountID holds the value of the "billing_account_id" field.
	BillingAccountID int `json:"billing_account_id,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID int `json:"project_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int `json:"api_key_id,omitempty"`
	// ModelID holds the value of the "model_id" field.
	ModelID string `json:"model_id,omitempty"`
	// RequestType holds the value of the "request_type" field.
	RequestType usagebillingrecord.RequestType `json:"request_type,omitempty"`
	// UsageSnapshot holds the value of the "usage_snapshot" field.
	UsageSnapshot objects.JSONRawMessage `json:"usage_snapshot,omitempty"`
	// PriceSnapshot holds the value of the "price_snapshot" field.
	PriceSnapshot objects.ModelPrice `json:"price_snapshot,omitempty"`
	// PriceReferenceID holds the value of the "price_reference_id" field.
	PriceReferenceID string `json:"price_reference_id,omitempty"`
	// ChargeItems holds the value of the "charge_items" field.
	ChargeItems []objects.CostItem `json:"charge_items,omitempty"`
	// CostAmountMicros holds the value of the "cost_amount_micros" field.
	CostAmountMicros int64 `json:"cost_amount_micros,omitempty"`
	// ChargeAmountMicros holds the value of the "charge_amount_micros" field.
	ChargeAmountMicros int64 `json:"charge_amount_micros,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// Status holds the value of the "status" field.
	Status usagebillingrecord.Status `json:"status,omitempty"`
	// LedgerTransactionID holds the value of the "ledger_transaction_id" field.
	LedgerTransactionID int `json:"ledger_transaction_id,omitempty"`
	// IdempotencyKey holds the value of the "idempotency_key" field.
	IdempotencyKey string `json:"idempotency_key,omitempty"`
	// Error holds the value of the "error" field.
	Error string `json:"error,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UsageBillingRecordQuery when eager-loading is set.
	Edges        UsageBillingRecordEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UsageBillingRecordEdges holds the relations/edges for other nodes in the graph.
type UsageBillingRecordEdges struct {
	// UsageLog holds the value of the usage_log edge.
	UsageLog *UsageLog `json:"usage_log,omitempty"`
	// BillingAccount holds the value of the billing_account edge.
	BillingAccount *BillingAccount `json:"billing_account,omitempty"`
	// LedgerTransaction holds the value of the ledger_transaction edge.
	LedgerTransaction *LedgerTransaction `json:"ledger_transaction,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
	// totalCount holds the count of the edges above.
	totalCount [3]map[string]int
}

// UsageLogOrErr returns the UsageLog value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UsageBillingRecordEdges) UsageLogOrErr() (*UsageLog, error) {
	if e.UsageLog != nil {
		return e.UsageLog, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: usagelog.Label}
	}
	return nil, &NotLoadedError{edge: "usage_log"}
}

// BillingAccountOrErr returns the BillingAccount value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UsageBillingRecordEdges) BillingAccountOrErr() (*BillingAccount, error) {
	if e.BillingAccount != nil {
		return e.BillingAccount, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: billingaccount.Label}
	}
	return nil, &NotLoadedError{edge: "billing_account"}
}

// LedgerTransactionOrErr returns the LedgerTransaction value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UsageBillingRecordEdges) LedgerTransactionOrErr() (*LedgerTransaction, error) {
	if e.LedgerTransaction != nil {
		return e.LedgerTransaction, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: ledgertransaction.Label}
	}
	return nil, &NotLoadedError{edge: "ledger_transaction"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UsageBillingRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usagebillingrecord.FieldUsageSnapshot, usagebillingrecord.FieldPriceSnapshot, usagebillingrecord.FieldChargeItems:
			values[i] = new([]byte)
		case usagebillingrecord.FieldID, usagebillingrecord.FieldUsageLogID, usagebillingrecord.FieldBillingAccountID, usagebillingrecord.FieldProjectID, usagebillingrecord.FieldUserID, usagebillingrecord.FieldAPIKeyID, usagebillingrecord.FieldCostAmountMicros, usagebillingrecord.FieldChargeAmountMicros, usagebillingrecord.FieldLedgerTransactionID:
			values[i] = new(sql.NullInt64)
		case usagebillingrecord.FieldModelID, usagebillingrecord.FieldRequestType, usagebillingrecord.FieldPriceReferenceID, usagebillingrecord.FieldCurrency, usagebillingrecord.FieldStatus, usagebillingrecord.FieldIdempotencyKey, usagebillingrecord.FieldError:
			values[i] = new(sql.NullString)
		case usagebillingrecord.FieldCreatedAt, usagebillingrecord.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UsageBillingRecord fields.
func (_m *UsageBillingRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usagebillingrecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case usagebillingrecord.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case usagebillingrecord.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case usagebillingrecord.FieldUsageLogID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field usage_log_id", values[i])
			} else if value.Valid {
				_m.UsageLogID = int(value.Int64)
			}
		case usagebillingrecord.FieldBillingAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field billing_account_id", values[i])
			} else if value.Valid {
				_m.BillingAccountID = int(value.Int64)
			}
		case usagebillingrecord.FieldProjectID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value.Valid {
				_m.ProjectID = int(value.Int64)
			}
		case usagebillingrecord.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case usagebillingrecord.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = int(value.Int64)
			}
		case usagebillingrecord.FieldModelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_id", values[i])
			} else if value.Valid {
				_m.ModelID = value.String
			}
		case usagebillingrecord.FieldRequestType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_type", values[i])
			} else if value.Valid {
				_m.RequestType = usagebillingrecord.RequestType(value.String)
			}
		case usagebillingrecord.FieldUsageSnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field usage_snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.UsageSnapshot); err != nil {
					return fmt.Errorf("unmarshal field usage_snapshot: %w", err)
				}
			}
		case usagebillingrecord.FieldPriceSnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field price_snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.PriceSnapshot); err != nil {
					return fmt.Errorf("unmarshal field price_snapshot: %w", err)
				}
			}
		case usagebillingrecord.FieldPriceReferenceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field price_reference_id", values[i])
			} else if value.Valid {
				_m.PriceReferenceID = value.String
			}
		case usagebillingrecord.FieldChargeItems:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field charge_items", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ChargeItems); err != nil {
					return fmt.Errorf("unmarshal field charge_items: %w", err)
				}
			}
		case usagebillingrecord.FieldCostAmountMicros:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cost_amount_micros", values[i])
			} else if value.Valid {
				_m.CostAmountMicros = value.Int64
			}
		case usagebillingrecord.FieldChargeAmountMicros:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field charge_amount_micros", values[i])
			} else if value.Valid {
				_m.ChargeAmountMicros = value.Int64
			}
		case usagebillingrecord.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case usagebillingrecord.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = usagebillingrecord.Status(value.String)
			}
		case usagebillingrecord.FieldLedgerTransactionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ledger_transaction_id", values[i])
			} else if value.Valid {
				_m.LedgerTransactionID = int(value.Int64)
			}
		case usagebillingrecord.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				_m.IdempotencyKey = value.String
			}
		case usagebillingrecord.FieldError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error", values[i])
			} else if value.Valid {
				_m.Error = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UsageBillingRecord.
// This includes values selected through modifiers, order, etc.
func (_m *UsageBillingRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUsageLog queries the "usage_log" edge of the UsageBillingRecord entity.
func (_m *UsageBillingRecord) QueryUsageLog() *UsageLogQuery {
	return NewUsageBillingRecordClient(_m.config).QueryUsageLog(_m)
}

// QueryBillingAccount queries the "billing_account" edge of the UsageBillingRecord entity.
func (_m *UsageBillingRecord) QueryBillingAccount() *BillingAccountQuery {
	return NewUsageBillingRecordClient(_m.config).QueryBillingAccount(_m)
}

// QueryLedgerTransaction queries the "ledger_transaction" edge of the UsageBillingRecord entity.
func (_m *UsageBillingRecord) QueryLedgerTransaction() *LedgerTransactionQuery {
	return NewUsageBillingRecordClient(_m.config).QueryLedgerTransaction(_m)
}

// Update returns a builder for updating this UsageBillingRecord.
// Note that you need to call UsageBillingRecord.Unwrap() before calling this method if this UsageBillingRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UsageBillingRecord) Update() *UsageBillingRecordUpdateOne {
	return NewUsageBillingRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UsageBillingRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UsageBillingRecord) Unwrap() *UsageBillingRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UsageBillingRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UsageBillingRecord) String() string {
	var builder strings.Builder
	builder.WriteString("UsageBillingRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("usage_log_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UsageLogID))
	builder.WriteString(", ")
	builder.WriteString("billing_account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.BillingAccountID))
	builder.WriteString(", ")
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("model_id=")
	builder.WriteString(_m.ModelID)
	builder.WriteString(", ")
	builder.WriteString("request_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestType))
	builder.WriteString(", ")
	builder.WriteString("usage_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.UsageSnapshot))
	builder.WriteString(", ")
	builder.WriteString("price_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.PriceSnapshot))
	builder.WriteString(", ")
	builder.WriteString("price_reference_id=")
	builder.WriteString(_m.PriceReferenceID)
	builder.WriteString(", ")
	builder.WriteString("charge_items=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChargeItems))
	builder.WriteString(", ")
	builder.WriteString("cost_amount_micros=")
	builder.WriteString(fmt.Sprintf("%v", _m.CostAmountMicros))
	builder.WriteString(", ")
	builder.WriteString("charge_amount_micros=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChargeAmountMicros))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("ledger_transaction_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.LedgerTransactionID))
	builder.WriteString(", ")
	builder.WriteString("idempotency_key=")
	builder.WriteString(_m.IdempotencyKey)
	builder.WriteString(", ")
	builder.WriteString("error=")
	builder.WriteString(_m.Error)
	builder.WriteByte(')')
	return builder.String()
}

// UsageBillingRecords is a parsable slice of UsageBillingRecord.
type UsageBillingRecords []*UsageBillingRecord
