// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/usagehourlyaggregate"
)

// UsageHourlyAggregateCreate is the builder for creating a UsageHourlyAggregate entity.
type UsageHourlyAggregateCreate struct {
	config
	mutation *UsageHourlyAggregateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UsageHourlyAggregateCreate) SetCreatedAt(v time.Time) *UsageHourlyAggregateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UsageHourlyAggregateCreate) SetNillableCreatedAt(v *time.Time) *UsageHourlyAggregateCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UsageHourlyAggregateCreate) SetUpdatedAt(v time.Time) *UsageHourlyAggregateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UsageHourlyAggregateCreate) SetNillableUpdatedAt(v *time.Time) *UsageHourlyAggregateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetBucketStart sets the "bucket_start" field.
func (_c *UsageHourlyAggregateCreate) SetBucketStart(v time.Time) *UsageHourlyAggregateCreate {
	_c.mutation.SetBucketStart(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UsageHourlyAggregateCreate) SetUserID(v int) *UsageHourlyAggregateCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *UsageHourlyAggregateCreate) SetNillableUserID(v *int) *UsageHourlyAggregateCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *UsageHourlyAggregateCreate) SetAPIKeyID(v int) *UsageHourlyAggregateCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_c *UsageHourlyAggregateCreate) SetNillableAPIKeyID(v *int) *UsageHourlyAggregateCreate {
	if v != nil {
		_c.SetAPIKeyID(*v)
	}
	return _c
}

// SetProjectID sets the "project_id" field.
func (_c *UsageHourlyAggregateCreate) SetProjectID(v int) *UsageHourlyAggregateCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_c *UsageHourlyAggregateCreate) SetNillableProjectID(v *int) *UsageHourlyAggregateCreate {
	if v != nil {
		_c.SetProjectID(*v)
	}
	return _c
}

// SetChannelID sets the "channel_id" field.
func (_c *UsageHourlyAggregateCreate) SetChannelID(v int) *UsageHourlyAggregateCreate {
	_c.mutation.SetChannelID(v)
	return _c
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_c *UsageHourlyAggregateCreate) SetNillableChannelID(v *int) *UsageHourlyAggregateCreate {
	if v != nil {
		_c.SetChannelID(*v)
	}
	return _c
}

// SetUpstreamAccountID sets the "upstream_account_id" field.
func (_c *UsageHourlyAggregateCreate) SetUpstreamAccountID(v int) *UsageHourlyAggregateCreate {
	_c.mutation.SetUpstreamAccountID(v)
	return _c
}

// SetNillableUpstreamAccountID sets the "upstream_account_id" field if the given value is not nil.
func (_c *UsageHourlyAggregateCreate) SetNillableUpstreamAccountID(v *int) *UsageHourlyAggregateCreate {
	if v != nil {
		_c.SetUpstreamAccountID(*v)
	}
	return _c
}

// SetModelID sets the "model_id" field.
func (_c *UsageHourlyAggregateCreate) SetModelID(v string) *UsageHourlyAggregateCreate {
	_c.mutation.SetModelID(v)
	return _c
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_c *UsageHourlyAggregateCreate) SetNillableModelID(v *string) *UsageHourlyAggregateCreate {
	if v != nil {
		_c.SetModelID(*v)
	}
	return _c
}

// SetRequestType sets the "request_type" field.
func (_c *UsageHourlyAggregateCreate) SetRequestType(v usagehourlyaggregate.RequestType) *UsageHourlyAggregateCreate {
	_c.mutation.SetRequestType(v)
	return _c
}

// SetNillableRequestType sets the "request_type" field if the given value is not nil.
func (_c *UsageHourlyAggregateCreate) SetNillableRequestType(v *usagehourlyaggregate.RequestType) *UsageHourlyAggregateCreate {
	if v != nil {
		_c.SetRequestType(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *UsageHourlyAggregateCreate) SetStatus(v usagehourlyaggregate.Status) *UsageHourlyAggregateCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *UsageHourlyAggregateCreate) SetNillableStatus(v *usagehourlyaggregate.Status) *UsageHourlyAggregateCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *UsageHourlyAggregateCreate) SetCurrency(v string) *UsageHourlyAggregateCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *UsageHourlyAggregateCreate) SetNillableCurrency(v *string) *UsageHourlyAggregateCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetRequestCount sets the "request_count" field.
func (_c *UsageHourlyAggregateCreate) SetRequestCount(v int64) *UsageHourlyAggregateCreate {
	_c.mutation.SetRequestCount(v)
	return _c
}

// SetNillableRequestCount sets the "request_count" field if the given value is not nil.
func (_c *UsageHourlyAggregateCreate) SetNillableRequestCount(v *int64) *UsageHourlyAggregateCreate {
	if v != nil {
		_c.SetRequestCount(*v)
	}
	return _c
}

// SetSuccessCount sets the "success_count" field.
func (_c *UsageHourlyAggregateCreate) SetSuccessCount(v int64) *UsageHourlyAggregateCreate {
	_c.mutation.SetSuccessCount(v)
	return _c
}

// SetNillableSuccessCount sets the "success_count" field if the given value is not nil.
func (_c *UsageHourlyAggregateCreate) SetNillableSuccessCount(v *int64) *UsageHourlyAggregateCreate {
	if v != nil {
		_c.SetSuccessCount(*v)
	}
	return _c
}

// SetErrorCount sets the "error_count" field.
func (_c *UsageHourlyAggregateCreate) SetErrorCount(v int64) *UsageHourlyAggregateCreate {
	_c.mutation.SetErrorCount(v)
	return _c
}

// SetNillableErrorCount sets the "error_count" field if the given value is not nil.
func (_c *UsageHourlyAggregateCreate) SetNillableErrorCount(v *int64) *UsageHourlyAggregateCreate {
	if v != nil {
		_c.SetErrorCount(*v)
	}
	return _c
}

// SetPromptTokens sets the "prompt_tokens" field.
func (_c *UsageHourlyAggregateCreate) SetPromptTokens(v int64) *UsageHourlyAggregateCreate {
	_c.mutation.SetPromptTokens(v)
	return _c
}

// SetNillablePromptTokens sets the "prompt_tokens" field if the given value is not nil.
func (_c *UsageHourlyAggregateCreate) SetNillablePromptTokens(v *int64) *UsageHourlyAggregateCreate {
	if v != nil {
		_c.SetPromptTokens(*v)
	}
	return _c
}

// SetCompletionTokens sets the "completion_tokens" field.
func (_c *UsageHourlyAggregateCreate) SetCompletionTokens(v int64) *UsageHourlyAggregateCreate {
	_c.mutation.SetCompletionTokens(v)
	return _c
}

// SetNillableCompletionTokens sets the "completion_tokens" field if the given value is not nil.
func (_c *UsageHourlyAggregateCreate) SetNillableCompletionTokens(v *int64) *UsageHourlyAggregateCreate {
	if v != nil {
		_c.SetCompletionTokens(*v)
	}
	return _c
}

// SetTotalTokens sets the "total_tokens" field.
func (_c *UsageHourlyAggregateCreate) SetTotalTokens(v int64) *UsageHourlyAggregateCreate {
	_c.mutation.SetTotalTokens(v)
	return _c
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_c *UsageHourlyAggregateCreate) SetNillableTotalTokens(v *int64) *UsageHourlyAggregateCreate {
	if v != nil {
		_c.SetTotalTokens(*v)
	}
	return _c
}

// SetUserChargeMicros sets the "user_charge_micros" field.
func (_c *UsageHourlyAggregateCreate) SetUserChargeMicros(v int64) *UsageHourlyAggregateCreate {
	_c.mutation.SetUserChargeMicros(v)
	return _c
}

// SetNillableUserChargeMicros sets the "user_charge_micros" field if the given value is not nil.
func (_c *UsageHourlyAggregateCreate) SetNillableUserChargeMicros(v *int64) *UsageHourlyAggregateCreate {
	if v != nil {
		_c.SetUserChargeMicros(*v)
	}
	return _c
}

// SetUpstreamCostMicros sets the "upstream_cost_micros" field.
func (_c *UsageHourlyAggregateCreate) SetUpstreamCostMicros(v int64) *UsageHourlyAggregateCreate {
	_c.mutation.SetUpstreamCostMicros(v)
	return _c
}

// SetNillableUpstreamCostMicros sets the "upstream_cost_micros" field if the given value is not nil.
func (_c *UsageHourlyAggregateCreate) SetNillableUpstreamCostMicros(v *int64) *UsageHourlyAggregateCreate {
	if v != nil {
		_c.SetUpstreamCostMicros(*v)
	}
	return _c
}

// SetGrossMarginMicros sets the "gross_margin_micros" field.
func (_c *UsageHourlyAggregateCreate) SetGrossMarginMicros(v int64) *UsageHourlyAggregateCreate {
	_c.mutation.SetGrossMarginMicros(v)
	return _c
}

// SetNillableGrossMarginMicros sets the "gross_margin_micros" field if the given value is not nil.
func (_c *UsageHourlyAggregateCreate) SetNillableGrossMarginMicros(v *int64) *UsageHourlyAggregateCreate {
	if v != nil {
		_c.SetGrossMarginMicros(*v)
	}
	return _c
}

// Mutation returns the UsageHourlyAggregateMutation object of the builder.
func (_c *UsageHourlyAggregateCreate) Mutation() *UsageHourlyAggregateMutation {
	return _c.mutation
}

// Save creates the UsageHourlyAggregate in the database.
func (_c *UsageHourlyAggregateCreate) Save(ctx context.Context) (*UsageHourlyAggregate, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UsageHourlyAggregateCreate) SaveX(ctx context.Context) *UsageHourlyAggregate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UsageHourlyAggregateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UsageHourlyAggregateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UsageHourlyAggregateCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if usagehourlyaggregate.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized usagehourlyaggregate.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := usagehourlyaggregate.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if usagehourlyaggregate.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized usagehourlyaggregate.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := usagehourlyaggregate.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.UserID(); !ok {
		v := usagehourlyaggregate.DefaultUserID
		_c.mutation.SetUserID(v)
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		v := usagehourlyaggregate.DefaultAPIKeyID
		_c.mutation.SetAPIKeyID(v)
	}
	if _, ok := _c.mutation.ProjectID(); !ok {
		v := usagehourlyaggregate.DefaultProjectID
		_c.mutation.SetProjectID(v)
	}
	if _, ok := _c.mutation.ChannelID(); !ok {
		v := usagehourlyaggregate.DefaultChannelID
		_c.mutation.SetChannelID(v)
	}
	if _, ok := _c.mutation.UpstreamAccountID(); !ok {
		v := usagehourlyaggregate.DefaultUpstreamAccountID
		_c.mutation.SetUpstreamAccountID(v)
	}
	if _, ok := _c.mutation.ModelID(); !ok {
		v := usagehourlyaggregate.DefaultModelID
		_c.mutation.SetModelID(v)
	}
	if _, ok := _c.mutation.RequestType(); !ok {
		v := usagehourlyaggregate.DefaultRequestType
		_c.mutation.SetRequestType(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := usagehourlyaggregate.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := usagehourlyaggregate.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.RequestCount(); !ok {
		v := usagehourlyaggregate.DefaultRequestCount
		_c.mutation.SetRequestCount(v)
	}
	if _, ok := _c.mutation.SuccessCount(); !ok {
		v := usagehourlyaggregate.DefaultSuccessCount
		_c.mutation.SetSuccessCount(v)
	}
	if _, ok := _c.mutation.ErrorCount(); !ok {
		v := usagehourlyaggregate.DefaultErrorCount
		_c.mutation.SetErrorCount(v)
	}
	if _, ok := _c.mutation.PromptTokens(); !ok {
		v := usagehourlyaggregate.DefaultPromptTokens
		_c.mutation.SetPromptTokens(v)
	}
	if _, ok := _c.mutation.CompletionTokens(); !ok {
		v := usagehourlyaggregate.DefaultCompletionTokens
		_c.mutation.SetCompletionTokens(v)
	}
	if _, ok := _c.mutation.TotalTokens(); !ok {
		v := usagehourlyaggregate.DefaultTotalTokens
		_c.mutation.SetTotalTokens(v)
	}
	if _, ok := _c.mutation.UserChargeMicros(); !ok {
		v := usagehourlyaggregate.DefaultUserChargeMicros
		_c.mutation.SetUserChargeMicros(v)
	}
	if _, ok := _c.mutation.UpstreamCostMicros(); !ok {
		v := usagehourlyaggregate.DefaultUpstreamCostMicros
		_c.mutation.SetUpstreamCostMicros(v)
	}
	if _, ok := _c.mutation.GrossMarginMicros(); !ok {
		v := usagehourlyaggregate.DefaultGrossMarginMicros
		_c.mutation.SetGrossMarginMicros(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *UsageHourlyAggregateCreate) check() error {
	if _, ok := _c.mutation.BucketStart(); !ok {
		return &ValidationError{Name: "bucket_start", err: errors.New(`ent: missing required field "UsageHourlyAggregate.bucket_start"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UsageHourlyAggregate.user_id"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "UsageHourlyAggregate.api_key_id"`)}
	}
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "UsageHourlyAggregate.project_id"`)}
	}
	if _, ok := _c.mutation.ChannelID(); !ok {
		return &ValidationError{Name: "channel_id", err: errors.New(`ent: missing required field "UsageHourlyAggregate.channel_id"`)}
	}
	if _, ok := _c.mutation.UpstreamAccountID(); !ok {
		return &ValidationError{Name: "upstream_account_id", err: errors.New(`ent: missing required field "UsageHourlyAggregate.upstream_account_id"`)}
	}
	if _, ok := _c.mutation.ModelID(); !ok {
		return &ValidationError{Name: "model_id", err: errors.New(`ent: missing required field "UsageHourlyAggregate.model_id"`)}
	}
	if _, ok := _c.mutation.RequestType(); !ok {
		return &ValidationError{Name: "request_type", err: errors.New(`ent: missing required field "UsageHourlyAggregate.request_type"`)}
	}
	if v, ok := _c.mutation.RequestType(); ok {
		if err := usagehourlyaggregate.RequestTypeValidator(v); err != nil {
			return &ValidationError{Name: "request_type", err: fmt.Errorf(`ent: validator failed for field "UsageHourlyAggregate.request_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "UsageHourlyAggregate.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := usagehourlyaggregate.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UsageHourlyAggregate.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "UsageHourlyAggregate.currency"`)}
	}
	if _, ok := _c.mutation.RequestCount(); !ok {
		return &ValidationError{Name: "request_count", err: errors.New(`ent: missing required field "UsageHourlyAggregate.request_count"`)}
	}
	if _, ok := _c.mutation.SuccessCount(); !ok {
		return &ValidationError{Name: "success_count", err: errors.New(`ent: missing required field "UsageHourlyAggregate.success_count"`)}
	}
	if _, ok := _c.mutation.ErrorCount(); !ok {
		return &ValidationError{Name: "error_count", err: errors.New(`ent: missing required field "UsageHourlyAggregate.error_count"`)}
	}
	if _, ok := _c.mutation.PromptTokens(); !ok {
		return &ValidationError{Name: "prompt_tokens", err: errors.New(`ent: missing required field "UsageHourlyAggregate.prompt_tokens"`)}
	}
	if _, ok := _c.mutation.CompletionTokens(); !ok {
		return &ValidationError{Name: "completion_tokens", err: errors.New(`ent: missing required field "UsageHourlyAggregate.completion_tokens"`)}
	}
	if _, ok := _c.mutation.TotalTokens(); !ok {
		return &ValidationError{Name: "total_tokens", err: errors.New(`ent: missing required field "UsageHourlyAggregate.total_tokens"`)}
	}
	if _, ok := _c.mutation.UserChargeMicros(); !ok {
		return &ValidationError{Name: "user_charge_micros", err: errors.New(`ent: missing required field "UsageHourlyAggregate.user_charge_micros"`)}
	}
	if _, ok := _c.mutation.UpstreamCostMicros(); !ok {
		return &ValidationError{Name: "upstream_cost_micros", err: errors.New(`ent: missing required field "UsageHourlyAggregate.upstream_cost_micros"`)}
	}
	if _, ok := _c.mutation.GrossMarginMicros(); !ok {
		return &ValidationError{Name: "gross_margin_micros", err: errors.New(`ent: missing required field "UsageHourlyAggregate.gross_margin_micros"`)}
	}
	return nil
}

func (_c *UsageHourlyAggregateCreate) sqlSave(ctx context.Context) (*UsageHourlyAggregate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UsageHourlyAggregateCreate) createSpec() (*UsageHourlyAggregate, *sqlgraph.CreateSpec) {
	var (
		_node = &UsageHourlyAggregate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usagehourlyaggregate.Table, sqlgraph.NewFieldSpec(usagehourlyaggregate.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usagehourlyaggregate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(usagehourlyaggregate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.BucketStart(); ok {
		_spec.SetField(usagehourlyaggregate.FieldBucketStart, field.TypeTime, value)
		_node.BucketStart = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(usagehourlyaggregate.FieldUserID, field.TypeInt, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(usagehourlyaggregate.FieldAPIKeyID, field.TypeInt, value)
		_node.APIKeyID = value
	}
	if value, ok := _c.mutation.ProjectID(); ok {
		_spec.SetField(usagehourlyaggregate.FieldProjectID, field.TypeInt, value)
		_node.ProjectID = value
	}
	if value, ok := _c.mutation.ChannelID(); ok {
		_spec.SetField(usagehourlyaggregate.FieldChannelID, field.TypeInt, value)
		_node.ChannelID = value
	}
	if value, ok := _c.mutation.UpstreamAccountID(); ok {
		_spec.SetField(usagehourlyaggregate.FieldUpstreamAccountID, field.TypeInt, value)
		_node.UpstreamAccountID = value
	}
	if value, ok := _c.mutation.ModelID(); ok {
		_spec.SetField(usagehourlyaggregate.FieldModelID, field.TypeString, value)
		_node.ModelID = value
	}
	if value, ok := _c.mutation.RequestType(); ok {
		_spec.SetField(usagehourlyaggregate.FieldRequestType, field.TypeEnum, value)
		_node.RequestType = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(usagehourlyaggregate.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(usagehourlyaggregate.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.RequestCount(); ok {
		_spec.SetField(usagehourlyaggregate.FieldRequestCount, field.TypeInt64, value)
		_node.RequestCount = value
	}
	if value, ok := _c.mutation.SuccessCount(); ok {
		_spec.SetField(usagehourlyaggregate.FieldSuccessCount, field.TypeInt64, value)
		_node.SuccessCount = value
	}
	if value, ok := _c.mutation.ErrorCount(); ok {
		_spec.SetField(usagehourlyaggregate.FieldErrorCount, field.TypeInt64, value)
		_node.ErrorCount = value
	}
	if value, ok := _c.mutation.PromptTokens(); ok {
		_spec.SetField(usagehourlyaggregate.FieldPromptTokens, field.TypeInt64, value)
		_node.PromptTokens = value
	}
	if value, ok := _c.mutation.CompletionTokens(); ok {
		_spec.SetField(usagehourlyaggregate.FieldCompletionTokens, field.TypeInt64, value)
		_node.CompletionTokens = value
	}
	if value, ok := _c.mutation.TotalTokens(); ok {
		_spec.SetField(usagehourlyaggregate.FieldTotalTokens, field.TypeInt64, value)
		_node.TotalTokens = value
	}
	if value, ok := _c.mutation.UserChargeMicros(); ok {
		_spec.SetField(usagehourlyaggregate.FieldUserChargeMicros, field.TypeInt64, value)
		_node.UserChargeMicros = value
	}
	if value, ok := _c.mutation.UpstreamCostMicros(); ok {
		_spec.SetField(usagehourlyaggregate.FieldUpstreamCostMicros, field.TypeInt64, value)
		_node.UpstreamCostMicros = value
	}
	if value, ok := _c.mutation.GrossMarginMicros(); ok {
		_spec.SetField(usagehourlyaggregate.FieldGrossMarginMicros, field.TypeInt64, value)
		_node.GrossMarginMicros = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UsageHourlyAggregate.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UsageHourlyAggregateUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UsageHourlyAggregateCreate) OnConflict(opts ...sql.ConflictOption) *UsageHourlyAggregateUpsertOne {
	_c.conflict = opts
	return &UsageHourlyAggregateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UsageHourlyAggregate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UsageHourlyAggregateCreate) OnConflictColumns(columns ...string) *UsageHourlyAggregateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UsageHourlyAggregateUpsertOne{
		create: _c,
	}
}

type (
	// UsageHourlyAggregateUpsertOne is the builder for "upsert"-ing
	//  one UsageHourlyAggregate node.
	UsageHourlyAggregateUpsertOne struct {
		create *UsageHourlyAggregateCreate
	}

	// UsageHourlyAggregateUpsert is the "OnConflict" setter.
	UsageHourlyAggregateUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UsageHourlyAggregateUpsert) SetUpdatedAt(v time.Time) *UsageHourlyAggregateUpsert {
	u.Set(usagehourlyaggregate.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsert) UpdateUpdatedAt() *UsageHourlyAggregateUpsert {
	u.SetExcluded(usagehourlyaggregate.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *UsageHourlyAggregateUpsert) SetUserID(v int) *UsageHourlyAggregateUpsert {
	u.Set(usagehourlyaggregate.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsert) UpdateUserID() *UsageHourlyAggregateUpsert {
	u.SetExcluded(usagehourlyaggregate.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *UsageHourlyAggregateUpsert) AddUserID(v int) *UsageHourlyAggregateUpsert {
	u.Add(usagehourlyaggregate.FieldUserID, v)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *UsageHourlyAggregateUpsert) SetAPIKeyID(v int) *UsageHourlyAggregateUpsert {
	u.Set(usagehourlyaggregate.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsert) UpdateAPIKeyID() *UsageHourlyAggregateUpsert {
	u.SetExcluded(usagehourlyaggregate.FieldAPIKeyID)
	return u
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *UsageHourlyAggregateUpsert) AddAPIKeyID(v int) *UsageHourlyAggregateUpsert {
	u.Add(usagehourlyaggregate.FieldAPIKeyID, v)
	return u
}

// SetProjectID sets the "project_id" field.
func (u *UsageHourlyAggregateUpsert) SetProjectID(v int) *UsageHourlyAggregateUpsert {
	u.Set(usagehourlyaggregate.FieldProjectID, v)
	return u
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsert) UpdateProjectID() *UsageHourlyAggregateUpsert {
	u.SetExcluded(usagehourlyaggregate.FieldProjectID)
	return u
}

// AddProjectID adds v to the "project_id" field.
func (u *UsageHourlyAggregateUpsert) AddProjectID(v int) *UsageHourlyAggregateUpsert {
	u.Add(usagehourlyaggregate.FieldProjectID, v)
	return u
}

// SetChannelID sets the "channel_id" field.
func (u *UsageHourlyAggregateUpsert) SetChannelID(v int) *UsageHourlyAggregateUpsert {
	u.Set(usagehourlyaggregate.FieldChannelID, v)
	return u
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsert) UpdateChannelID() *UsageHourlyAggregateUpsert {
	u.SetExcluded(usagehourlyaggregate.FieldChannelID)
	return u
}

// AddChannelID adds v to the "channel_id" field.
func (u *UsageHourlyAggregateUpsert) AddChannelID(v int) *UsageHourlyAggregateUpsert {
	u.Add(usagehourlyaggregate.FieldChannelID, v)
	return u
}

// SetUpstreamAccountID sets the "upstream_account_id" field.
func (u *UsageHourlyAggregateUpsert) SetUpstreamAccountID(v int) *UsageHourlyAggregateUpsert {
	u.Set(usagehourlyaggregate.FieldUpstreamAccountID, v)
	return u
}

// UpdateUpstreamAccountID sets the "upstream_account_id" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsert) UpdateUpstreamAccountID() *UsageHourlyAggregateUpsert {
	u.SetExcluded(usagehourlyaggregate.FieldUpstreamAccountID)
	return u
}

// AddUpstreamAccountID adds v to the "upstream_account_id" field.
func (u *UsageHourlyAggregateUpsert) AddUpstreamAccountID(v int) *UsageHourlyAggregateUpsert {
	u.Add(usagehourlyaggregate.FieldUpstreamAccountID, v)
	return u
}

// SetModelID sets the "model_id" field.
func (u *UsageHourlyAggregateUpsert) SetModelID(v string) *UsageHourlyAggregateUpsert {
	u.Set(usagehourlyaggregate.FieldModelID, v)
	return u
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsert) UpdateModelID() *UsageHourlyAggregateUpsert {
	u.SetExcluded(usagehourlyaggregate.FieldModelID)
	return u
}

// SetRequestType sets the "request_type" field.
func (u *UsageHourlyAggregateUpsert) SetRequestType(v usagehourlyaggregate.RequestType) *UsageHourlyAggregateUpsert {
	u.Set(usagehourlyaggregate.FieldRequestType, v)
	return u
}

// UpdateRequestType sets the "request_type" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsert) UpdateRequestType() *UsageHourlyAggregateUpsert {
	u.SetExcluded(usagehourlyaggregate.FieldRequestType)
	return u
}

// SetStatus sets the "status" field.
func (u *UsageHourlyAggregateUpsert) SetStatus(v usagehourlyaggregate.Status) *UsageHourlyAggregateUpsert {
	u.Set(usagehourlyaggregate.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsert) UpdateStatus() *UsageHourlyAggregateUpsert {
	u.SetExcluded(usagehourlyaggregate.FieldStatus)
	return u
}

// SetCurrency sets the "currency" field.
func (u *UsageHourlyAggregateUpsert) SetCurrency(v string) *UsageHourlyAggregateUpsert {
	u.Set(usagehourlyaggregate.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsert) UpdateCurrency() *UsageHourlyAggregateUpsert {
	u.SetExcluded(usagehourlyaggregate.FieldCurrency)
	return u
}

// SetRequestCount sets the "request_count" field.
func (u *UsageHourlyAggregateUpsert) SetRequestCount(v int64) *UsageHourlyAggregateUpsert {
	u.Set(usagehourlyaggregate.FieldRequestCount, v)
	return u
}

// UpdateRequestCount sets the "request_count" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsert) UpdateRequestCount() *UsageHourlyAggregateUpsert {
	u.SetExcluded(usagehourlyaggregate.FieldRequestCount)
	return u
}

// AddRequestCount adds v to the "request_count" field.
func (u *UsageHourlyAggregateUpsert) AddRequestCount(v int64) *UsageHourlyAggregateUpsert {
	u.Add(usagehourlyaggregate.FieldRequestCount, v)
	return u
}

// SetSuccessCount sets the "success_count" field.
func (u *UsageHourlyAggregateUpsert) SetSuccessCount(v int64) *UsageHourlyAggregateUpsert {
	u.Set(usagehourlyaggregate.FieldSuccessCount, v)
	return u
}

// UpdateSuccessCount sets the "success_count" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsert) UpdateSuccessCount() *UsageHourlyAggregateUpsert {
	u.SetExcluded(usagehourlyaggregate.FieldSuccessCount)
	return u
}

// AddSuccessCount adds v to the "success_count" field.
func (u *UsageHourlyAggregateUpsert) AddSuccessCount(v int64) *UsageHourlyAggregateUpsert {
	u.Add(usagehourlyaggregate.FieldSuccessCount, v)
	return u
}

// SetErrorCount sets the "error_count" field.
func (u *UsageHourlyAggregateUpsert) SetErrorCount(v int64) *UsageHourlyAggregateUpsert {
	u.Set(usagehourlyaggregate.FieldErrorCount, v)
	return u
}

// UpdateErrorCount sets the "error_count" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsert) UpdateErrorCount() *UsageHourlyAggregateUpsert {
	u.SetExcluded(usagehourlyaggregate.FieldErrorCount)
	return u
}

// AddErrorCount adds v to the "error_count" field.
func (u *UsageHourlyAggregateUpsert) AddErrorCount(v int64) *UsageHourlyAggregateUpsert {
	u.Add(usagehourlyaggregate.FieldErrorCount, v)
	return u
}

// SetPromptTokens sets the "prompt_tokens" field.
func (u *UsageHourlyAggregateUpsert) SetPromptTokens(v int64) *UsageHourlyAggregateUpsert {
	u.Set(usagehourlyaggregate.FieldPromptTokens, v)
	return u
}

// UpdatePromptTokens sets the "prompt_tokens" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsert) UpdatePromptTokens() *UsageHourlyAggregateUpsert {
	u.SetExcluded(usagehourlyaggregate.FieldPromptTokens)
	return u
}

// AddPromptTokens adds v to the "prompt_tokens" field.
func (u *UsageHourlyAggregateUpsert) AddPromptTokens(v int64) *UsageHourlyAggregateUpsert {
	u.Add(usagehourlyaggregate.FieldPromptTokens, v)
	return u
}

// SetCompletionTokens sets the "completion_tokens" field.
func (u *UsageHourlyAggregateUpsert) SetCompletionTokens(v int64) *UsageHourlyAggregateUpsert {
	u.Set(usagehourlyaggregate.FieldCompletionTokens, v)
	return u
}

// UpdateCompletionTokens sets the "completion_tokens" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsert) UpdateCompletionTokens() *UsageHourlyAggregateUpsert {
	u.SetExcluded(usagehourlyaggregate.FieldCompletionTokens)
	return u
}

// AddCompletionTokens adds v to the "completion_tokens" field.
func (u *UsageHourlyAggregateUpsert) AddCompletionTokens(v int64) *UsageHourlyAggregateUpsert {
	u.Add(usagehourlyaggregate.FieldCompletionTokens, v)
	return u
}

// SetTotalTokens sets the "total_tokens" field.
func (u *UsageHourlyAggregateUpsert) SetTotalTokens(v int64) *UsageHourlyAggregateUpsert {
	u.Set(usagehourlyaggregate.FieldTotalTokens, v)
	return u
}

// UpdateTotalTokens sets the "total_tokens" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsert) UpdateTotalTokens() *UsageHourlyAggregateUpsert {
	u.SetExcluded(usagehourlyaggregate.FieldTotalTokens)
	return u
}

// AddTotalTokens adds v to the "total_tokens" field.
func (u *UsageHourlyAggregateUpsert) AddTotalTokens(v int64) *UsageHourlyAggregateUpsert {
	u.Add(usagehourlyaggregate.FieldTotalTokens, v)
	return u
}

// SetUserChargeMicros sets the "user_charge_micros" field.
func (u *UsageHourlyAggregateUpsert) SetUserChargeMicros(v int64) *UsageHourlyAggregateUpsert {
	u.Set(usagehourlyaggregate.FieldUserChargeMicros, v)
	return u
}

// UpdateUserChargeMicros sets the "user_charge_micros" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsert) UpdateUserChargeMicros() *UsageHourlyAggregateUpsert {
	u.SetExcluded(usagehourlyaggregate.FieldUserChargeMicros)
	return u
}

// AddUserChargeMicros adds v to the "user_charge_micros" field.
func (u *UsageHourlyAggregateUpsert) AddUserChargeMicros(v int64) *UsageHourlyAggregateUpsert {
	u.Add(usagehourlyaggregate.FieldUserChargeMicros, v)
	return u
}

// SetUpstreamCostMicros sets the "upstream_cost_micros" field.
func (u *UsageHourlyAggregateUpsert) SetUpstreamCostMicros(v int64) *UsageHourlyAggregateUpsert {
	u.Set(usagehourlyaggregate.FieldUpstreamCostMicros, v)
	return u
}

// UpdateUpstreamCostMicros sets the "upstream_cost_micros" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsert) UpdateUpstreamCostMicros() *UsageHourlyAggregateUpsert {
	u.SetExcluded(usagehourlyaggregate.FieldUpstreamCostMicros)
	return u
}

// AddUpstreamCostMicros adds v to the "upstream_cost_micros" field.
func (u *UsageHourlyAggregateUpsert) AddUpstreamCostMicros(v int64) *UsageHourlyAggregateUpsert {
	u.Add(usagehourlyaggregate.FieldUpstreamCostMicros, v)
	return u
}

// SetGrossMarginMicros sets the "gross_margin_micros" field.
func (u *UsageHourlyAggregateUpsert) SetGrossMarginMicros(v int64) *UsageHourlyAggregateUpsert {
	u.Set(usagehourlyaggregate.FieldGrossMarginMicros, v)
	return u
}

// UpdateGrossMarginMicros sets the "gross_margin_micros" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsert) UpdateGrossMarginMicros() *UsageHourlyAggregateUpsert {
	u.SetExcluded(usagehourlyaggregate.FieldGrossMarginMicros)
	return u
}

// AddGrossMarginMicros adds v to the "gross_margin_micros" field.
func (u *UsageHourlyAggregateUpsert) AddGrossMarginMicros(v int64) *UsageHourlyAggregateUpsert {
	u.Add(usagehourlyaggregate.FieldGrossMarginMicros, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UsageHourlyAggregate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UsageHourlyAggregateUpsertOne) UpdateNewValues() *UsageHourlyAggregateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(usagehourlyaggregate.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.BucketStart(); exists {
			s.SetIgnore(usagehourlyaggregate.FieldBucketStart)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UsageHourlyAggregate.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UsageHourlyAggregateUpsertOne) Ignore() *UsageHourlyAggregateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UsageHourlyAggregateUpsertOne) DoNothing() *UsageHourlyAggregateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UsageHourlyAggregateCreate.OnConflict
// documentation for more info.
func (u *UsageHourlyAggregateUpsertOne) Update(set func(*UsageHourlyAggregateUpsert)) *UsageHourlyAggregateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UsageHourlyAggregateUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UsageHourlyAggregateUpsertOne) SetUpdatedAt(v time.Time) *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertOne) UpdateUpdatedAt() *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UsageHourlyAggregateUpsertOne) SetUserID(v int) *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *UsageHourlyAggregateUpsertOne) AddUserID(v int) *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertOne) UpdateUserID() *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *UsageHourlyAggregateUpsertOne) SetAPIKeyID(v int) *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *UsageHourlyAggregateUpsertOne) AddAPIKeyID(v int) *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertOne) UpdateAPIKeyID() *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetProjectID sets the "project_id" field.
func (u *UsageHourlyAggregateUpsertOne) SetProjectID(v int) *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetProjectID(v)
	})
}

// AddProjectID adds v to the "project_id" field.
func (u *UsageHourlyAggregateUpsertOne) AddProjectID(v int) *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.AddProjectID(v)
	})
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertOne) UpdateProjectID() *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdateProjectID()
	})
}

// SetChannelID sets the "channel_id" field.
func (u *UsageHourlyAggregateUpsertOne) SetChannelID(v int) *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetChannelID(v)
	})
}

// AddChannelID adds v to the "channel_id" field.
func (u *UsageHourlyAggregateUpsertOne) AddChannelID(v int) *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.AddChannelID(v)
	})
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertOne) UpdateChannelID() *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdateChannelID()
	})
}

// SetUpstreamAccountID sets the "upstream_account_id" field.
func (u *UsageHourlyAggregateUpsertOne) SetUpstreamAccountID(v int) *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetUpstreamAccountID(v)
	})
}

// AddUpstreamAccountID adds v to the "upstream_account_id" field.
func (u *UsageHourlyAggregateUpsertOne) AddUpstreamAccountID(v int) *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.AddUpstreamAccountID(v)
	})
}

// UpdateUpstreamAccountID sets the "upstream_account_id" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertOne) UpdateUpstreamAccountID() *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdateUpstreamAccountID()
	})
}

// SetModelID sets the "model_id" field.
func (u *UsageHourlyAggregateUpsertOne) SetModelID(v string) *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetModelID(v)
	})
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertOne) UpdateModelID() *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdateModelID()
	})
}

// SetRequestType sets the "request_type" field.
func (u *UsageHourlyAggregateUpsertOne) SetRequestType(v usagehourlyaggregate.RequestType) *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetRequestType(v)
	})
}

// UpdateRequestType sets the "request_type" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertOne) UpdateRequestType() *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdateRequestType()
	})
}

// SetStatus sets the "status" field.
func (u *UsageHourlyAggregateUpsertOne) SetStatus(v usagehourlyaggregate.Status) *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertOne) UpdateStatus() *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdateStatus()
	})
}

// SetCurrency sets the "currency" field.
func (u *UsageHourlyAggregateUpsertOne) SetCurrency(v string) *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertOne) UpdateCurrency() *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdateCurrency()
	})
}

// SetRequestCount sets the "request_count" field.
func (u *UsageHourlyAggregateUpsertOne) SetRequestCount(v int64) *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetRequestCount(v)
	})
}

// AddRequestCount adds v to the "request_count" field.
func (u *UsageHourlyAggregateUpsertOne) AddRequestCount(v int64) *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.AddRequestCount(v)
	})
}

// UpdateRequestCount sets the "request_count" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertOne) UpdateRequestCount() *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdateRequestCount()
	})
}

// SetSuccessCount sets the "success_count" field.
func (u *UsageHourlyAggregateUpsertOne) SetSuccessCount(v int64) *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetSuccessCount(v)
	})
}

// AddSuccessCount adds v to the "success_count" field.
func (u *UsageHourlyAggregateUpsertOne) AddSuccessCount(v int64) *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.AddSuccessCount(v)
	})
}

// UpdateSuccessCount sets the "success_count" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertOne) UpdateSuccessCount() *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdateSuccessCount()
	})
}

// SetErrorCount sets the "error_count" field.
func (u *UsageHourlyAggregateUpsertOne) SetErrorCount(v int64) *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetErrorCount(v)
	})
}

// AddErrorCount adds v to the "error_count" field.
func (u *UsageHourlyAggregateUpsertOne) AddErrorCount(v int64) *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.AddErrorCount(v)
	})
}

// UpdateErrorCount sets the "error_count" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertOne) UpdateErrorCount() *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdateErrorCount()
	})
}

// SetPromptTokens sets the "prompt_tokens" field.
func (u *UsageHourlyAggregateUpsertOne) SetPromptTokens(v int64) *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetPromptTokens(v)
	})
}

// AddPromptTokens adds v to the "prompt_tokens" field.
func (u *UsageHourlyAggregateUpsertOne) AddPromptTokens(v int64) *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.AddPromptTokens(v)
	})
}

// UpdatePromptTokens sets the "prompt_tokens" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertOne) UpdatePromptTokens() *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdatePromptTokens()
	})
}

// SetCompletionTokens sets the "completion_tokens" field.
func (u *UsageHourlyAggregateUpsertOne) SetCompletionTokens(v int64) *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetCompletionTokens(v)
	})
}

// AddCompletionTokens adds v to the "completion_tokens" field.
func (u *UsageHourlyAggregateUpsertOne) AddCompletionTokens(v int64) *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.AddCompletionTokens(v)
	})
}

// UpdateCompletionTokens sets the "completion_tokens" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertOne) UpdateCompletionTokens() *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdateCompletionTokens()
	})
}

// SetTotalTokens sets the "total_tokens" field.
func (u *UsageHourlyAggregateUpsertOne) SetTotalTokens(v int64) *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetTotalTokens(v)
	})
}

// AddTotalTokens adds v to the "total_tokens" field.
func (u *UsageHourlyAggregateUpsertOne) AddTotalTokens(v int64) *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.AddTotalTokens(v)
	})
}

// UpdateTotalTokens sets the "total_tokens" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertOne) UpdateTotalTokens() *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdateTotalTokens()
	})
}

// SetUserChargeMicros sets the "user_charge_micros" field.
func (u *UsageHourlyAggregateUpsertOne) SetUserChargeMicros(v int64) *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetUserChargeMicros(v)
	})
}

// AddUserChargeMicros adds v to the "user_charge_micros" field.
func (u *UsageHourlyAggregateUpsertOne) AddUserChargeMicros(v int64) *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.AddUserChargeMicros(v)
	})
}

// UpdateUserChargeMicros sets the "user_charge_micros" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertOne) UpdateUserChargeMicros() *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdateUserChargeMicros()
	})
}

// SetUpstreamCostMicros sets the "upstream_cost_micros" field.
func (u *UsageHourlyAggregateUpsertOne) SetUpstreamCostMicros(v int64) *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetUpstreamCostMicros(v)
	})
}

// AddUpstreamCostMicros adds v to the "upstream_cost_micros" field.
func (u *UsageHourlyAggregateUpsertOne) AddUpstreamCostMicros(v int64) *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.AddUpstreamCostMicros(v)
	})
}

// UpdateUpstreamCostMicros sets the "upstream_cost_micros" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertOne) UpdateUpstreamCostMicros() *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdateUpstreamCostMicros()
	})
}

// SetGrossMarginMicros sets the "gross_margin_micros" field.
func (u *UsageHourlyAggregateUpsertOne) SetGrossMarginMicros(v int64) *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetGrossMarginMicros(v)
	})
}

// AddGrossMarginMicros adds v to the "gross_margin_micros" field.
func (u *UsageHourlyAggregateUpsertOne) AddGrossMarginMicros(v int64) *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.AddGrossMarginMicros(v)
	})
}

// UpdateGrossMarginMicros sets the "gross_margin_micros" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertOne) UpdateGrossMarginMicros() *UsageHourlyAggregateUpsertOne {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdateGrossMarginMicros()
	})
}

// Exec executes the query.
func (u *UsageHourlyAggregateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UsageHourlyAggregateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UsageHourlyAggregateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UsageHourlyAggregateUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UsageHourlyAggregateUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UsageHourlyAggregateCreateBulk is the builder for creating many UsageHourlyAggregate entities in bulk.
type UsageHourlyAggregateCreateBulk struct {
	config
	err      error
	builders []*UsageHourlyAggregateCreate
	conflict []sql.ConflictOption
}

// Save creates the UsageHourlyAggregate entities in the database.
func (_c *UsageHourlyAggregateCreateBulk) Save(ctx context.Context) ([]*UsageHourlyAggregate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UsageHourlyAggregate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UsageHourlyAggregateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UsageHourlyAggregateCreateBulk) SaveX(ctx context.Context) []*UsageHourlyAggregate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UsageHourlyAggregateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UsageHourlyAggregateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UsageHourlyAggregate.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UsageHourlyAggregateUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UsageHourlyAggregateCreateBulk) OnConflict(opts ...sql.ConflictOption) *UsageHourlyAggregateUpsertBulk {
	_c.conflict = opts
	return &UsageHourlyAggregateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UsageHourlyAggregate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UsageHourlyAggregateCreateBulk) OnConflictColumns(columns ...string) *UsageHourlyAggregateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UsageHourlyAggregateUpsertBulk{
		create: _c,
	}
}

// UsageHourlyAggregateUpsertBulk is the builder for "upsert"-ing
// a bulk of UsageHourlyAggregate nodes.
type UsageHourlyAggregateUpsertBulk struct {
	create *UsageHourlyAggregateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UsageHourlyAggregate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UsageHourlyAggregateUpsertBulk) UpdateNewValues() *UsageHourlyAggregateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(usagehourlyaggregate.FieldCreatedAt)
			}
			if _, exists := b.mutation.BucketStart(); exists {
				s.SetIgnore(usagehourlyaggregate.FieldBucketStart)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UsageHourlyAggregate.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UsageHourlyAggregateUpsertBulk) Ignore() *UsageHourlyAggregateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UsageHourlyAggregateUpsertBulk) DoNothing() *UsageHourlyAggregateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UsageHourlyAggregateCreateBulk.OnConflict
// documentation for more info.
func (u *UsageHourlyAggregateUpsertBulk) Update(set func(*UsageHourlyAggregateUpsert)) *UsageHourlyAggregateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UsageHourlyAggregateUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UsageHourlyAggregateUpsertBulk) SetUpdatedAt(v time.Time) *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertBulk) UpdateUpdatedAt() *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UsageHourlyAggregateUpsertBulk) SetUserID(v int) *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *UsageHourlyAggregateUpsertBulk) AddUserID(v int) *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertBulk) UpdateUserID() *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *UsageHourlyAggregateUpsertBulk) SetAPIKeyID(v int) *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *UsageHourlyAggregateUpsertBulk) AddAPIKeyID(v int) *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertBulk) UpdateAPIKeyID() *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetProjectID sets the "project_id" field.
func (u *UsageHourlyAggregateUpsertBulk) SetProjectID(v int) *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetProjectID(v)
	})
}

// AddProjectID adds v to the "project_id" field.
func (u *UsageHourlyAggregateUpsertBulk) AddProjectID(v int) *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.AddProjectID(v)
	})
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertBulk) UpdateProjectID() *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdateProjectID()
	})
}

// SetChannelID sets the "channel_id" field.
func (u *UsageHourlyAggregateUpsertBulk) SetChannelID(v int) *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetChannelID(v)
	})
}

// AddChannelID adds v to the "channel_id" field.
func (u *UsageHourlyAggregateUpsertBulk) AddChannelID(v int) *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.AddChannelID(v)
	})
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertBulk) UpdateChannelID() *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdateChannelID()
	})
}

// SetUpstreamAccountID sets the "upstream_account_id" field.
func (u *UsageHourlyAggregateUpsertBulk) SetUpstreamAccountID(v int) *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetUpstreamAccountID(v)
	})
}

// AddUpstreamAccountID adds v to the "upstream_account_id" field.
func (u *UsageHourlyAggregateUpsertBulk) AddUpstreamAccountID(v int) *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.AddUpstreamAccountID(v)
	})
}

// UpdateUpstreamAccountID sets the "upstream_account_id" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertBulk) UpdateUpstreamAccountID() *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdateUpstreamAccountID()
	})
}

// SetModelID sets the "model_id" field.
func (u *UsageHourlyAggregateUpsertBulk) SetModelID(v string) *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetModelID(v)
	})
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertBulk) UpdateModelID() *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdateModelID()
	})
}

// SetRequestType sets the "request_type" field.
func (u *UsageHourlyAggregateUpsertBulk) SetRequestType(v usagehourlyaggregate.RequestType) *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetRequestType(v)
	})
}

// UpdateRequestType sets the "request_type" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertBulk) UpdateRequestType() *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdateRequestType()
	})
}

// SetStatus sets the "status" field.
func (u *UsageHourlyAggregateUpsertBulk) SetStatus(v usagehourlyaggregate.Status) *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertBulk) UpdateStatus() *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdateStatus()
	})
}

// SetCurrency sets the "currency" field.
func (u *UsageHourlyAggregateUpsertBulk) SetCurrency(v string) *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertBulk) UpdateCurrency() *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdateCurrency()
	})
}

// SetRequestCount sets the "request_count" field.
func (u *UsageHourlyAggregateUpsertBulk) SetRequestCount(v int64) *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetRequestCount(v)
	})
}

// AddRequestCount adds v to the "request_count" field.
func (u *UsageHourlyAggregateUpsertBulk) AddRequestCount(v int64) *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.AddRequestCount(v)
	})
}

// UpdateRequestCount sets the "request_count" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertBulk) UpdateRequestCount() *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdateRequestCount()
	})
}

// SetSuccessCount sets the "success_count" field.
func (u *UsageHourlyAggregateUpsertBulk) SetSuccessCount(v int64) *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetSuccessCount(v)
	})
}

// AddSuccessCount adds v to the "success_count" field.
func (u *UsageHourlyAggregateUpsertBulk) AddSuccessCount(v int64) *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.AddSuccessCount(v)
	})
}

// UpdateSuccessCount sets the "success_count" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertBulk) UpdateSuccessCount() *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdateSuccessCount()
	})
}

// SetErrorCount sets the "error_count" field.
func (u *UsageHourlyAggregateUpsertBulk) SetErrorCount(v int64) *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetErrorCount(v)
	})
}

// AddErrorCount adds v to the "error_count" field.
func (u *UsageHourlyAggregateUpsertBulk) AddErrorCount(v int64) *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.AddErrorCount(v)
	})
}

// UpdateErrorCount sets the "error_count" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertBulk) UpdateErrorCount() *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdateErrorCount()
	})
}

// SetPromptTokens sets the "prompt_tokens" field.
func (u *UsageHourlyAggregateUpsertBulk) SetPromptTokens(v int64) *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetPromptTokens(v)
	})
}

// AddPromptTokens adds v to the "prompt_tokens" field.
func (u *UsageHourlyAggregateUpsertBulk) AddPromptTokens(v int64) *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.AddPromptTokens(v)
	})
}

// UpdatePromptTokens sets the "prompt_tokens" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertBulk) UpdatePromptTokens() *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdatePromptTokens()
	})
}

// SetCompletionTokens sets the "completion_tokens" field.
func (u *UsageHourlyAggregateUpsertBulk) SetCompletionTokens(v int64) *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetCompletionTokens(v)
	})
}

// AddCompletionTokens adds v to the "completion_tokens" field.
func (u *UsageHourlyAggregateUpsertBulk) AddCompletionTokens(v int64) *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.AddCompletionTokens(v)
	})
}

// UpdateCompletionTokens sets the "completion_tokens" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertBulk) UpdateCompletionTokens() *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdateCompletionTokens()
	})
}

// SetTotalTokens sets the "total_tokens" field.
func (u *UsageHourlyAggregateUpsertBulk) SetTotalTokens(v int64) *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetTotalTokens(v)
	})
}

// AddTotalTokens adds v to the "total_tokens" field.
func (u *UsageHourlyAggregateUpsertBulk) AddTotalTokens(v int64) *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.AddTotalTokens(v)
	})
}

// UpdateTotalTokens sets the "total_tokens" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertBulk) UpdateTotalTokens() *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdateTotalTokens()
	})
}

// SetUserChargeMicros sets the "user_charge_micros" field.
func (u *UsageHourlyAggregateUpsertBulk) SetUserChargeMicros(v int64) *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetUserChargeMicros(v)
	})
}

// AddUserChargeMicros adds v to the "user_charge_micros" field.
func (u *UsageHourlyAggregateUpsertBulk) AddUserChargeMicros(v int64) *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.AddUserChargeMicros(v)
	})
}

// UpdateUserChargeMicros sets the "user_charge_micros" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertBulk) UpdateUserChargeMicros() *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdateUserChargeMicros()
	})
}

// SetUpstreamCostMicros sets the "upstream_cost_micros" field.
func (u *UsageHourlyAggregateUpsertBulk) SetUpstreamCostMicros(v int64) *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetUpstreamCostMicros(v)
	})
}

// AddUpstreamCostMicros adds v to the "upstream_cost_micros" field.
func (u *UsageHourlyAggregateUpsertBulk) AddUpstreamCostMicros(v int64) *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.AddUpstreamCostMicros(v)
	})
}

// UpdateUpstreamCostMicros sets the "upstream_cost_micros" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertBulk) UpdateUpstreamCostMicros() *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdateUpstreamCostMicros()
	})
}

// SetGrossMarginMicros sets the "gross_margin_micros" field.
func (u *UsageHourlyAggregateUpsertBulk) SetGrossMarginMicros(v int64) *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.SetGrossMarginMicros(v)
	})
}

// AddGrossMarginMicros adds v to the "gross_margin_micros" field.
func (u *UsageHourlyAggregateUpsertBulk) AddGrossMarginMicros(v int64) *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.AddGrossMarginMicros(v)
	})
}

// UpdateGrossMarginMicros sets the "gross_margin_micros" field to the value that was provided on create.
func (u *UsageHourlyAggregateUpsertBulk) UpdateGrossMarginMicros() *UsageHourlyAggregateUpsertBulk {
	return u.Update(func(s *UsageHourlyAggregateUpsert) {
		s.UpdateGrossMarginMicros()
	})
}

// Exec executes the query.
func (u *UsageHourlyAggregateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UsageHourlyAggregateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UsageHourlyAggregateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UsageHourlyAggregateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
