// Code generated by ent, DO NOT EDIT.

package billingnotificationsetting

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldEQ(FieldUpdatedAt, v))
}

// Key applies equality check predicate on the "key" field. It's identical to KeyEQ.
func Key(v string) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldEQ(FieldKey, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldEQ(FieldEnabled, v))
}

// UserNotificationsEnabled applies equality check predicate on the "user_notifications_enabled" field. It's identical to UserNotificationsEnabledEQ.
func UserNotificationsEnabled(v bool) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldEQ(FieldUserNotificationsEnabled, v))
}

// OperatorAlertsEnabled applies equality check predicate on the "operator_alerts_enabled" field. It's identical to OperatorAlertsEnabledEQ.
func OperatorAlertsEnabled(v bool) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldEQ(FieldOperatorAlertsEnabled, v))
}

// LowBalanceThresholdMicros applies equality check predicate on the "low_balance_threshold_micros" field. It's identical to LowBalanceThresholdMicrosEQ.
func LowBalanceThresholdMicros(v int64) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldEQ(FieldLowBalanceThresholdMicros, v))
}

// LargeConsumptionThresholdMicros applies equality check predicate on the "large_consumption_threshold_micros" field. It's identical to LargeConsumptionThresholdMicrosEQ.
func LargeConsumptionThresholdMicros(v int64) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldEQ(FieldLargeConsumptionThresholdMicros, v))
}

// SubscriptionExpiryWarningDays applies equality check predicate on the "subscription_expiry_warning_days" field. It's identical to SubscriptionExpiryWarningDaysEQ.
func SubscriptionExpiryWarningDays(v int) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldEQ(FieldSubscriptionExpiryWarningDays, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldEQ(FieldCurrency, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldLTE(FieldUpdatedAt, v))
}

// KeyEQ applies the EQ predicate on the "key" field.
func KeyEQ(v string) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldEQ(FieldKey, v))
}

// KeyNEQ applies the NEQ predicate on the "key" field.
func KeyNEQ(v string) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldNEQ(FieldKey, v))
}

// KeyIn applies the In predicate on the "key" field.
func KeyIn(vs ...string) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldIn(FieldKey, vs...))
}

// KeyNotIn applies the NotIn predicate on the "key" field.
func KeyNotIn(vs ...string) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldNotIn(FieldKey, vs...))
}

// KeyGT applies the GT predicate on the "key" field.
func KeyGT(v string) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldGT(FieldKey, v))
}

// KeyGTE applies the GTE predicate on the "key" field.
func KeyGTE(v string) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldGTE(FieldKey, v))
}

// KeyLT applies the LT predicate on the "key" field.
func KeyLT(v string) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldLT(FieldKey, v))
}

// KeyLTE applies the LTE predicate on the "key" field.
func KeyLTE(v string) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldLTE(FieldKey, v))
}

// KeyContains applies the Contains predicate on the "key" field.
func KeyContains(v string) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldContains(FieldKey, v))
}

// KeyHasPrefix applies the HasPrefix predicate on the "key" field.
func KeyHasPrefix(v string) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldHasPrefix(FieldKey, v))
}

// KeyHasSuffix applies the HasSuffix predicate on the "key" field.
func KeyHasSuffix(v string) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldHasSuffix(FieldKey, v))
}

// KeyEqualFold applies the EqualFold predicate on the "key" field.
func KeyEqualFold(v string) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldEqualFold(FieldKey, v))
}

// KeyContainsFold applies the ContainsFold predicate on the "key" field.
func KeyContainsFold(v string) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldContainsFold(FieldKey, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldNEQ(FieldEnabled, v))
}

// UserNotificationsEnabledEQ applies the EQ predicate on the "user_notifications_enabled" field.
func UserNotificationsEnabledEQ(v bool) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldEQ(FieldUserNotificationsEnabled, v))
}

// UserNotificationsEnabledNEQ applies the NEQ predicate on the "user_notifications_enabled" field.
func UserNotificationsEnabledNEQ(v bool) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldNEQ(FieldUserNotificationsEnabled, v))
}

// OperatorAlertsEnabledEQ applies the EQ predicate on the "operator_alerts_enabled" field.
func OperatorAlertsEnabledEQ(v bool) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldEQ(FieldOperatorAlertsEnabled, v))
}

// OperatorAlertsEnabledNEQ applies the NEQ predicate on the "operator_alerts_enabled" field.
func OperatorAlertsEnabledNEQ(v bool) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldNEQ(FieldOperatorAlertsEnabled, v))
}

// LowBalanceThresholdMicrosEQ applies the EQ predicate on the "low_balance_threshold_micros" field.
func LowBalanceThresholdMicrosEQ(v int64) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldEQ(FieldLowBalanceThresholdMicros, v))
}

// LowBalanceThresholdMicrosNEQ applies the NEQ predicate on the "low_balance_threshold_micros" field.
func LowBalanceThresholdMicrosNEQ(v int64) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldNEQ(FieldLowBalanceThresholdMicros, v))
}

// LowBalanceThresholdMicrosIn applies the In predicate on the "low_balance_threshold_micros" field.
func LowBalanceThresholdMicrosIn(vs ...int64) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldIn(FieldLowBalanceThresholdMicros, vs...))
}

// LowBalanceThresholdMicrosNotIn applies the NotIn predicate on the "low_balance_threshold_micros" field.
func LowBalanceThresholdMicrosNotIn(vs ...int64) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldNotIn(FieldLowBalanceThresholdMicros, vs...))
}

// LowBalanceThresholdMicrosGT applies the GT predicate on the "low_balance_threshold_micros" field.
func LowBalanceThresholdMicrosGT(v int64) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldGT(FieldLowBalanceThresholdMicros, v))
}

// LowBalanceThresholdMicrosGTE applies the GTE predicate on the "low_balance_threshold_micros" field.
func LowBalanceThresholdMicrosGTE(v int64) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldGTE(FieldLowBalanceThresholdMicros, v))
}

// LowBalanceThresholdMicrosLT applies the LT predicate on the "low_balance_threshold_micros" field.
func LowBalanceThresholdMicrosLT(v int64) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldLT(FieldLowBalanceThresholdMicros, v))
}

// LowBalanceThresholdMicrosLTE applies the LTE predicate on the "low_balance_threshold_micros" field.
func LowBalanceThresholdMicrosLTE(v int64) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldLTE(FieldLowBalanceThresholdMicros, v))
}

// LargeConsumptionThresholdMicrosEQ applies the EQ predicate on the "large_consumption_threshold_micros" field.
func LargeConsumptionThresholdMicrosEQ(v int64) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldEQ(FieldLargeConsumptionThresholdMicros, v))
}

// LargeConsumptionThresholdMicrosNEQ applies the NEQ predicate on the "large_consumption_threshold_micros" field.
func LargeConsumptionThresholdMicrosNEQ(v int64) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldNEQ(FieldLargeConsumptionThresholdMicros, v))
}

// LargeConsumptionThresholdMicrosIn applies the In predicate on the "large_consumption_threshold_micros" field.
func LargeConsumptionThresholdMicrosIn(vs ...int64) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldIn(FieldLargeConsumptionThresholdMicros, vs...))
}

// LargeConsumptionThresholdMicrosNotIn applies the NotIn predicate on the "large_consumption_threshold_micros" field.
func LargeConsumptionThresholdMicrosNotIn(vs ...int64) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldNotIn(FieldLargeConsumptionThresholdMicros, vs...))
}

// LargeConsumptionThresholdMicrosGT applies the GT predicate on the "large_consumption_threshold_micros" field.
func LargeConsumptionThresholdMicrosGT(v int64) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldGT(FieldLargeConsumptionThresholdMicros, v))
}

// LargeConsumptionThresholdMicrosGTE applies the GTE predicate on the "large_consumption_threshold_micros" field.
func LargeConsumptionThresholdMicrosGTE(v int64) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldGTE(FieldLargeConsumptionThresholdMicros, v))
}

// LargeConsumptionThresholdMicrosLT applies the LT predicate on the "large_consumption_threshold_micros" field.
func LargeConsumptionThresholdMicrosLT(v int64) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldLT(FieldLargeConsumptionThresholdMicros, v))
}

// LargeConsumptionThresholdMicrosLTE applies the LTE predicate on the "large_consumption_threshold_micros" field.
func LargeConsumptionThresholdMicrosLTE(v int64) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldLTE(FieldLargeConsumptionThresholdMicros, v))
}

// SubscriptionExpiryWarningDaysEQ applies the EQ predicate on the "subscription_expiry_warning_days" field.
func SubscriptionExpiryWarningDaysEQ(v int) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldEQ(FieldSubscriptionExpiryWarningDays, v))
}

// SubscriptionExpiryWarningDaysNEQ applies the NEQ predicate on the "subscription_expiry_warning_days" field.
func SubscriptionExpiryWarningDaysNEQ(v int) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldNEQ(FieldSubscriptionExpiryWarningDays, v))
}

// SubscriptionExpiryWarningDaysIn applies the In predicate on the "subscription_expiry_warning_days" field.
func SubscriptionExpiryWarningDaysIn(vs ...int) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldIn(FieldSubscriptionExpiryWarningDays, vs...))
}

// SubscriptionExpiryWarningDaysNotIn applies the NotIn predicate on the "subscription_expiry_warning_days" field.
func SubscriptionExpiryWarningDaysNotIn(vs ...int) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldNotIn(FieldSubscriptionExpiryWarningDays, vs...))
}

// SubscriptionExpiryWarningDaysGT applies the GT predicate on the "subscription_expiry_warning_days" field.
func SubscriptionExpiryWarningDaysGT(v int) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldGT(FieldSubscriptionExpiryWarningDays, v))
}

// SubscriptionExpiryWarningDaysGTE applies the GTE predicate on the "subscription_expiry_warning_days" field.
func SubscriptionExpiryWarningDaysGTE(v int) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldGTE(FieldSubscriptionExpiryWarningDays, v))
}

// SubscriptionExpiryWarningDaysLT applies the LT predicate on the "subscription_expiry_warning_days" field.
func SubscriptionExpiryWarningDaysLT(v int) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldLT(FieldSubscriptionExpiryWarningDays, v))
}

// SubscriptionExpiryWarningDaysLTE applies the LTE predicate on the "subscription_expiry_warning_days" field.
func SubscriptionExpiryWarningDaysLTE(v int) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldLTE(FieldSubscriptionExpiryWarningDays, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.FieldContainsFold(FieldCurrency, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BillingNotificationSetting) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BillingNotificationSetting) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BillingNotificationSetting) predicate.BillingNotificationSetting {
	return predicate.BillingNotificationSetting(sql.NotPredicates(p))
}
