// Code generated by ent, DO NOT EDIT.

package billingaccountbinding

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// BillingAccountID applies equality check predicate on the "billing_account_id" field. It's identical to BillingAccountIDEQ.
func BillingAccountID(v int) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldEQ(FieldBillingAccountID, v))
}

// OwnerID applies equality check predicate on the "owner_id" field. It's identical to OwnerIDEQ.
func OwnerID(v int) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldEQ(FieldOwnerID, v))
}

// Relation applies equality check predicate on the "relation" field. It's identical to RelationEQ.
func Relation(v string) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldEQ(FieldRelation, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldLTE(FieldUpdatedAt, v))
}

// BillingAccountIDEQ applies the EQ predicate on the "billing_account_id" field.
func BillingAccountIDEQ(v int) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldEQ(FieldBillingAccountID, v))
}

// BillingAccountIDNEQ applies the NEQ predicate on the "billing_account_id" field.
func BillingAccountIDNEQ(v int) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldNEQ(FieldBillingAccountID, v))
}

// BillingAccountIDIn applies the In predicate on the "billing_account_id" field.
func BillingAccountIDIn(vs ...int) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldIn(FieldBillingAccountID, vs...))
}

// BillingAccountIDNotIn applies the NotIn predicate on the "billing_account_id" field.
func BillingAccountIDNotIn(vs ...int) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldNotIn(FieldBillingAccountID, vs...))
}

// OwnerTypeEQ applies the EQ predicate on the "owner_type" field.
func OwnerTypeEQ(v OwnerType) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldEQ(FieldOwnerType, v))
}

// OwnerTypeNEQ applies the NEQ predicate on the "owner_type" field.
func OwnerTypeNEQ(v OwnerType) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldNEQ(FieldOwnerType, v))
}

// OwnerTypeIn applies the In predicate on the "owner_type" field.
func OwnerTypeIn(vs ...OwnerType) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldIn(FieldOwnerType, vs...))
}

// OwnerTypeNotIn applies the NotIn predicate on the "owner_type" field.
func OwnerTypeNotIn(vs ...OwnerType) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldNotIn(FieldOwnerType, vs...))
}

// OwnerIDEQ applies the EQ predicate on the "owner_id" field.
func OwnerIDEQ(v int) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldEQ(FieldOwnerID, v))
}

// OwnerIDNEQ applies the NEQ predicate on the "owner_id" field.
func OwnerIDNEQ(v int) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldNEQ(FieldOwnerID, v))
}

// OwnerIDIn applies the In predicate on the "owner_id" field.
func OwnerIDIn(vs ...int) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldIn(FieldOwnerID, vs...))
}

// OwnerIDNotIn applies the NotIn predicate on the "owner_id" field.
func OwnerIDNotIn(vs ...int) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldNotIn(FieldOwnerID, vs...))
}

// OwnerIDGT applies the GT predicate on the "owner_id" field.
func OwnerIDGT(v int) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldGT(FieldOwnerID, v))
}

// OwnerIDGTE applies the GTE predicate on the "owner_id" field.
func OwnerIDGTE(v int) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldGTE(FieldOwnerID, v))
}

// OwnerIDLT applies the LT predicate on the "owner_id" field.
func OwnerIDLT(v int) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldLT(FieldOwnerID, v))
}

// OwnerIDLTE applies the LTE predicate on the "owner_id" field.
func OwnerIDLTE(v int) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldLTE(FieldOwnerID, v))
}

// RelationEQ applies the EQ predicate on the "relation" field.
func RelationEQ(v string) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldEQ(FieldRelation, v))
}

// RelationNEQ applies the NEQ predicate on the "relation" field.
func RelationNEQ(v string) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldNEQ(FieldRelation, v))
}

// RelationIn applies the In predicate on the "relation" field.
func RelationIn(vs ...string) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldIn(FieldRelation, vs...))
}

// RelationNotIn applies the NotIn predicate on the "relation" field.
func RelationNotIn(vs ...string) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldNotIn(FieldRelation, vs...))
}

// RelationGT applies the GT predicate on the "relation" field.
func RelationGT(v string) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldGT(FieldRelation, v))
}

// RelationGTE applies the GTE predicate on the "relation" field.
func RelationGTE(v string) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldGTE(FieldRelation, v))
}

// RelationLT applies the LT predicate on the "relation" field.
func RelationLT(v string) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldLT(FieldRelation, v))
}

// RelationLTE applies the LTE predicate on the "relation" field.
func RelationLTE(v string) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldLTE(FieldRelation, v))
}

// RelationContains applies the Contains predicate on the "relation" field.
func RelationContains(v string) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldContains(FieldRelation, v))
}

// RelationHasPrefix applies the HasPrefix predicate on the "relation" field.
func RelationHasPrefix(v string) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldHasPrefix(FieldRelation, v))
}

// RelationHasSuffix applies the HasSuffix predicate on the "relation" field.
func RelationHasSuffix(v string) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldHasSuffix(FieldRelation, v))
}

// RelationEqualFold applies the EqualFold predicate on the "relation" field.
func RelationEqualFold(v string) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldEqualFold(FieldRelation, v))
}

// RelationContainsFold applies the ContainsFold predicate on the "relation" field.
func RelationContainsFold(v string) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.FieldContainsFold(FieldRelation, v))
}

// HasBillingAccount applies the HasEdge predicate on the "billing_account" edge.
func HasBillingAccount() predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, BillingAccountTable, BillingAccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBillingAccountWith applies the HasEdge predicate on the "billing_account" edge with a given conditions (other predicates).
func HasBillingAccountWith(preds ...predicate.BillingAccount) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(func(s *sql.Selector) {
		step := newBillingAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BillingAccountBinding) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BillingAccountBinding) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BillingAccountBinding) predicate.BillingAccountBinding {
	return predicate.BillingAccountBinding(sql.NotPredicates(p))
}
