// Code generated by ent, DO NOT EDIT.

package affiliaterebate

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the affiliaterebate type in the database.
	Label = "affiliate_rebate"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldInvitationID holds the string denoting the invitation_id field in the database.
	FieldInvitationID = "invitation_id"
	// FieldInviterUserID holds the string denoting the inviter_user_id field in the database.
	FieldInviterUserID = "inviter_user_id"
	// FieldInviteeUserID holds the string denoting the invitee_user_id field in the database.
	FieldInviteeUserID = "invitee_user_id"
	// FieldSourceType holds the string denoting the source_type field in the database.
	FieldSourceType = "source_type"
	// FieldSourceID holds the string denoting the source_id field in the database.
	FieldSourceID = "source_id"
	// FieldPaymentOrderID holds the string denoting the payment_order_id field in the database.
	FieldPaymentOrderID = "payment_order_id"
	// FieldUserSubscriptionID holds the string denoting the user_subscription_id field in the database.
	FieldUserSubscriptionID = "user_subscription_id"
	// FieldBaseAmountMicros holds the string denoting the base_amount_micros field in the database.
	FieldBaseAmountMicros = "base_amount_micros"
	// FieldAmountMicros holds the string denoting the amount_micros field in the database.
	FieldAmountMicros = "amount_micros"
	// FieldRateBps holds the string denoting the rate_bps field in the database.
	FieldRateBps = "rate_bps"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldFreezeUntil holds the string denoting the freeze_until field in the database.
	FieldFreezeUntil = "freeze_until"
	// FieldTransferredAt holds the string denoting the transferred_at field in the database.
	FieldTransferredAt = "transferred_at"
	// FieldLedgerTransactionID holds the string denoting the ledger_transaction_id field in the database.
	FieldLedgerTransactionID = "ledger_transaction_id"
	// FieldIdempotencyKey holds the string denoting the idempotency_key field in the database.
	FieldIdempotencyKey = "idempotency_key"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// EdgeInvitation holds the string denoting the invitation edge name in mutations.
	EdgeInvitation = "invitation"
	// EdgeInviter holds the string denoting the inviter edge name in mutations.
	EdgeInviter = "inviter"
	// EdgeInvitee holds the string denoting the invitee edge name in mutations.
	EdgeInvitee = "invitee"
	// EdgePaymentOrder holds the string denoting the payment_order edge name in mutations.
	EdgePaymentOrder = "payment_order"
	// EdgeUserSubscription holds the string denoting the user_subscription edge name in mutations.
	EdgeUserSubscription = "user_subscription"
	// EdgeLedgerTransaction holds the string denoting the ledger_transaction edge name in mutations.
	EdgeLedgerTransaction = "ledger_transaction"
	// Table holds the table name of the affiliaterebate in the database.
	Table = "affiliate_rebates"
	// InvitationTable is the table that holds the invitation relation/edge.
	InvitationTable = "affiliate_rebates"
	// InvitationInverseTable is the table name for the AffiliateInvitation entity.
	// It exists in this package in order to avoid circular dependency with the "affiliateinvitation" package.
	InvitationInverseTable = "affiliate_invitations"
	// InvitationColumn is the table column denoting the invitation relation/edge.
	InvitationColumn = "invitation_id"
	// InviterTable is the table that holds the inviter relation/edge.
	InviterTable = "affiliate_rebates"
	// InviterInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	InviterInverseTable = "users"
	// InviterColumn is the table column denoting the inviter relation/edge.
	InviterColumn = "inviter_user_id"
	// InviteeTable is the table that holds the invitee relation/edge.
	InviteeTable = "affiliate_rebates"
	// InviteeInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	InviteeInverseTable = "users"
	// InviteeColumn is the table column denoting the invitee relation/edge.
	InviteeColumn = "invitee_user_id"
	// PaymentOrderTable is the table that holds the payment_order relation/edge.
	PaymentOrderTable = "affiliate_rebates"
	// PaymentOrderInverseTable is the table name for the PaymentOrder entity.
	// It exists in this package in order to avoid circular dependency with the "paymentorder" package.
	PaymentOrderInverseTable = "payment_orders"
	// PaymentOrderColumn is the table column denoting the payment_order relation/edge.
	PaymentOrderColumn = "payment_order_id"
	// UserSubscriptionTable is the table that holds the user_subscription relation/edge.
	UserSubscriptionTable = "affiliate_rebates"
	// UserSubscriptionInverseTable is the table name for the UserSubscription entity.
	// It exists in this package in order to avoid circular dependency with the "usersubscription" package.
	UserSubscriptionInverseTable = "user_subscriptions"
	// UserSubscriptionColumn is the table column denoting the user_subscription relation/edge.
	UserSubscriptionColumn = "user_subscription_id"
	// LedgerTransactionTable is the table that holds the ledger_transaction relation/edge.
	LedgerTransactionTable = "affiliate_rebates"
	// LedgerTransactionInverseTable is the table name for the LedgerTransaction entity.
	// It exists in this package in order to avoid circular dependency with the "ledgertransaction" package.
	LedgerTransactionInverseTable = "ledger_transactions"
	// LedgerTransactionColumn is the table column denoting the ledger_transaction relation/edge.
	LedgerTransactionColumn = "ledger_transaction_id"
)

// Columns holds all SQL columns for affiliaterebate fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldInvitationID,
	FieldInviterUserID,
	FieldInviteeUserID,
	FieldSourceType,
	FieldSourceID,
	FieldPaymentOrderID,
	FieldUserSubscriptionID,
	FieldBaseAmountMicros,
	FieldAmountMicros,
	FieldRateBps,
	FieldCurrency,
	FieldStatus,
	FieldFreezeUntil,
	FieldTransferredAt,
	FieldLedgerTransactionID,
	FieldIdempotencyKey,
	FieldNotes,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/looplj/axonhub/internal/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// BaseAmountMicrosValidator is a validator for the "base_amount_micros" field. It is called by the builders before save.
	BaseAmountMicrosValidator func(int64) error
	// AmountMicrosValidator is a validator for the "amount_micros" field. It is called by the builders before save.
	AmountMicrosValidator func(int64) error
	// RateBpsValidator is a validator for the "rate_bps" field. It is called by the builders before save.
	RateBpsValidator func(int) error
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// DefaultNotes holds the default value on creation for the "notes" field.
	DefaultNotes string
)

// SourceType defines the type for the "source_type" enum field.
type SourceType string

// SourceType values.
const (
	SourceTypePaymentOrder     SourceType = "payment_order"
	SourceTypeUserSubscription SourceType = "user_subscription"
)

func (st SourceType) String() string {
	return string(st)
}

// SourceTypeValidator is a validator for the "source_type" field enum values. It is called by the builders before save.
func SourceTypeValidator(st SourceType) error {
	switch st {
	case SourceTypePaymentOrder, SourceTypeUserSubscription:
		return nil
	default:
		return fmt.Errorf("affiliaterebate: invalid enum value for source_type field: %q", st)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusFrozen is the default value of the Status enum.
const DefaultStatus = StatusFrozen

// Status values.
const (
	StatusFrozen      Status = "frozen"
	StatusAvailable   Status = "available"
	StatusTransferred Status = "transferred"
	StatusVoided      Status = "voided"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusFrozen, StatusAvailable, StatusTransferred, StatusVoided:
		return nil
	default:
		return fmt.Errorf("affiliaterebate: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the AffiliateRebate queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByInvitationID orders the results by the invitation_id field.
func ByInvitationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvitationID, opts...).ToFunc()
}

// ByInviterUserID orders the results by the inviter_user_id field.
func ByInviterUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInviterUserID, opts...).ToFunc()
}

// ByInviteeUserID orders the results by the invitee_user_id field.
func ByInviteeUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInviteeUserID, opts...).ToFunc()
}

// BySourceType orders the results by the source_type field.
func BySourceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceType, opts...).ToFunc()
}

// BySourceID orders the results by the source_id field.
func BySourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceID, opts...).ToFunc()
}

// ByPaymentOrderID orders the results by the payment_order_id field.
func ByPaymentOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentOrderID, opts...).ToFunc()
}

// ByUserSubscriptionID orders the results by the user_subscription_id field.
func ByUserSubscriptionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserSubscriptionID, opts...).ToFunc()
}

// ByBaseAmountMicros orders the results by the base_amount_micros field.
func ByBaseAmountMicros(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseAmountMicros, opts...).ToFunc()
}

// ByAmountMicros orders the results by the amount_micros field.
func ByAmountMicros(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmountMicros, opts...).ToFunc()
}

// ByRateBps orders the results by the rate_bps field.
func ByRateBps(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRateBps, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByFreezeUntil orders the results by the freeze_until field.
func ByFreezeUntil(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFreezeUntil, opts...).ToFunc()
}

// ByTransferredAt orders the results by the transferred_at field.
func ByTransferredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTransferredAt, opts...).ToFunc()
}

// ByLedgerTransactionID orders the results by the ledger_transaction_id field.
func ByLedgerTransactionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLedgerTransactionID, opts...).ToFunc()
}

// ByIdempotencyKey orders the results by the idempotency_key field.
func ByIdempotencyKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdempotencyKey, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByInvitationField orders the results by invitation field.
func ByInvitationField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInvitationStep(), sql.OrderByField(field, opts...))
	}
}

// ByInviterField orders the results by inviter field.
func ByInviterField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInviterStep(), sql.OrderByField(field, opts...))
	}
}

// ByInviteeField orders the results by invitee field.
func ByInviteeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInviteeStep(), sql.OrderByField(field, opts...))
	}
}

// ByPaymentOrderField orders the results by payment_order field.
func ByPaymentOrderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPaymentOrderStep(), sql.OrderByField(field, opts...))
	}
}

// ByUserSubscriptionField orders the results by user_subscription field.
func ByUserSubscriptionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserSubscriptionStep(), sql.OrderByField(field, opts...))
	}
}

// ByLedgerTransactionField orders the results by ledger_transaction field.
func ByLedgerTransactionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLedgerTransactionStep(), sql.OrderByField(field, opts...))
	}
}
func newInvitationStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InvitationInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, InvitationTable, InvitationColumn),
	)
}
func newInviterStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InviterInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, InviterTable, InviterColumn),
	)
}
func newInviteeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InviteeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, InviteeTable, InviteeColumn),
	)
}
func newPaymentOrderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PaymentOrderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PaymentOrderTable, PaymentOrderColumn),
	)
}
func newUserSubscriptionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserSubscriptionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserSubscriptionTable, UserSubscriptionColumn),
	)
}
func newLedgerTransactionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LedgerTransactionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, LedgerTransactionTable, LedgerTransactionColumn),
	)
}

// MarshalGQL implements graphql.Marshaler interface.
func (e SourceType) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *SourceType) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = SourceType(str)
	if err := SourceTypeValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid SourceType", str)
	}
	return nil
}

// MarshalGQL implements graphql.Marshaler interface.
func (e Status) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *Status) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = Status(str)
	if err := StatusValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid Status", str)
	}
	return nil
}
