// Code generated by ent, DO NOT EDIT.

package affiliaterebate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldUpdatedAt, v))
}

// InvitationID applies equality check predicate on the "invitation_id" field. It's identical to InvitationIDEQ.
func InvitationID(v int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldInvitationID, v))
}

// InviterUserID applies equality check predicate on the "inviter_user_id" field. It's identical to InviterUserIDEQ.
func InviterUserID(v int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldInviterUserID, v))
}

// InviteeUserID applies equality check predicate on the "invitee_user_id" field. It's identical to InviteeUserIDEQ.
func InviteeUserID(v int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldInviteeUserID, v))
}

// SourceID applies equality check predicate on the "source_id" field. It's identical to SourceIDEQ.
func SourceID(v int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldSourceID, v))
}

// PaymentOrderID applies equality check predicate on the "payment_order_id" field. It's identical to PaymentOrderIDEQ.
func PaymentOrderID(v int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldPaymentOrderID, v))
}

// UserSubscriptionID applies equality check predicate on the "user_subscription_id" field. It's identical to UserSubscriptionIDEQ.
func UserSubscriptionID(v int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldUserSubscriptionID, v))
}

// BaseAmountMicros applies equality check predicate on the "base_amount_micros" field. It's identical to BaseAmountMicrosEQ.
func BaseAmountMicros(v int64) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldBaseAmountMicros, v))
}

// AmountMicros applies equality check predicate on the "amount_micros" field. It's identical to AmountMicrosEQ.
func AmountMicros(v int64) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldAmountMicros, v))
}

// RateBps applies equality check predicate on the "rate_bps" field. It's identical to RateBpsEQ.
func RateBps(v int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldRateBps, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldCurrency, v))
}

// FreezeUntil applies equality check predicate on the "freeze_until" field. It's identical to FreezeUntilEQ.
func FreezeUntil(v time.Time) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldFreezeUntil, v))
}

// TransferredAt applies equality check predicate on the "transferred_at" field. It's identical to TransferredAtEQ.
func TransferredAt(v time.Time) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldTransferredAt, v))
}

// LedgerTransactionID applies equality check predicate on the "ledger_transaction_id" field. It's identical to LedgerTransactionIDEQ.
func LedgerTransactionID(v int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldLedgerTransactionID, v))
}

// IdempotencyKey applies equality check predicate on the "idempotency_key" field. It's identical to IdempotencyKeyEQ.
func IdempotencyKey(v string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldIdempotencyKey, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldNotes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldLTE(FieldUpdatedAt, v))
}

// InvitationIDEQ applies the EQ predicate on the "invitation_id" field.
func InvitationIDEQ(v int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldInvitationID, v))
}

// InvitationIDNEQ applies the NEQ predicate on the "invitation_id" field.
func InvitationIDNEQ(v int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNEQ(FieldInvitationID, v))
}

// InvitationIDIn applies the In predicate on the "invitation_id" field.
func InvitationIDIn(vs ...int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldIn(FieldInvitationID, vs...))
}

// InvitationIDNotIn applies the NotIn predicate on the "invitation_id" field.
func InvitationIDNotIn(vs ...int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNotIn(FieldInvitationID, vs...))
}

// InviterUserIDEQ applies the EQ predicate on the "inviter_user_id" field.
func InviterUserIDEQ(v int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldInviterUserID, v))
}

// InviterUserIDNEQ applies the NEQ predicate on the "inviter_user_id" field.
func InviterUserIDNEQ(v int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNEQ(FieldInviterUserID, v))
}

// InviterUserIDIn applies the In predicate on the "inviter_user_id" field.
func InviterUserIDIn(vs ...int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldIn(FieldInviterUserID, vs...))
}

// InviterUserIDNotIn applies the NotIn predicate on the "inviter_user_id" field.
func InviterUserIDNotIn(vs ...int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNotIn(FieldInviterUserID, vs...))
}

// InviteeUserIDEQ applies the EQ predicate on the "invitee_user_id" field.
func InviteeUserIDEQ(v int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldInviteeUserID, v))
}

// InviteeUserIDNEQ applies the NEQ predicate on the "invitee_user_id" field.
func InviteeUserIDNEQ(v int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNEQ(FieldInviteeUserID, v))
}

// InviteeUserIDIn applies the In predicate on the "invitee_user_id" field.
func InviteeUserIDIn(vs ...int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldIn(FieldInviteeUserID, vs...))
}

// InviteeUserIDNotIn applies the NotIn predicate on the "invitee_user_id" field.
func InviteeUserIDNotIn(vs ...int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNotIn(FieldInviteeUserID, vs...))
}

// SourceTypeEQ applies the EQ predicate on the "source_type" field.
func SourceTypeEQ(v SourceType) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldSourceType, v))
}

// SourceTypeNEQ applies the NEQ predicate on the "source_type" field.
func SourceTypeNEQ(v SourceType) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNEQ(FieldSourceType, v))
}

// SourceTypeIn applies the In predicate on the "source_type" field.
func SourceTypeIn(vs ...SourceType) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldIn(FieldSourceType, vs...))
}

// SourceTypeNotIn applies the NotIn predicate on the "source_type" field.
func SourceTypeNotIn(vs ...SourceType) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNotIn(FieldSourceType, vs...))
}

// SourceIDEQ applies the EQ predicate on the "source_id" field.
func SourceIDEQ(v int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldSourceID, v))
}

// SourceIDNEQ applies the NEQ predicate on the "source_id" field.
func SourceIDNEQ(v int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNEQ(FieldSourceID, v))
}

// SourceIDIn applies the In predicate on the "source_id" field.
func SourceIDIn(vs ...int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldIn(FieldSourceID, vs...))
}

// SourceIDNotIn applies the NotIn predicate on the "source_id" field.
func SourceIDNotIn(vs ...int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNotIn(FieldSourceID, vs...))
}

// SourceIDGT applies the GT predicate on the "source_id" field.
func SourceIDGT(v int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldGT(FieldSourceID, v))
}

// SourceIDGTE applies the GTE predicate on the "source_id" field.
func SourceIDGTE(v int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldGTE(FieldSourceID, v))
}

// SourceIDLT applies the LT predicate on the "source_id" field.
func SourceIDLT(v int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldLT(FieldSourceID, v))
}

// SourceIDLTE applies the LTE predicate on the "source_id" field.
func SourceIDLTE(v int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldLTE(FieldSourceID, v))
}

// PaymentOrderIDEQ applies the EQ predicate on the "payment_order_id" field.
func PaymentOrderIDEQ(v int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldPaymentOrderID, v))
}

// PaymentOrderIDNEQ applies the NEQ predicate on the "payment_order_id" field.
func PaymentOrderIDNEQ(v int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNEQ(FieldPaymentOrderID, v))
}

// PaymentOrderIDIn applies the In predicate on the "payment_order_id" field.
func PaymentOrderIDIn(vs ...int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldIn(FieldPaymentOrderID, vs...))
}

// PaymentOrderIDNotIn applies the NotIn predicate on the "payment_order_id" field.
func PaymentOrderIDNotIn(vs ...int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNotIn(FieldPaymentOrderID, vs...))
}

// PaymentOrderIDIsNil applies the IsNil predicate on the "payment_order_id" field.
func PaymentOrderIDIsNil() predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldIsNull(FieldPaymentOrderID))
}

// PaymentOrderIDNotNil applies the NotNil predicate on the "payment_order_id" field.
func PaymentOrderIDNotNil() predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNotNull(FieldPaymentOrderID))
}

// UserSubscriptionIDEQ applies the EQ predicate on the "user_subscription_id" field.
func UserSubscriptionIDEQ(v int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldUserSubscriptionID, v))
}

// UserSubscriptionIDNEQ applies the NEQ predicate on the "user_subscription_id" field.
func UserSubscriptionIDNEQ(v int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNEQ(FieldUserSubscriptionID, v))
}

// UserSubscriptionIDIn applies the In predicate on the "user_subscription_id" field.
func UserSubscriptionIDIn(vs ...int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldIn(FieldUserSubscriptionID, vs...))
}

// UserSubscriptionIDNotIn applies the NotIn predicate on the "user_subscription_id" field.
func UserSubscriptionIDNotIn(vs ...int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNotIn(FieldUserSubscriptionID, vs...))
}

// UserSubscriptionIDIsNil applies the IsNil predicate on the "user_subscription_id" field.
func UserSubscriptionIDIsNil() predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldIsNull(FieldUserSubscriptionID))
}

// UserSubscriptionIDNotNil applies the NotNil predicate on the "user_subscription_id" field.
func UserSubscriptionIDNotNil() predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNotNull(FieldUserSubscriptionID))
}

// BaseAmountMicrosEQ applies the EQ predicate on the "base_amount_micros" field.
func BaseAmountMicrosEQ(v int64) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldBaseAmountMicros, v))
}

// BaseAmountMicrosNEQ applies the NEQ predicate on the "base_amount_micros" field.
func BaseAmountMicrosNEQ(v int64) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNEQ(FieldBaseAmountMicros, v))
}

// BaseAmountMicrosIn applies the In predicate on the "base_amount_micros" field.
func BaseAmountMicrosIn(vs ...int64) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldIn(FieldBaseAmountMicros, vs...))
}

// BaseAmountMicrosNotIn applies the NotIn predicate on the "base_amount_micros" field.
func BaseAmountMicrosNotIn(vs ...int64) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNotIn(FieldBaseAmountMicros, vs...))
}

// BaseAmountMicrosGT applies the GT predicate on the "base_amount_micros" field.
func BaseAmountMicrosGT(v int64) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldGT(FieldBaseAmountMicros, v))
}

// BaseAmountMicrosGTE applies the GTE predicate on the "base_amount_micros" field.
func BaseAmountMicrosGTE(v int64) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldGTE(FieldBaseAmountMicros, v))
}

// BaseAmountMicrosLT applies the LT predicate on the "base_amount_micros" field.
func BaseAmountMicrosLT(v int64) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldLT(FieldBaseAmountMicros, v))
}

// BaseAmountMicrosLTE applies the LTE predicate on the "base_amount_micros" field.
func BaseAmountMicrosLTE(v int64) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldLTE(FieldBaseAmountMicros, v))
}

// AmountMicrosEQ applies the EQ predicate on the "amount_micros" field.
func AmountMicrosEQ(v int64) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldAmountMicros, v))
}

// AmountMicrosNEQ applies the NEQ predicate on the "amount_micros" field.
func AmountMicrosNEQ(v int64) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNEQ(FieldAmountMicros, v))
}

// AmountMicrosIn applies the In predicate on the "amount_micros" field.
func AmountMicrosIn(vs ...int64) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldIn(FieldAmountMicros, vs...))
}

// AmountMicrosNotIn applies the NotIn predicate on the "amount_micros" field.
func AmountMicrosNotIn(vs ...int64) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNotIn(FieldAmountMicros, vs...))
}

// AmountMicrosGT applies the GT predicate on the "amount_micros" field.
func AmountMicrosGT(v int64) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldGT(FieldAmountMicros, v))
}

// AmountMicrosGTE applies the GTE predicate on the "amount_micros" field.
func AmountMicrosGTE(v int64) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldGTE(FieldAmountMicros, v))
}

// AmountMicrosLT applies the LT predicate on the "amount_micros" field.
func AmountMicrosLT(v int64) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldLT(FieldAmountMicros, v))
}

// AmountMicrosLTE applies the LTE predicate on the "amount_micros" field.
func AmountMicrosLTE(v int64) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldLTE(FieldAmountMicros, v))
}

// RateBpsEQ applies the EQ predicate on the "rate_bps" field.
func RateBpsEQ(v int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldRateBps, v))
}

// RateBpsNEQ applies the NEQ predicate on the "rate_bps" field.
func RateBpsNEQ(v int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNEQ(FieldRateBps, v))
}

// RateBpsIn applies the In predicate on the "rate_bps" field.
func RateBpsIn(vs ...int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldIn(FieldRateBps, vs...))
}

// RateBpsNotIn applies the NotIn predicate on the "rate_bps" field.
func RateBpsNotIn(vs ...int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNotIn(FieldRateBps, vs...))
}

// RateBpsGT applies the GT predicate on the "rate_bps" field.
func RateBpsGT(v int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldGT(FieldRateBps, v))
}

// RateBpsGTE applies the GTE predicate on the "rate_bps" field.
func RateBpsGTE(v int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldGTE(FieldRateBps, v))
}

// RateBpsLT applies the LT predicate on the "rate_bps" field.
func RateBpsLT(v int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldLT(FieldRateBps, v))
}

// RateBpsLTE applies the LTE predicate on the "rate_bps" field.
func RateBpsLTE(v int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldLTE(FieldRateBps, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldContainsFold(FieldCurrency, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNotIn(FieldStatus, vs...))
}

// FreezeUntilEQ applies the EQ predicate on the "freeze_until" field.
func FreezeUntilEQ(v time.Time) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldFreezeUntil, v))
}

// FreezeUntilNEQ applies the NEQ predicate on the "freeze_until" field.
func FreezeUntilNEQ(v time.Time) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNEQ(FieldFreezeUntil, v))
}

// FreezeUntilIn applies the In predicate on the "freeze_until" field.
func FreezeUntilIn(vs ...time.Time) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldIn(FieldFreezeUntil, vs...))
}

// FreezeUntilNotIn applies the NotIn predicate on the "freeze_until" field.
func FreezeUntilNotIn(vs ...time.Time) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNotIn(FieldFreezeUntil, vs...))
}

// FreezeUntilGT applies the GT predicate on the "freeze_until" field.
func FreezeUntilGT(v time.Time) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldGT(FieldFreezeUntil, v))
}

// FreezeUntilGTE applies the GTE predicate on the "freeze_until" field.
func FreezeUntilGTE(v time.Time) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldGTE(FieldFreezeUntil, v))
}

// FreezeUntilLT applies the LT predicate on the "freeze_until" field.
func FreezeUntilLT(v time.Time) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldLT(FieldFreezeUntil, v))
}

// FreezeUntilLTE applies the LTE predicate on the "freeze_until" field.
func FreezeUntilLTE(v time.Time) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldLTE(FieldFreezeUntil, v))
}

// TransferredAtEQ applies the EQ predicate on the "transferred_at" field.
func TransferredAtEQ(v time.Time) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldTransferredAt, v))
}

// TransferredAtNEQ applies the NEQ predicate on the "transferred_at" field.
func TransferredAtNEQ(v time.Time) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNEQ(FieldTransferredAt, v))
}

// TransferredAtIn applies the In predicate on the "transferred_at" field.
func TransferredAtIn(vs ...time.Time) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldIn(FieldTransferredAt, vs...))
}

// TransferredAtNotIn applies the NotIn predicate on the "transferred_at" field.
func TransferredAtNotIn(vs ...time.Time) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNotIn(FieldTransferredAt, vs...))
}

// TransferredAtGT applies the GT predicate on the "transferred_at" field.
func TransferredAtGT(v time.Time) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldGT(FieldTransferredAt, v))
}

// TransferredAtGTE applies the GTE predicate on the "transferred_at" field.
func TransferredAtGTE(v time.Time) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldGTE(FieldTransferredAt, v))
}

// TransferredAtLT applies the LT predicate on the "transferred_at" field.
func TransferredAtLT(v time.Time) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldLT(FieldTransferredAt, v))
}

// TransferredAtLTE applies the LTE predicate on the "transferred_at" field.
func TransferredAtLTE(v time.Time) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldLTE(FieldTransferredAt, v))
}

// TransferredAtIsNil applies the IsNil predicate on the "transferred_at" field.
func TransferredAtIsNil() predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldIsNull(FieldTransferredAt))
}

// TransferredAtNotNil applies the NotNil predicate on the "transferred_at" field.
func TransferredAtNotNil() predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNotNull(FieldTransferredAt))
}

// LedgerTransactionIDEQ applies the EQ predicate on the "ledger_transaction_id" field.
func LedgerTransactionIDEQ(v int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldLedgerTransactionID, v))
}

// LedgerTransactionIDNEQ applies the NEQ predicate on the "ledger_transaction_id" field.
func LedgerTransactionIDNEQ(v int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNEQ(FieldLedgerTransactionID, v))
}

// LedgerTransactionIDIn applies the In predicate on the "ledger_transaction_id" field.
func LedgerTransactionIDIn(vs ...int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldIn(FieldLedgerTransactionID, vs...))
}

// LedgerTransactionIDNotIn applies the NotIn predicate on the "ledger_transaction_id" field.
func LedgerTransactionIDNotIn(vs ...int) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNotIn(FieldLedgerTransactionID, vs...))
}

// LedgerTransactionIDIsNil applies the IsNil predicate on the "ledger_transaction_id" field.
func LedgerTransactionIDIsNil() predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldIsNull(FieldLedgerTransactionID))
}

// LedgerTransactionIDNotNil applies the NotNil predicate on the "ledger_transaction_id" field.
func LedgerTransactionIDNotNil() predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNotNull(FieldLedgerTransactionID))
}

// IdempotencyKeyEQ applies the EQ predicate on the "idempotency_key" field.
func IdempotencyKeyEQ(v string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyNEQ applies the NEQ predicate on the "idempotency_key" field.
func IdempotencyKeyNEQ(v string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyIn applies the In predicate on the "idempotency_key" field.
func IdempotencyKeyIn(vs ...string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyNotIn applies the NotIn predicate on the "idempotency_key" field.
func IdempotencyKeyNotIn(vs ...string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNotIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyGT applies the GT predicate on the "idempotency_key" field.
func IdempotencyKeyGT(v string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldGT(FieldIdempotencyKey, v))
}

// IdempotencyKeyGTE applies the GTE predicate on the "idempotency_key" field.
func IdempotencyKeyGTE(v string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldGTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyLT applies the LT predicate on the "idempotency_key" field.
func IdempotencyKeyLT(v string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldLT(FieldIdempotencyKey, v))
}

// IdempotencyKeyLTE applies the LTE predicate on the "idempotency_key" field.
func IdempotencyKeyLTE(v string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldLTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyContains applies the Contains predicate on the "idempotency_key" field.
func IdempotencyKeyContains(v string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldContains(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasPrefix applies the HasPrefix predicate on the "idempotency_key" field.
func IdempotencyKeyHasPrefix(v string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldHasPrefix(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasSuffix applies the HasSuffix predicate on the "idempotency_key" field.
func IdempotencyKeyHasSuffix(v string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldHasSuffix(FieldIdempotencyKey, v))
}

// IdempotencyKeyEqualFold applies the EqualFold predicate on the "idempotency_key" field.
func IdempotencyKeyEqualFold(v string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEqualFold(FieldIdempotencyKey, v))
}

// IdempotencyKeyContainsFold applies the ContainsFold predicate on the "idempotency_key" field.
func IdempotencyKeyContainsFold(v string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldContainsFold(FieldIdempotencyKey, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.FieldContainsFold(FieldNotes, v))
}

// HasInvitation applies the HasEdge predicate on the "invitation" edge.
func HasInvitation() predicate.AffiliateRebate {
	return predicate.AffiliateRebate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, InvitationTable, InvitationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInvitationWith applies the HasEdge predicate on the "invitation" edge with a given conditions (other predicates).
func HasInvitationWith(preds ...predicate.AffiliateInvitation) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(func(s *sql.Selector) {
		step := newInvitationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasInviter applies the HasEdge predicate on the "inviter" edge.
func HasInviter() predicate.AffiliateRebate {
	return predicate.AffiliateRebate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, InviterTable, InviterColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInviterWith applies the HasEdge predicate on the "inviter" edge with a given conditions (other predicates).
func HasInviterWith(preds ...predicate.User) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(func(s *sql.Selector) {
		step := newInviterStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasInvitee applies the HasEdge predicate on the "invitee" edge.
func HasInvitee() predicate.AffiliateRebate {
	return predicate.AffiliateRebate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, InviteeTable, InviteeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInviteeWith applies the HasEdge predicate on the "invitee" edge with a given conditions (other predicates).
func HasInviteeWith(preds ...predicate.User) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(func(s *sql.Selector) {
		step := newInviteeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPaymentOrder applies the HasEdge predicate on the "payment_order" edge.
func HasPaymentOrder() predicate.AffiliateRebate {
	return predicate.AffiliateRebate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PaymentOrderTable, PaymentOrderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPaymentOrderWith applies the HasEdge predicate on the "payment_order" edge with a given conditions (other predicates).
func HasPaymentOrderWith(preds ...predicate.PaymentOrder) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(func(s *sql.Selector) {
		step := newPaymentOrderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUserSubscription applies the HasEdge predicate on the "user_subscription" edge.
func HasUserSubscription() predicate.AffiliateRebate {
	return predicate.AffiliateRebate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserSubscriptionTable, UserSubscriptionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserSubscriptionWith applies the HasEdge predicate on the "user_subscription" edge with a given conditions (other predicates).
func HasUserSubscriptionWith(preds ...predicate.UserSubscription) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(func(s *sql.Selector) {
		step := newUserSubscriptionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLedgerTransaction applies the HasEdge predicate on the "ledger_transaction" edge.
func HasLedgerTransaction() predicate.AffiliateRebate {
	return predicate.AffiliateRebate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, LedgerTransactionTable, LedgerTransactionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLedgerTransactionWith applies the HasEdge predicate on the "ledger_transaction" edge with a given conditions (other predicates).
func HasLedgerTransactionWith(preds ...predicate.LedgerTransaction) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(func(s *sql.Selector) {
		step := newLedgerTransactionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AffiliateRebate) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AffiliateRebate) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AffiliateRebate) predicate.AffiliateRebate {
	return predicate.AffiliateRebate(sql.NotPredicates(p))
}
