// Code generated by ent, DO NOT EDIT.

package upstreamaccountpool

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v int) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldEQ(FieldDeletedAt, v))
}

// ChannelID applies equality check predicate on the "channel_id" field. It's identical to ChannelIDEQ.
func ChannelID(v int) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldEQ(FieldChannelID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldEQ(FieldName, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldEQ(FieldPriority, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldEQ(FieldRemark, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v int) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v int) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...int) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...int) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v int) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v int) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v int) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v int) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldLTE(FieldDeletedAt, v))
}

// ChannelIDEQ applies the EQ predicate on the "channel_id" field.
func ChannelIDEQ(v int) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldEQ(FieldChannelID, v))
}

// ChannelIDNEQ applies the NEQ predicate on the "channel_id" field.
func ChannelIDNEQ(v int) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldNEQ(FieldChannelID, v))
}

// ChannelIDIn applies the In predicate on the "channel_id" field.
func ChannelIDIn(vs ...int) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldIn(FieldChannelID, vs...))
}

// ChannelIDNotIn applies the NotIn predicate on the "channel_id" field.
func ChannelIDNotIn(vs ...int) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldNotIn(FieldChannelID, vs...))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldContainsFold(FieldName, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldNotIn(FieldStatus, vs...))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldLTE(FieldPriority, v))
}

// ModelPatternsIsNil applies the IsNil predicate on the "model_patterns" field.
func ModelPatternsIsNil() predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldIsNull(FieldModelPatterns))
}

// ModelPatternsNotNil applies the NotNil predicate on the "model_patterns" field.
func ModelPatternsNotNil() predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldNotNull(FieldModelPatterns))
}

// ProjectIdsIsNil applies the IsNil predicate on the "project_ids" field.
func ProjectIdsIsNil() predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldIsNull(FieldProjectIds))
}

// ProjectIdsNotNil applies the NotNil predicate on the "project_ids" field.
func ProjectIdsNotNil() predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldNotNull(FieldProjectIds))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.FieldContainsFold(FieldRemark, v))
}

// HasChannel applies the HasEdge predicate on the "channel" edge.
func HasChannel() predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ChannelTable, ChannelColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChannelWith applies the HasEdge predicate on the "channel" edge with a given conditions (other predicates).
func HasChannelWith(preds ...predicate.Channel) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(func(s *sql.Selector) {
		step := newChannelStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccounts applies the HasEdge predicate on the "accounts" edge.
func HasAccounts() predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AccountsTable, AccountsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountsWith applies the HasEdge predicate on the "accounts" edge with a given conditions (other predicates).
func HasAccountsWith(preds ...predicate.UpstreamAccount) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(func(s *sql.Selector) {
		step := newAccountsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UpstreamAccountPool) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UpstreamAccountPool) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UpstreamAccountPool) predicate.UpstreamAccountPool {
	return predicate.UpstreamAccountPool(sql.NotPredicates(p))
}
